"""Generated by sutra_compiler.codegen_pytorch. Do not edit by hand."""
from __future__ import annotations

import torch as _torch

# Pick device and dtype once at module import. CUDA is preferred
# because the whole reason for this backend is to collapse the
# fused bind / bundle / argmax_cosine shapes into single big
# kernel launches on GPU. CPU fallback keeps the module usable
# on machines without CUDA — the numerics are identical.
_DEVICE = _torch.device('cuda' if _torch.cuda.is_available() else 'cpu')
# float32 on GPU is the fast path; keep dtype consistent across
# every tensor so einsum / matmul don't trigger implicit upcasts.
_DTYPE = _torch.float32


class _TorchVSA:
    """Torch-backed VSA runtime. Rotation binding, normalized bundle.

    State tensors carry the extended layout:
    `[semantic (semantic_dim) | synthetic (synthetic_dim)]`. The
    semantic block is filled by `embed()` from the frozen LLM; the
    synthetic block is reserved computational/symbolic space with
    canonical axes at synthetic[0..2] (real, imag, truth). See
    planning/findings/2026-04-21-extended-state-and-rotation-binding.md.

    Bind is role-seeded Haar-random orthogonal rotation applied to
    filler: bind(filler, role) = Q_role @ filler. The rotation is
    block-diagonal — Haar in the semantic block, identity in the
    synthetic block — so rotation acts only on semantic content and
    the synthetic block is preserved through bind/unbind.
    """

    # Canonical synthetic-axis allocation — real, imag, truth at
    # synthetic[0..2], char-flag at synthetic[3], loop-done at
    # synthetic[4]. Mirrored from the CPU runtime so the two agree
    # bit-for-bit on layout. AXIS_LOOP_DONE is the substrate-side
    # completion flag set by the RNN-style branchless loop.
    AXIS_REAL = 0
    AXIS_IMAG = 1
    AXIS_TRUTH = 2
    AXIS_CHAR_FLAG = 3
    AXIS_LOOP_DONE = 4

    def __init__(self, semantic_dim, synthetic_dim, seed, llm_model):
        self.semantic_dim = semantic_dim
        self.synthetic_dim = synthetic_dim
        self.dim = semantic_dim + synthetic_dim
        self.seed = seed
        self.llm_model = llm_model
        self.device = _DEVICE
        self.dtype = _DTYPE
        self._codebook = {}
        # Rotation matrix cache: role-hash -> tensor on self.device.
        # Generating a 768x768 Haar rotation is O(d^3) on CPU (seeded
        # via numpy for Haar-uniformity). Cached on the GPU after the
        # first draw so repeated bind/unbind with the same role is a
        # lookup + one matmul, no transfer.
        self._rot_cache = {}
        # On-disk embedding cache. Keyed by (model, dim) so switching
        # embedding model OR changing the extended-state dim invalidates
        # automatically (different filename). Torch cache uses .pt so
        # it doesn't collide with the numpy backend's .npz.
        import os as _os
        self._cache_dir = _os.path.join(
            _os.environ.get('XDG_CACHE_HOME', _os.path.expanduser('~/.cache')),
            'sutra', 'embeddings')
        _os.makedirs(self._cache_dir, exist_ok=True)
        _safe_model = llm_model.replace('/', '_').replace(':', '_')
        self._cache_path = _os.path.join(
            self._cache_dir, f'{_safe_model}-d{self.dim}.pt')
        self._load_disk_cache()

    def _load_disk_cache(self):
        """Populate self._codebook from disk if the cache file exists.

        Tolerant of missing or corrupt files — a failed load just leaves
        the codebook empty and lets Ollama repopulate it.
        """
        import os as _os
        if not _os.path.exists(self._cache_path):
            return
        try:
            data = _torch.load(self._cache_path, map_location=self.device, weights_only=True)
            for key, tensor in data.items():
                self._codebook[key] = tensor.to(dtype=self.dtype)
        except Exception:
            # Corrupt cache: ignore and let Ollama repopulate.
            self._codebook = {}

    def _write_disk_cache(self):
        """Persist self._codebook to disk via tempfile + atomic rename.

        A partial write (crash, SIGKILL) leaves the old cache intact
        rather than corrupted.
        """
        import os as _os, tempfile as _tempfile
        if not self._codebook:
            return
        fd, tmp = _tempfile.mkstemp(
            dir=self._cache_dir, prefix='.tmp-', suffix='.pt')
        _os.close(fd)
        try:
            # Save tensors on CPU so the cache file is portable — the
            # next run can load on any device. Reload will move them.
            cpu_codebook = {k: v.detach().cpu() for k, v in self._codebook.items()}
            _torch.save(cpu_codebook, tmp)
            _os.replace(tmp, self._cache_path)
        except Exception:
            try:
                _os.unlink(tmp)
            except OSError:
                pass

    def embed(self, name):
        """Frozen-LLM embedding via Ollama. Returns a tensor on self.device.

        Extended-state layout: `[semantic (semantic_dim) | zeros (synthetic_dim)]`.
        No random fallback — if Ollama is unavailable this raises.
        """
        if name not in self._codebook:
            import ollama
            r = ollama.embed(model=self.llm_model, input=name)
            v = _torch.tensor(r['embeddings'][0], dtype=self.dtype, device=self.device)
            # Mean-center; raw LLM embeddings cluster in a cone and centering
            # keeps rotation/bind algebra well-behaved.
            v = v - _torch.mean(v)
            n = _torch.linalg.norm(v)
            if n > 0: v = v / n
            # Fit to semantic block.
            if v.shape[0] > self.semantic_dim:
                v = v[:self.semantic_dim]
            elif v.shape[0] < self.semantic_dim:
                pad = _torch.zeros(self.semantic_dim - v.shape[0], dtype=self.dtype, device=self.device)
                v = _torch.cat([v, pad])
            # Append synthetic block — reserved, starts zero.
            syn = _torch.zeros(self.synthetic_dim, dtype=self.dtype, device=self.device)
            v = _torch.cat([v, syn])
            n = _torch.linalg.norm(v)
            if n > 0: v = v / n
            self._codebook[name] = v
            self._write_disk_cache()
        return self._codebook[name].clone()

    def embed_batch(self, names):
        """Batched Ollama embed: one HTTP round-trip for many names.

        Same layout as embed(). Writes back to disk once after all
        fetches to amortize the save.
        """
        missing = [n for n in names if n not in self._codebook]
        if not missing:
            return
        import ollama
        r = ollama.embed(model=self.llm_model, input=missing)
        for i, name in enumerate(missing):
            v = _torch.tensor(r['embeddings'][i], dtype=self.dtype, device=self.device)
            v = v - _torch.mean(v)
            n = _torch.linalg.norm(v)
            if n > 0: v = v / n
            if v.shape[0] > self.semantic_dim:
                v = v[:self.semantic_dim]
            elif v.shape[0] < self.semantic_dim:
                pad = _torch.zeros(self.semantic_dim - v.shape[0], dtype=self.dtype, device=self.device)
                v = _torch.cat([v, pad])
            syn = _torch.zeros(self.synthetic_dim, dtype=self.dtype, device=self.device)
            v = _torch.cat([v, syn])
            n = _torch.linalg.norm(v)
            if n > 0: v = v / n
            self._codebook[name] = v
        self._write_disk_cache()

    # ---- Embedded SutraDB (compile-time string codebook) ----
    # Per Emma 2026-04-30 (queue item 2): every embedded string in a
    # Sutra program goes into SutraDB at compile time. The embeddings
    # don't live in the Python module's data section — they live in
    # the .sdb file SutraDB manages. Runtime can decode any query
    # vector back to a string via nearest_string() — the inverse of
    # embed(). Strings declared but not used in expressions still get
    # inserted, so they remain decodable.

    def _ensure_sutradb(self):
        """Lazy-init the SutraDB handle on first use. Returns None if the
        FFI DLL isn't built (caller decides what to do).

        Path resolution (queue item 2 piece 5):
          1. env var SUTRA_DB_PATH if set (persistent across runs)
          2. else a tempdir (ephemeral; freed at process exit)

        Full atman.toml [vector_db] section is deferred until there's a
        concrete config requirement — env var covers the immediate
        'persistent codebook' use case.
        """
        if hasattr(self, '_sutradb') and self._sutradb is not None:
            return self._sutradb
        try:
            import importlib, tempfile, os as _os2
            mod = importlib.import_module('sutra_compiler.sutradb_embedded')
            env_path = _os2.environ.get('SUTRA_DB_PATH')
            if env_path:
                path = env_path
                self._sutradb_tmpdir = None
            else:
                self._sutradb_tmpdir = tempfile.mkdtemp(prefix='sutra_codebook_')
                path = _os2.path.join(self._sutradb_tmpdir, 'codebook.sdb')
            self._sutradb = mod.SutraDBEmbedded(path)
            return self._sutradb
        except Exception:
            self._sutradb = None  # mark attempted-and-failed
            return None

    def populate_sutradb(self):
        """Push every codebook entry into SutraDB.

        Called from the codegen prelude after embed_batch finishes
        populating self._codebook. Each (name, vec) becomes a triple
        <urn:sutra:label:NAME> <urn:sutra:embedding> "VEC"^^<f32vec> .
        """
        db = self._ensure_sutradb()
        if db is None:
            return  # FFI unavailable; nearest_string will return None
        for name, vec in self._codebook.items():
            # Skip non-URL-safe characters in label by URL-quoting.
            import urllib.parse as _urllib_parse
            safe = _urllib_parse.quote(name, safe='')
            vec_list = vec.tolist() if hasattr(vec, 'tolist') else list(vec)
            try:
                db.add(safe, vec_list)
            except Exception:
                pass  # one bad insert shouldn't kill the rest

    def prewarm_rotation_cache(self):
        """Pre-compute rotation matrices for every codebook entry.

        Per Emma 2026-04-30 (queue item 3): the runtime should never
        pay the QR construction cost on the hot path. Pre-warming at
        module init means every bind/unbind hits the cache. Conservative
        over the codebook (some entries are fillers, not roles); the
        cost is one-time and proportional to codebook size.
        """
        for name, vec in self._codebook.items():
            try:
                self._rotation_for(vec)
            except Exception:
                pass  # one bad rotation shouldn't kill the rest

    def nearest_string(self, query):
        """Inverse of embed(): given a query vector, return the nearest
        string from the compile-time-populated SutraDB codebook. None
        if SutraDB is unavailable. The query vector is the full extended-
        state vector; only the semantic block is consulted by SutraDB.
        """
        db = self._ensure_sutradb()
        if db is None:
            return None
        q_list = query.tolist() if hasattr(query, 'tolist') else list(query)
        try:
            labels = db.nearest(q_list, k=1)
        except Exception:
            return None
        if not labels:
            return None
        import urllib.parse as _urllib_parse
        return _urllib_parse.unquote(labels[0])

    def _role_hash(self, role_vec):
        """Deterministic uint32 seed from a role tensor.

        Computed from the CPU bytes of the tensor so numerical bit-
        identity across runs gives the same rotation. Matches the
        numpy backend's hash scheme exactly when the semantic content
        is bit-for-bit equal.
        """
        import hashlib
        b = role_vec.detach().cpu().contiguous().numpy().tobytes()
        h = hashlib.blake2b(b, digest_size=8).digest()
        return int.from_bytes(h, 'little') & 0xFFFFFFFF

    def _rotation_for(self, role_vec):
        """Block-diagonal Haar rotation seeded by the role tensor.

        Haar-uniform in the semantic block, identity in the synthetic
        block — same layout as the numpy backend so rotation-binding
        semantics are identical. The Haar draw uses numpy because
        numpy's RandomState(seed) is the canonical bit-reproducible
        generator; we move the result to the torch device before
        caching.

        Cached per role-hash so the same role always produces the same
        rotation — required for bind/unbind round-trip.
        """
        key = self._role_hash(role_vec)
        if key not in self._rot_cache:
            import numpy as _np_bridge
            rng = _np_bridge.random.RandomState(key)
            A = rng.randn(self.semantic_dim, self.semantic_dim)
            Q_sem_np, R_np = _np_bridge.linalg.qr(A)
            d = _np_bridge.sign(_np_bridge.diag(R_np))
            d[d == 0] = 1.0
            Q_sem_np = Q_sem_np * d
            Q_sem = _torch.as_tensor(Q_sem_np, dtype=self.dtype, device=self.device)
            # Block-diagonal embedding: Q_sem on the semantic block,
            # identity everywhere else.
            Q = _torch.eye(self.dim, dtype=self.dtype, device=self.device)
            Q[:self.semantic_dim, :self.semantic_dim] = Q_sem
            self._rot_cache[key] = Q
        return self._rot_cache[key]

    def bind(self, role, filler):
        # Rotation binding. bind(role, filler) = Q_role @ filler. Role-
        # first convention (matches numpy backend and the .su demos).
        Q = self._rotation_for(role)
        return Q @ filler

    def unbind(self, role, record):
        # Q is orthogonal so unbind(role, record) = Q_role^T @ record.
        # Round-trip: unbind(r, bind(r, v)) = Q^T @ Q @ v = v exactly.
        Q = self._rotation_for(role)
        return Q.T @ record

    def bundle(self, *vectors):
        s = _torch.stack([
            _torch.as_tensor(v, dtype=self.dtype, device=self.device)
            for v in vectors
        ]).sum(dim=0)
        n = _torch.linalg.norm(s)
        return s / n if n > 0 else s

    def zero_vector(self):
        """Zero vector in the runtime dim. Emitted by simplifier identities."""
        return _torch.zeros(self.dim, dtype=self.dtype, device=self.device)

    def bundle_of_binds(self, *role_filler_pairs):
        """Fused bind+sum+normalize over N role-filler pairs.

        This is the GPU-shaped primitive: stack roles into (N, d, d),
        stack fillers into (N, d), one batched einsum + reduce. On
        CUDA, N small bind+bundle kernel launches collapse into O(1)
        big launches. Same numerics as sequential bind + bundle.
        """
        if not role_filler_pairs:
            return self.zero_vector()
        roles = [rf[0] for rf in role_filler_pairs]
        fillers = [rf[1] for rf in role_filler_pairs]
        Q_stack = _torch.stack([self._rotation_for(r) for r in roles])
        F_stack = _torch.stack([
            _torch.as_tensor(f, dtype=self.dtype, device=self.device)
            for f in fillers
        ])
        # Batched bind: element-i is Q_i @ f_i; shape (N, d).
        bound = _torch.einsum('nij,nj->ni', Q_stack, F_stack)
        s = bound.sum(dim=0)
        n = _torch.linalg.norm(s)
        return s / n if n > 0 else s

    # ---- Rotation-hashmap (same shape as numpy backend) ----

    def hashmap_new(self):
        return _torch.zeros(self.dim, dtype=self.dtype, device=self.device)

    def hashmap_set(self, acc, key_vec, val_vec):
        return acc + self.bind(key_vec, val_vec)

    def hashmap_get(self, acc, key_vec):
        return self.unbind(key_vec, acc)

    # ---- 2D-Givens-per-slot rotation binding (synthetic subspace) ----
    # Mirrors the numpy backend slot block; see codegen.py.
    # SLOT_BASE = 5 to leave room for AXIS_LOOP_DONE at synthetic[4].
    SLOT_BASE = 5

    def _slot_plane(self, slot_idx):
        n_planes = (self.synthetic_dim - self.SLOT_BASE) // 2
        if n_planes <= 0:
            raise RuntimeError(
                "synthetic subspace has no room for slot planes; "
                "increase synthetic_dim or SLOT_BASE budget")
        s = int(slot_idx) % n_planes
        base = self.semantic_dim + self.SLOT_BASE + 2 * s
        return (base, base + 1)

    def slot_store(self, state, slot_idx, scalar):
        i, j = self._slot_plane(slot_idx)
        new = state.clone() if hasattr(state, 'clone') else state.copy()
        new[i] = float(scalar)
        new[j] = 0.0
        return new

    def slot_load(self, state, slot_idx):
        """Read the slot scalar. Returns a torch 0-dim tensor.

        Substrate-pure: downstream arithmetic stays in tensor land. See
        planning/findings/2026-04-30-substrate-purity-leak-enumeration.md.
        """
        i, _j = self._slot_plane(slot_idx)
        return state[i]

    # ---- Binding-array primitive (substrate-stored ordered list) ----
    # Layout: arr[0] = length scalar, arr[1..length] = elements. Used by
    # foreach_loop. Pure tensor reads/writes; no Python list, no heap
    # allocation beyond the initial tensor.

    def array_from_literal(self, *values):
        """Build an array from compile-time-known scalar values."""
        arr = _torch.zeros(len(values) + 1, dtype=self.dtype, device=self.device)
        arr[0] = float(len(values))
        for i, v in enumerate(values):
            arr[1 + i] = float(v)
        return arr

    def array_length(self, arr):
        """Read the length prefix as an int (used for Python loop bound)."""
        return int(arr[0].item())

    def array_get(self, arr, i):
        """Read element at index i (0-based). Returns torch 0-dim tensor."""
        return arr[1 + int(i)]

    # ---- Substrate scalar primitives (boundary-leak reductions) ----

    def truth_axis(self, vec_or_scalar):
        """Read AXIS_TRUTH from a fuzzy-vector result, or pass scalars through.

        Returns a torch 0-dim tensor; substrate-pure loop halt checks consume
        the result without crossing the Python boundary.
        """
        if hasattr(vec_or_scalar, '__len__') and len(vec_or_scalar) > 1:
            return vec_or_scalar[self.semantic_dim + self.AXIS_TRUTH]
        if _torch.is_tensor(vec_or_scalar):
            return vec_or_scalar
        return _torch.tensor(vec_or_scalar, dtype=self.dtype, device=self.device)

    def heaviside(self, x):
        """Step function: 1.0 where x > 0, else 0.0. Torch 0-dim tensor."""
        if not _torch.is_tensor(x):
            x = _torch.tensor(x, dtype=self.dtype, device=self.device)
        zero = _torch.zeros((), dtype=self.dtype, device=self.device)
        return _torch.heaviside(x.to(self.dtype), zero)

    def saturate_unit(self, x):
        """min(x, 1.0) implemented as torch.minimum. Torch 0-dim tensor."""
        if not _torch.is_tensor(x):
            x = _torch.tensor(x, dtype=self.dtype, device=self.device)
        one = _torch.ones((), dtype=self.dtype, device=self.device)
        return _torch.minimum(x, one)

    def rotate_slot(self, state, slot_idx, angle):
        import math as _math
        i, j = self._slot_plane(slot_idx)
        c, s = _math.cos(float(angle)), _math.sin(float(angle))
        new = state.clone() if hasattr(state, 'clone') else state.copy()
        xi, xj = float(state[i]), float(state[j])
        new[i] = c * xi - s * xj
        new[j] = s * xi + c * xj
        return new

    def similarity(self, a, b):
        na = _torch.linalg.norm(a)
        nb = _torch.linalg.norm(b)
        # eps-guarded divide — zero-norm case evaluates to 0 without branch.
        return float(_torch.dot(a, b) / (na * nb + _torch.finfo(self.dtype).tiny))

    # ---- Vector component accessors (debugging / teaching) ----

    def component(self, v, i):
        """Return element i of v over the full extended state vector."""
        return float(v[int(i)].item())

    def semantic(self, v, i):
        """Return element i within the semantic block."""
        idx = int(i)
        if idx < 0 or idx >= self.semantic_dim:
            raise IndexError(
                f"semantic index {idx} out of range [0, {self.semantic_dim})")
        return float(v[idx].item())

    def synthetic(self, v, i):
        """Return element i within the synthetic block."""
        idx = int(i)
        if idx < 0 or idx >= self.synthetic_dim:
            raise IndexError(
                f"synthetic index {idx} out of range [0, {self.synthetic_dim})")
        return float(v[self.semantic_dim + idx].item())

    # ---- Canonical-axis accessors (real/imag/truth) ----

    def real(self, v):
        return float(v[self.semantic_dim + self.AXIS_REAL].item())

    def imag(self, v):
        return float(v[self.semantic_dim + self.AXIS_IMAG].item())

    def truth(self, v):
        return float(v[self.semantic_dim + self.AXIS_TRUTH].item())

    def make_real(self, x):
        v = _torch.zeros(self.dim, dtype=self.dtype, device=self.device)
        v[self.semantic_dim + self.AXIS_REAL] = float(x)
        return v

    def make_complex(self, re, im):
        v = _torch.zeros(self.dim, dtype=self.dtype, device=self.device)
        v[self.semantic_dim + self.AXIS_REAL] = float(re)
        v[self.semantic_dim + self.AXIS_IMAG] = float(im)
        return v

    def _swap_ri_matrix(self):
        if not hasattr(self, '_swap_ri_cache') or self._swap_ri_cache is None:
            M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)
            r = self.semantic_dim + self.AXIS_REAL
            i = self.semantic_dim + self.AXIS_IMAG
            M[r, i] = 1.0; M[i, r] = 1.0
            self._swap_ri_cache = M
        return self._swap_ri_cache

    def _cm_real_matrix(self):
        if not hasattr(self, '_cm_real_cache') or self._cm_real_cache is None:
            M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)
            r = self.semantic_dim + self.AXIS_REAL
            i = self.semantic_dim + self.AXIS_IMAG
            M[r, r] = 1.0; M[r, i] = -1.0
            self._cm_real_cache = M
        return self._cm_real_cache

    def _cm_imag_matrix(self):
        if not hasattr(self, '_cm_imag_cache') or self._cm_imag_cache is None:
            M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)
            r = self.semantic_dim + self.AXIS_REAL
            i = self.semantic_dim + self.AXIS_IMAG
            M[i, r] = 1.0; M[i, i] = 1.0
            self._cm_imag_cache = M
        return self._cm_imag_cache

    def complex_mul(self, a, b):
        """Complex product: matrix form, no scalar extraction.

        c = _cm_real @ (a * b) + _cm_imag @ ((_swap_ri @ a) * b)
        """
        av = self._as_complex_vector(a)
        bv = self._as_complex_vector(b)
        ab = av * bv
        swapped_ab = (self._swap_ri_matrix() @ av) * bv
        return self._cm_real_matrix() @ ab + self._cm_imag_matrix() @ swapped_ab

    def _as_complex_vector(self, x):
        """Coerce Python scalar / tensor to complex-plane form."""
        if isinstance(x, _torch.Tensor):
            return x
        if isinstance(x, bool):
            return self.make_real(1.0 if x else 0.0)
        return self.make_real(float(x))

    def make_truth(self, t):
        v = _torch.zeros(self.dim, dtype=self.dtype, device=self.device)
        v[self.semantic_dim + self.AXIS_TRUTH] = float(t)
        return v

    def make_char(self, codepoint):
        """Character literal: code point at AXIS_REAL, flag at AXIS_CHAR_FLAG."""
        v = _torch.zeros(self.dim, dtype=self.dtype, device=self.device)
        v[self.semantic_dim + self.AXIS_REAL] = float(codepoint)
        v[self.semantic_dim + self.AXIS_CHAR_FLAG] = 1.0
        return v

    def is_char(self, v):
        """True iff v was produced as a character literal."""
        return bool(v[self.semantic_dim + self.AXIS_CHAR_FLAG].item() >= 0.5)

    def make_trit(self, t):
        """Three-valued primitive class — aliases make_truth."""
        return self.make_truth(t)

    def defuzzify_trit(self, v, iters=10, beta=2.0):
        """Three-way polarizer toward {-1, 0, +1} — torch version."""
        x = float(v[self.semantic_dim + self.AXIS_TRUTH].item())
        b = float(beta)
        for _ in range(int(iters)):
            import math as _math
            w_neg = _math.exp(-b * (x + 1.0) ** 2)
            w_zero = _math.exp(-b * x ** 2)
            w_pos = _math.exp(-b * (x - 1.0) ** 2)
            s = w_neg + w_zero + w_pos
            x = (-w_neg + w_pos) / s
            b *= 2.0
        out = v.clone()
        out[self.semantic_dim + self.AXIS_TRUTH] = float(x)
        return out

    # ---- Logical operators — smooth polynomial form ----
    #
    # Same Lagrange-derived polynomials as the numpy backend:
    #   min(a, b) = (a + b + ab - a² - b² + a²b²) / 2
    #   max(a, b) = (a + b - ab + a² + b² - a²b²) / 2
    # Exact on {-1, 0, +1}², C^∞ everywhere, CUDA via torch ops.

    def _as_truth_vector(self, x):
        """Return x as a tensor. Scalar / bool → make_truth."""
        if isinstance(x, _torch.Tensor):
            return x
        if isinstance(x, bool):
            return self.make_truth(1.0 if x else -1.0)
        return self.make_truth(float(x))

    # ---- Ordered comparison — pure tensor ops, no branches ----

    def _real_projector(self):
        """Diagonal real-axis projector. Cached tensor on device."""
        if not hasattr(self, '_real_proj_cache') or self._real_proj_cache is None:
            M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)
            idx = self.semantic_dim + self.AXIS_REAL
            M[idx, idx] = 1.0
            self._real_proj_cache = M
        return self._real_proj_cache

    def _truth_from_real(self):
        """Matrix moving the real-axis entry to the truth axis."""
        if not hasattr(self, '_t_from_r_cache') or self._t_from_r_cache is None:
            M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)
            M[self.semantic_dim + self.AXIS_TRUTH,
                self.semantic_dim + self.AXIS_REAL] = 1.0
            self._t_from_r_cache = M
        return self._t_from_r_cache

    CMP_SLOPE = 100.0

    def gt(self, a, b):
        """a > b — differentiable tanh on real-axis difference."""
        av = self._as_complex_vector(a)
        bv = self._as_complex_vector(b)
        diff_r = self._real_projector() @ (av - bv)
        signed = _torch.tanh(self.CMP_SLOPE * diff_r)
        return self._truth_from_real() @ signed

    # ---- Equality — cosine similarity on tensors ----

    def eq(self, a, b):
        """a == b — cosine similarity, eps-guarded divide, no branch."""
        av = self._as_any_vector(a)
        bv = self._as_any_vector(b)
        na = _torch.sqrt((av * av).sum())
        nb = _torch.sqrt((bv * bv).sum())
        cos = (av * bv).sum() / (na * nb + _torch.finfo(self.dtype).tiny)
        return self.make_truth(float(cos.item()))

    def _as_any_vector(self, x):
        """Coerce any runtime value to a d-dim tensor for comparison."""
        if isinstance(x, _torch.Tensor):
            return x
        if isinstance(x, bool):
            return self.make_truth(1.0 if x else -1.0)
        if isinstance(x, (int, float)):
            return self.make_real(float(x))
        if isinstance(x, str):
            return self.embed(x)
        raise TypeError(f'cannot coerce {type(x).__name__} to a tensor for comparison')

    # ---- Defuzzification — torch version ----

    def _truth_projector(self):
        """Diagonal dim×dim projector onto truth axis. Cached tensor."""
        if not hasattr(self, '_truth_proj_cache') or self._truth_proj_cache is None:
            M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)
            idx = self.semantic_dim + self.AXIS_TRUTH
            M[idx, idx] = 1.0
            self._truth_proj_cache = M
        return self._truth_proj_cache


    def make_random_rotation(self, angle, n_planes=1, seed=None):
        """Block-diagonal Haar rotation, scaled by fractional power.

        Seeded by numpy's RandomState for deterministic Haar-uniformity;
        the result is converted to a torch tensor on self.device. Used
        by eigenrotation loops.
        """
        import numpy as _np_bridge
        rng = _np_bridge.random.RandomState(seed if seed is not None else self.seed)
        A = rng.randn(self.semantic_dim, self.semantic_dim)
        Q_sem_np, _ = _np_bridge.linalg.qr(A)
        w, V = _np_bridge.linalg.eig(Q_sem_np)
        phases = _np_bridge.angle(w) * (angle / _np_bridge.pi)
        R_sem_np = _np_bridge.real((V * _np_bridge.exp(1j * phases)) @ _np_bridge.linalg.inv(V))
        R_sem = _torch.as_tensor(R_sem_np, dtype=self.dtype, device=self.device)
        R = _torch.eye(self.dim, dtype=self.dtype, device=self.device)
        R[:self.semantic_dim, :self.semantic_dim] = R_sem
        return R

    def compile_prototypes(self, prototype_vectors, frame_seed=None):
        return dict(prototype_vectors)

    def _step(self, state, R, target, halt_cum, k, threshold, eps=1e-12):
        """RNN cell: one branchless eigenrotation step (torch tensor ops)."""
        cand = R @ state
        cand = cand / (_torch.linalg.norm(cand) + eps)
        sim = _torch.dot(cand, target) / (_torch.linalg.norm(target) + eps)
        halt = 1.0 / (1.0 + _torch.exp(-k * (sim - threshold)))
        one = _torch.tensor(1.0, dtype=self.dtype, device=self.device)
        halt_cum = _torch.minimum(halt_cum + halt, one)
        state = (1.0 - halt_cum) * cand + halt_cum * state
        return state, halt_cum

    def loop(self, initial_state, rotation, compiled_prototypes,
        target_name=None, threshold=0.5, max_iters=50, k=20.0, frame_seed=None):
        """Branchless RNN-style eigenrotation loop (torch backend).

        Same semantics as the numpy backend. T-step unroll, soft halt via
        sigmoid, output gating via AXIS_LOOP_DONE. Autograd-friendly:
        every op is differentiable with respect to state, target, threshold.
        """
        state = initial_state.clone()
        halt_cum = _torch.tensor(0.0, dtype=self.dtype, device=self.device)
        iters_active = _torch.tensor(0.0, dtype=self.dtype, device=self.device)
        if target_name is not None:
            target = compiled_prototypes[target_name]
        else:
            target = next(iter(compiled_prototypes.values()))
        for _t in range(max_iters):
            iters_active = iters_active + (1.0 - halt_cum)
            state, halt_cum = self._step(state, rotation, target, halt_cum, k, threshold)
        # Output gating: scale value axes by halt_cum; mark AXIS_LOOP_DONE.
        gated = state * halt_cum
        gated[self.semantic_dim + self.AXIS_LOOP_DONE] = halt_cum
        return target_name, gated, iters_active


_VSA = _TorchVSA(semantic_dim=50, synthetic_dim=100, seed=42, llm_model='nomic-embed-text')
_VSA.embed_batch(['hello_world', 'goodbye', 'are_you_there'])
_VSA.populate_sutradb()
_VSA.prewarm_rotation_cache()


def _argmax_cosine(query, candidates):
    """Vectorized cosine argmax on torch tensors.

    Stacks candidates into (N, d), computes all N cosines as one
    matmul against the query, returns the candidate at the argmax.
    This is the GPU-shaped form: O(1) big kernel, not O(N) small ones.

    Note: SutraDB integration (queue item 2) does NOT route through
    here — see _VSA.nearest_string for the embedded-DB decode path.
    argmax_cosine takes a runtime candidate-vector list; SutraDB is
    the compile-time-populated string-to-embedding store.
    """
    if not candidates:
        return None
    M = _torch.stack([
        _torch.as_tensor(c, dtype=_DTYPE, device=_DEVICE)
        for c in candidates
    ])
    q = _torch.as_tensor(query, dtype=_DTYPE, device=_DEVICE)
    row_norms = _torch.linalg.norm(M, dim=1)
    q_norm = _torch.linalg.norm(q)
    if float(q_norm) == 0:
        return candidates[0]
    safe_rn = _torch.where(row_norms > 0, row_norms, _torch.ones_like(row_norms))
    scores = (M @ q) / (safe_rn * q_norm)
    neg_inf = _torch.full_like(scores, float('-inf'))
    scores = _torch.where(row_norms > 0, scores, neg_inf)
    return candidates[int(_torch.argmax(scores).item())]


def _select_softmax(scores, options):
    """Softmax-weighted superposition of option vectors (torch)."""
    s = _torch.as_tensor(scores, dtype=_DTYPE, device=_DEVICE)
    s = s - _torch.amax(s)
    w = _torch.exp(s)
    w = w / _torch.sum(w)
    opts = _torch.stack([
        _torch.as_tensor(o, dtype=_DTYPE, device=_DEVICE)
        for o in options
    ])
    return (w[:, None] * opts).sum(dim=0)

def _vector_map_lookup(pairs, key):
    """Identity-first lookup for vector-keyed maps, cosine fallback."""
    for k, v in pairs:
        if k is key:
            return v
    if not pairs:
        return None
    keys = _torch.stack([
        _torch.as_tensor(k, dtype=_DTYPE, device=_DEVICE)
        for k, _ in pairs
    ])
    q = _torch.as_tensor(key, dtype=_DTYPE, device=_DEVICE)
    row_norms = _torch.linalg.norm(keys, dim=1)
    q_norm = _torch.linalg.norm(q)
    if float(q_norm) == 0:
        return pairs[0][1]
    safe_rn = _torch.where(row_norms > 0, row_norms, _torch.ones_like(row_norms))
    scores = (keys @ q) / (safe_rn * q_norm)
    neg_inf = _torch.full_like(scores, float('-inf'))
    scores = _torch.where(row_norms > 0, scores, neg_inf)
    return pairs[int(_torch.argmax(scores).item())][1]

greeting = _VSA.embed('hello_world')

v_hello = _VSA.embed('hello_world')

v_goodbye = _VSA.embed('goodbye')

v_question = _VSA.embed('are_you_there')

PHRASE_NAME = [(v_hello, 'hello world'), (v_goodbye, 'goodbye'), (v_question, 'are you there')]

def say():
    _program_halt = 1.0
    winner = _argmax_cosine(greeting, [v_hello, v_goodbye, v_question])
    return _vector_map_lookup(PHRASE_NAME, winner)

def main():
    _program_halt = 1.0
    return say()

