"""Smoke test for the `ts2su` CLI.

The lowering engine has dedicated fixture-driven coverage in
`test_lower_fixtures.py`. This file is the missing layer above it: a
direct invocation of the CLI (`python -m sutra_from_ts ...`) on a
real fixture, with the assertion that the output file appears on
disk and contains valid-looking Sutra source.

Locks: (a) the CLI does not regress to the pre-v0.1.0 "skeleton —
not implemented" state, and (b) the default output-path computation
(`.ts` → `.su`) keeps working.
"""

from __future__ import annotations

import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
FIXTURE = HERE / "fixtures" / "array_sum" / "input.ts"


def test_cli_writes_su_file_to_explicit_output(tmp_path: pathlib.Path) -> None:
    """`ts2su -o ...` writes a file with the expected header."""
    out = tmp_path / "out.su"
    result = subprocess.run(
        [sys.executable, "-m", "sutra_from_ts", str(FIXTURE), "-o", str(out)],
        capture_output=True, text=True, timeout=30,
    )
    assert result.returncode == 0, (
        f"ts2su exited {result.returncode}; "
        f"stdout={result.stdout!r} stderr={result.stderr!r}"
    )
    assert out.exists(), f"ts2su should have written {out}"
    content = out.read_text(encoding="utf-8")
    assert content.startswith("// Generated by sutra-from-ts"), (
        f"output should start with the generator marker; got: {content[:80]!r}"
    )
    # Sanity-check that real lowering happened (function decl present).
    assert "function int sum_arr" in content


def test_cli_default_output_path_replaces_extension(tmp_path: pathlib.Path) -> None:
    """`ts2su input.ts` writes `input.su` next to the source."""
    # Copy the fixture into a tmpdir so the test does not pollute
    # the fixtures directory with a sibling .su file.
    src = tmp_path / "demo.ts"
    src.write_text(FIXTURE.read_text(encoding="utf-8"), encoding="utf-8")

    result = subprocess.run(
        [sys.executable, "-m", "sutra_from_ts", str(src)],
        capture_output=True, text=True, timeout=30,
    )
    assert result.returncode == 0, result.stderr
    expected_out = src.with_suffix(".su")
    assert expected_out.exists(), (
        f"default output path should be {expected_out} ({expected_out.parent}/* = "
        f"{[p.name for p in expected_out.parent.iterdir()]})"
    )


def test_cli_missing_input_returns_nonzero(tmp_path: pathlib.Path) -> None:
    """A nonexistent input path is a clean error, not a crash."""
    bogus = tmp_path / "nope.ts"
    result = subprocess.run(
        [sys.executable, "-m", "sutra_from_ts", str(bogus), "-o", str(tmp_path / "x.su")],
        capture_output=True, text=True, timeout=30,
    )
    assert result.returncode != 0, "ts2su should reject missing input"
    assert "cannot read" in result.stderr.lower() or "no such" in result.stderr.lower()


def test_cli_version_flag() -> None:
    """`ts2su --version` prints the version and exits zero."""
    result = subprocess.run(
        [sys.executable, "-m", "sutra_from_ts", "--version"],
        capture_output=True, text=True, timeout=30,
    )
    assert result.returncode == 0
    # argparse writes --version to stdout
    assert "ts2su" in result.stdout
