"""Generate apps/font/font_bound.su from tools/font_data.py.

Bound-vector implementation of the font demo per planning/26-font-bound-vector-
rewrite.md. The existing tools/generate_font_su.py emits a 36-way x 25-way
defuzzified-select tree (~22500 substrate branches per keypress); this
generator emits the rotation-binding pattern instead:

  - 25 position basis vectors (p_00..p_24) — one rotation role per (x, y) cell.
  - LIT / UNLIT basis vectors — fillers.
  - 36 per-character glyph bundles, each a bundle of 25 (position |-> LIT or
    UNLIT) bindings.
  - glyph_pixel_antipodal(x, y, char_code) — 36-way outer select picks the right
    glyph bundle by char_code, 25-way inner select picks the right pos basis
    by (x, y), then unbind(pos, glyph) -> bit_vec; return make_real(
    similarity(bit_vec, LIT)).

The substrate output is fuzzy (a cosine similarity in roughly [0, 1] with
rotation-binding noise from the 25 bound items per glyph). The host clips
to {0, 1} for display. Existing tests/test_font.py uses 1e-9 tolerance and
WILL NOT pass against this output — that's expected, the rewrite is fuzzy
by design and gets its own measured-capacity test (test_font_bound.py).

Re-run after editing tools/font_data.py:

    python tools/generate_font_bound_su.py
"""
from __future__ import annotations

import pathlib
import sys

_HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))

from font_data import CHARS_ORDER, bits_for  # noqa: E402


_HEADER = """\
// font_bound.su -- GENERATED by tools/generate_font_bound_su.py.
// DO NOT EDIT BY HAND -- regenerate via `python tools/generate_font_bound_su.py`.
//
// Bound-vector rewrite of font.su per planning/26-font-bound-vector-rewrite.md.
// Each character is a single bundle of 25 (position -> lit/unlit) rotation-
// bindings; the glyph_pixel lookup unbinds the position from the glyph and
// returns the cosine similarity to LIT on the real axis.
//
// Per keypress this dispatches ~25 cells * (36-way outer select + 25-way pos
// select + 1 unbind + 1 similarity) ~= 1600 substrate ops, vs ~22500 in
// the original font.su (25-way inner switch per character). The bottleneck
// on this runtime is Python -> torch dispatch overhead, so fewer ops -> faster
// wall clock even when the per-op tensor work is identical.
//
// Trade-off: substrate output is FUZZY (rotation-binding noise from the 25
// bound items per glyph). Cosine to LIT is ~1.0 for lit cells, ~0.0 for unlit,
// with capacity-dependent crosstalk. The host displays the field clipped to
// [0, 1]. Existing tests/test_font.py uses 1e-9 tolerance and will NOT pass
// against this output -- that's expected; this gets its own measured-tolerance
// test in tests/test_font_bound.py.
//
// @fv-claim: classifier test=demos/font/test_font_bound_antipodal.py
"""


def _basis_decl(name: str) -> str:
    # Distinct namespace from font_bound.su's keys so the two variants don't
    # share a codebook entry — each gets independent (semantic-fresh) embeddings.
    return f'vector {name} = embed("font_bound_antipodal_{name}");'


def gen_basis_block() -> str:
    """Position basis (25) + LIT + UNLIT + per-character basis (36)."""
    lines: list[str] = []
    lines.append("// --- Basis vectors (codebook entries; embedded once at module load) ---")
    lines.append("// 25 position basis vectors, one rotation role per (x, y) cell of the 5x5 grid.")
    for pos in range(25):
        lines.append(_basis_decl(f"p_{pos:02d}"))
    lines.append("")
    lines.append("// Fillers: LIT marker for a lit pixel, UNLIT for an unlit pixel.")
    lines.append(_basis_decl("LIT"))
    lines.append(_basis_decl("UNLIT"))
    lines.append("")
    lines.append("// 36 per-character basis vectors -- not strictly needed for glyph lookup")
    lines.append("// (we select glyphs by char_code via defuzzified select), but kept here as")
    lines.append("// codebook entries the host can build a char-string from if needed downstream.")
    for c in CHARS_ORDER:
        suffix = c if c.isalpha() else f"d{c}"
        lines.append(_basis_decl(f"c_{suffix}"))
    return "\n".join(lines)


def gen_glyph_bundles() -> str:
    """36 bundles, one per char: bundle(bind(p, LIT) for lit, bind(p, -LIT) for unlit).

    ANTIPODAL-FILLER encoding (third try after planning/26's first two):
    every cell is bound, lit cells with +LIT, unlit cells with -LIT. The
    expected unbind result is +LIT-direction for lit cells, -LIT-direction
    for unlit cells. Cosine to LIT is ~+1 for lit, ~-1 for unlit — a much
    wider gap than the sparse-only variant's `~+1 vs ~0`.

    Why this should beat sparse-only-LIT in low-dim noise:
    - In sparse-only, the bundle crosstalk for an unlit cell sums over all
      OTHER lit-cell bindings (one direction only). For a glyph with 14 lit
      cells, that's 14·(small crosstalk per term) of LIT-direction noise.
    - In antipodal, the crosstalk sums over ALL other 24 cells with
      MIXED signs (some +LIT, some -LIT). The signs partially cancel; the
      net crosstalk magnitude is sqrt(net imbalance) instead of (lit_count).
      For 'A' (14 lit, 11 unlit), the imbalance is 3 — much smaller than 14.

    Trade-off: every cell is bound, not just lit ones, so the bundle's
    capacity load is 25 per glyph instead of (lit_count, mean ~13.6). At
    a given runtime_dim the noise floor might be slightly higher; the
    measurement table in the commit message will tell.
    """
    lines: list[str] = []
    lines.append("// --- Per-character glyph bundles (rotation-bindings) ---")
    lines.append("// ANTIPODAL-FILLER encoding (2026-05-28): every cell is bound. Lit cells")
    lines.append("// bind to +LIT, unlit cells bind to -LIT. Unbinding by position returns")
    lines.append("// +LIT-direction for lit, -LIT-direction for unlit. Cosine to LIT then")
    lines.append("// separates the classes around 0 (not around the threshold the sparse-only")
    lines.append("// variant needs). Crosstalk: with ~half +LIT and ~half -LIT bindings, the")
    lines.append("// other-bindings contribution partially cancels, vs sparse-only where it")
    lines.append("// only adds in the LIT direction.")
    for c in CHARS_ORDER:
        suffix = c if c.isalpha() else f"d{c}"
        bits = bits_for(c)  # 25 floats in row-major (y*5+x)
        lines.append("")
        if all(b < 0.5 for b in bits):
            lines.append(f"// '{c}' has zero lit cells — bundle is all -LIT bindings.")
        binds = []
        for pos in range(25):
            marker = "LIT" if bits[pos] > 0.5 else "-LIT"
            binds.append(f"    bind(p_{pos:02d}, {marker})")
        lines.append(f"vector glyph_{suffix} = bundle(")
        lines.append(",\n".join(binds))
        lines.append(");")
    return "\n".join(lines)


def gen_glyph_pixel_antipodal() -> str:
    """The runtime function: 36-way outer + 25-way pos + unbind + similarity."""
    lines: list[str] = []
    lines.append("function vector glyph_pixel_antipodal(number x, number y, number char_code) {")
    lines.append("    number pos = y * 5.0 + x;")
    lines.append("")
    lines.append("    // 36-way defuzzified outer select picks the right glyph bundle by char_code.")
    lines.append("    // Same softmax-saturation pattern as the existing font.su glyph_pixel:")
    lines.append("    // exp(-1000 * delta^2) underflows in float64, making the matching score's")
    lines.append("    // branch one-hot.")
    for c in CHARS_ORDER:
        suffix = c if c.isalpha() else f"d{c}"
        cp = ord(c)
        lines.append(
            f"    scalar sc_{suffix} = 0.0 - 1000.0 * (char_code - {float(cp):.1f})"
            f" * (char_code - {float(cp):.1f});"
        )
    lines.append("")
    score_list = ", ".join(
        f"sc_{c if c.isalpha() else f'd{c}'}" for c in CHARS_ORDER
    )
    glyph_list = ", ".join(
        f"glyph_{c if c.isalpha() else f'd{c}'}" for c in CHARS_ORDER
    )
    lines.append(f"    vector glyph = select([{score_list}], [{glyph_list}]);")
    lines.append("")
    lines.append("    // 25-way defuzzified select picks the matching position basis vector for pos.")
    for p in range(25):
        lines.append(
            f"    scalar sp_{p:02d} = 0.0 - 1000.0 * (pos - {float(p):.1f})"
            f" * (pos - {float(p):.1f});"
        )
    lines.append("")
    pos_scores = ", ".join(f"sp_{p:02d}" for p in range(25))
    pos_basis = ", ".join(f"p_{p:02d}" for p in range(25))
    lines.append(f"    vector pos_vec = select([{pos_scores}], [{pos_basis}]);")
    lines.append("")
    lines.append("    // Unbind position from glyph -> a noisy approximation of LIT or UNLIT.")
    lines.append("    // Similarity to LIT -> ~1 lit, ~0 unlit. Lifted to real-axis vector.")
    lines.append("    vector bit_vec = unbind(pos_vec, glyph);")
    lines.append("    return make_real(similarity(bit_vec, LIT));")
    lines.append("}")
    lines.append("")
    lines.append("function vector main() { return glyph_pixel_antipodal(2.0, 0.0, 65.0); }")
    return "\n".join(lines)


def generate() -> str:
    parts: list[str] = [_HEADER, ""]
    parts.append(gen_basis_block())
    parts.append("")
    parts.append(gen_glyph_bundles())
    parts.append("")
    parts.append(gen_glyph_pixel_antipodal())
    parts.append("")
    return "\n".join(parts)


def main() -> None:
    # Migrated to Sutra demos/font/ 2026-05-28 — generator lives next to
    # its output now, not in a separate tools/ dir.
    out = pathlib.Path(__file__).resolve().parent / "font_bound_antipodal.su"
    out.parent.mkdir(parents=True, exist_ok=True)
    src = generate()
    out.write_text(src, encoding="utf-8", newline="\n")
    n_lines = src.count("\n") + 1
    print(f"[gen-bound] wrote {out} ({n_lines} lines)")


if __name__ == "__main__":
    main()
