"""Generate apps/font/font.su from tools/font_data.py (Emma 2026-05-26).

The .su file is long but mechanical — 36 letter functions, each a 25-way
position select; plus an outer 36-way letter select. Hand-writing this is
both error-prone and obscures intent. Generate it from font_data.py instead,
so the font shape lives in one place (the data) and the substrate dispatch
shape lives in one place (this generator).

Re-run after editing tools/font_data.py:

    python tools/generate_font_su.py

The generator does not run on the substrate; it is build-time tooling that
emits .su source. The .su that gets shipped IS what the substrate executes.
"""
from __future__ import annotations

import pathlib
import sys

_HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))

from font_data import CHARS_ORDER, FONT_5x5, bits_for


_HEADER = """\
// font.su -- GENERATED by tools/generate_font_su.py from tools/font_data.py.
// DO NOT EDIT BY HAND -- regenerate via `python tools/generate_font_su.py`.
//
// Emma's text-input demo (2026-05-26, extended 2026-05-27): each tick shows
// a character as a 5x5 pixel glyph on the substrate. By default the char_code
// auto-advances through the 36-glyph cycle (A->Z->0->9->A); a keypress
// replaces the state (the typed code "takes the place"). Substrate
// computations:
//
//   step(prev_state, x, y, char_code)
//       Stateless per-cell substrate dispatch. `prev_state` is multiplied
//       by 0 (discarded) and the new glyph bit for cell (x, y) under
//       char_code is returned. The "recurrence" across renders lives in
//       the host's pixel array, NOT on the substrate — this function is
//       not a substrate-state RNN (CLAUDE.md "Subtler substrate breaches"
//       #2; finding planning/findings/2026-05-28-demos-font-substrate-audit.md).
//
//   cycle_step(typed_onehot, has_typed) -- substrate-state RNN (rewritten 2026-05-28)
//       The glyph cursor is a 36-dim ONE-HOT held in a `recurring vector`
//       slot that survives across ticks ON THE SUBSTRATE (non-halting-loop.md).
//       The advance is one matmul `next = P @ glyph` against the frozen
//       36x36 cyclic-permutation matrix P (shift-by-one, wraps
//       Z->0->...->9->A), built with the `matrix_literal` primitive. One-hot
//       in, one-hot out, no scalar char_code ever materializes. With
//       has_typed=1.0 a host-provided typed one-hot replaces the advance via
//       the substrate weighted sum `has_typed*typed_onehot +
//       (1-has_typed)*advanced`. This is a REAL substrate RNN: the recurring
//       slot is a vector that survives across calls without host real()
//       extraction (the prior host-state-shuttle shape is gone). The host
//       decodes the returned one-hot to a glyph for rendering only — a
//       monitoring boundary, like count.su decoding its count vector. Option
//       B of planning/findings/2026-05-28-cycle-step-rewrite-blocked.md.
//
//   glyph_pixel(x, y, char_code)
//       Returns 1.0 if pixel (x, y) is lit for the letter with this codepoint,
//       else 0.0. Decided ON THE SUBSTRATE: 36-way defuzzified `select` over
//       A-Z + 0-9, made one-hot by softmax saturation (scores
//       -1000*(char_code - target_code)^2 -> exp underflows to exact 0 in
//       float32 AND float64, so the selected branch passes through and the
//       others are zeroed by exact-zero weights -- the same one-hot trick
//       apps/calc/switch.su uses for operator dispatch).
//
//   bit_<C>(pos) (helpers, one per of the 36 chars)
//       The lit/unlit bit for character <C> at flat position pos = y*5 + x
//       (pos in 0..24). Same defuzzified-select pattern, 25-way over pos.
//
// Together: each tick -> cycle_step(typed_onehot, has_typed) advances the
//                    recurring one-hot glyph cursor on the substrate; the host
//                    decodes it to a char_code (argmax, monitoring boundary)
//                 -> for each of 25 cells, glyph_pixel(x, y, code) selects
//                    a bit from the 36-way outer + 25-way inner switches.
// No host font table on the runtime path; both the cycle advance and the
// lit/unlit decision are the substrate's. Host stays I/O: tick the clock,
// read keypresses, paint pixels.
"""


def gen_bit_function(char: str) -> str:
    """One ``bit_<C>(number pos)`` returning the lit/unlit bit for char at pos."""
    bits = bits_for(char)
    lines: list[str] = []
    lines.append(f"function vector bit_{char}(number pos) {{")
    for p in range(25):
        lines.append(
            f"    number s{p:02d} = 0.0 - 1000.0 * (pos - {float(p):.1f}) * (pos - {float(p):.1f});"
        )
    scores = ", ".join(f"s{p:02d}" for p in range(25))
    vals = ", ".join(f"make_real({bits[p]:.1f})" for p in range(25))
    lines.append(f"    return select([{scores}], [{vals}]);")
    lines.append("}")
    return "\n".join(lines)


def gen_glyph_pixel() -> str:
    """36-way defuzzified select over char_code -> the per-letter bit at (x, y)."""
    lines: list[str] = []
    lines.append("function vector glyph_pixel(number x, number y, number char_code) {")
    lines.append("    number pos = y * 5.0 + x;")
    lines.append("")
    lines.append("    // Per-letter bit at this position. Each `bit_<C>(pos)` is a 25-way")
    lines.append("    // defuzzified select over the 25 grid positions of letter <C>.")
    for c in CHARS_ORDER:
        # Use a safe identifier: digits get prefixed with `d`.
        suffix = c if c.isalpha() else f"d{c}"
        lines.append(f"    vector b_{suffix} = bit_{c}(pos);")
    lines.append("")
    lines.append("    // Score char_code against each letter's codepoint. The softmax-")
    lines.append("    // saturation constant (1000) clears float64 underflow (~745), so")
    lines.append("    // exp(-1000) is exactly 0 and select is a true one-hot.")
    for c in CHARS_ORDER:
        suffix = c if c.isalpha() else f"d{c}"
        cp = ord(c)
        lines.append(
            f"    number s_{suffix} = 0.0 - 1000.0 * (char_code - {float(cp):.1f}) "
            f"* (char_code - {float(cp):.1f});"
        )
    lines.append("")
    scores = ", ".join(
        f"s_{c if c.isalpha() else f'd{c}'}" for c in CHARS_ORDER
    )
    branches = ", ".join(
        f"b_{c if c.isalpha() else f'd{c}'}" for c in CHARS_ORDER
    )
    lines.append(f"    return select([{scores}], [{branches}]);")
    lines.append("}")
    return "\n".join(lines)


def gen_step() -> str:
    """Stateless per-cell substrate dispatch: ``state = prev*0 + glyph_pixel(...)``.

    Per CLAUDE.md "Subtler substrate breaches" #2, this is NOT a substrate-
    state RNN — `prev_state` is multiplied by 0 (discarded) so the function
    is stateless per-cell. The pixel-field "recurrence" across renders
    lives in the host's pixel array, not on the substrate. Finding:
    planning/findings/2026-05-28-demos-font-substrate-audit.md.
    """
    return """\
function vector step(vector prev_state, number x, number y, number char_code) {
    // Stateless per-cell substrate dispatch. The prev_state input is
    // multiplied by 0 (discarded) and the new glyph bit for cell (x, y)
    // under char_code is returned. The "recurrence" across renders lives
    // in the host's pixel array, not on the substrate — this is
    // host-state-shuttle, not a substrate RNN (CLAUDE.md "Subtler
    // substrate breaches" #2; finding planning/findings/2026-05-28-demos-
    // font-substrate-audit.md). Both summands are real-axis vectors, so
    // the sum is real-axis too (no make_real needed).
    vector zeroed = prev_state * 0.0;
    vector new_pix = glyph_pixel(x, y, char_code);
    return zeroed + new_pix;
}
"""


def gen_cycle_step() -> str:
    """Emma's recurrent step on the glyph cycle — a real substrate-state RNN
    (rewritten 2026-05-28, Option B of the cycle-step-rewrite-blocked finding).

    The recurring state is a 36-dim ONE-HOT over the glyph cycle
    (A->B->...->Z->0->...->9->A), held as a ``recurring vector`` slot that
    survives across ticks ON THE SUBSTRATE (per non-halting-loop.md). It is
    NOT a scalar char_code shuttled through the host via ``real()`` between
    ticks — that was the prior host-state-shuttle shape and the source of the
    blocker (scalar scoring needs a source-level ``real()`` Sutra doesn't have).

    The advance is a single matmul: ``next = P @ glyph`` where ``P`` is the
    frozen 36x36 cyclic-permutation matrix (shift-by-one, wraps Z->0->...->9->A),
    built with the ``matrix_literal`` source-level primitive (shipped
    2026-05-28). One-hot in, one-hot out, no scalar ever touched. With
    ``has_typed=1.0`` the substrate weighted sum lets a host-provided typed
    one-hot take the place of the advance — same gate pattern as before, on
    one-hot vectors instead of ``make_real(code)``. The host decodes the
    returned one-hot to a glyph for rendering — a monitoring boundary, exactly
    like count.su decoding its count vector to position the glow; the
    recurrence itself never leaves the substrate.

    Note: the state/advance are 36-dim problem-sized tensors, independent of
    runtime_dim (no basis_vector calls), so the dim-audit rule is satisfied
    at the smallest runtime_dim.
    """
    cycle = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    n = len(cycle)  # 36

    def row(active_col: int) -> str:
        vals = ", ".join("1.0" if k == active_col else "0.0" for k in range(n))
        return f"vector_literal({vals})"

    lines: list[str] = []
    lines.append("function vector cycle_step(vector typed_onehot, number has_typed) {")
    lines.append("    // Substrate-state RNN over the 36-glyph cycle. The recurring `glyph`")
    lines.append("    // slot is a 36-dim one-hot living on the substrate across ticks; the")
    lines.append("    // advance is one matmul against the frozen cyclic-permutation matrix P.")
    lines.append("")
    # Initial one-hot: glyph 'A' = cycle index 0.
    lines.append("    // First-tick state: one-hot for 'A' (cycle index 0).")
    lines.append(f"    recurring vector glyph = {row(0)};")
    lines.append("")
    # Permutation P: (P @ e_i) = e_{(i+1)%n}, so row j has its 1 at column (j-1)%n.
    lines.append("    // Cyclic-shift permutation: (P @ e_i) = e_{(i+1) mod 36}. Row j has")
    lines.append("    // its single 1 at column (j-1) mod 36, so a one-hot advances by one")
    lines.append("    // and wraps Z(25)->0(26), 9(35)->A(0).")
    lines.append("    matrix P = matrix_literal(")
    row_lines = [f"        {row((j - 1) % n)}" for j in range(n)]
    lines.append(",\n".join(row_lines))
    lines.append("    );")
    lines.append("")
    lines.append("    vector advanced = Tensor.MatrixMul(P, glyph);")
    lines.append("")
    lines.append("    // Override: has_typed=1.0 -> the host-provided typed one-hot replaces")
    lines.append("    // the advance; has_typed=0.0 -> the advance passes through. Substrate")
    lines.append("    // weighted sum, not a host if -- both branches computed, the gate picks.")
    lines.append("    vector next = advanced * (1.0 - has_typed) + typed_onehot * has_typed;")
    lines.append("")
    lines.append("    recur(next);")
    lines.append("    return(next);")
    lines.append("}")
    return "\n".join(lines)


def generate() -> str:
    """Emit the full .su source as a string."""
    parts: list[str] = [_HEADER, ""]
    parts.append(gen_step())
    parts.append("")
    parts.append(gen_cycle_step())
    parts.append("")
    parts.append(gen_glyph_pixel())
    parts.append("")
    parts.append("// ============================================================")
    parts.append("// Per-letter bit lookups (25-way position selects), one per char.")
    parts.append("// ============================================================")
    for c in CHARS_ORDER:
        parts.append("")
        parts.append(gen_bit_function(c))
    parts.append("")
    return "\n".join(parts)


def main() -> None:
    # Migrated to Sutra demos/font/ 2026-05-28 — generator lives next to
    # its output now, not in a separate tools/ dir.
    out = pathlib.Path(__file__).resolve().parent / "font.su"
    out.parent.mkdir(parents=True, exist_ok=True)
    src = generate()
    out.write_text(src, encoding="utf-8", newline="\n")
    n_lines = src.count("\n") + 1
    print(f"[gen] wrote {out} ({n_lines} lines, "
          f"{len(FONT_5x5)} glyphs)")


if __name__ == "__main__":
    main()
