"""AST -> pure-numpy Python source translator.

This is the demo-path backend. It emits self-contained Python modules
that depend only on numpy — no fly-brain imports, no spiking simulator,
no learned MBON readouts. VSA ops run as plain matrix operations on CPU.

The fly-brain backend (`codegen_flybrain.py`) stays for fly-brain-only
work. The demo path (what the paper points at, what fresh clones run)
goes through this file.

Design is a thin subclass of `FlyBrainCodegen`: the translator logic for
expressions, statements, loops, declarations is identical — only the
prelude changes. `snap` is not supported here (the demo substrate has no
cleanup circuit; programs that need `snap` should target the fly-brain
backend).
"""

from __future__ import annotations

from typing import List

from . import ast_nodes as ast
from .codegen_flybrain import FlyBrainCodegen, CodegenNotSupported


class NumpyCodegen(FlyBrainCodegen):
    """Emits a self-contained numpy-only module.

    Overrides the prelude and rejects `snap()` at codegen time. Everything
    else (function bodies, bind/bundle/unbind/similarity/argmax_cosine,
    map lookup, loop unrolling) is inherited unchanged.
    """

    # Frozen-LLM substrate. The embed() method tries Ollama with this
    # model first; if Ollama isn't available, it falls back to seeded
    # random vectors so demos still run on a fresh clone with no extra
    # services. Default model: nomic-embed-text (768-dim). Avoid
    # mxbai-embed-large per CLAUDE.md — it has a documented attention-
    # sink defect on diacritics and is treated as known-broken baseline.
    DEFAULT_LLM_MODEL = "nomic-embed-text"
    DEFAULT_LLM_DIM = 768

    def __init__(self, *, runtime_dim: int | None = None,
                 runtime_seed: int = 42,
                 llm_model: str | None = None) -> None:
        self._llm_model = llm_model if llm_model is not None else self.DEFAULT_LLM_MODEL
        # If using LLM default, dim is the LLM's; otherwise allow override.
        if runtime_dim is None:
            runtime_dim = self.DEFAULT_LLM_DIM
        super().__init__(
            runtime_dim=runtime_dim,
            runtime_seed=runtime_seed,
            runtime_n_kc=0,
            runtime_use_hemibrain=False,
        )

    # Ops not supported by the pure-numpy substrate. `snap` requires a
    # cleanup circuit (MB spiking model or equivalent); rotation-based
    # loop primitives need the same. Programs that use these should
    # target `codegen_flybrain` instead.
    _UNSUPPORTED_BUILTINS = frozenset({
        "snap",
        "make_rotation",
        "compile_prototypes",
        "geometric_loop",
    })

    def _translate_eigenrotation_loop(self, stmt):
        """Eigenrotation on the numpy substrate.

        Differences from fly-brain:
        - Haar-random orthogonal matrix (fly-brain's uniform-angle
          Givens gives a tight periodic orbit that never explores).
        - Threshold is parsed from the condition (the numeric literal
          side of `similarity(state, target) < T`). Fly-brain uses a
          fixed 0.3 because matching is KC-pattern Jaccard; numpy
          matches on raw cosine, which has a very different scale.
        """
        from . import ast_nodes as ast
        lid = self._next_loop_id()
        state_var = self._extract_loop_state_var(stmt.body)
        target_expr = self._extract_loop_target(stmt.condition)

        threshold = 0.9
        cond = stmt.condition
        if isinstance(cond, ast.BinaryOp):
            for side in (cond.left, cond.right):
                if isinstance(side, ast.FloatLiteral):
                    threshold = side.value
                elif isinstance(side, ast.IntLiteral):
                    threshold = float(side.value)

        self._emit(f"{lid}_R = _VSA.make_random_rotation("
                   f"angle=1.0, n_planes=_VSA.dim // 2, seed=_VSA.seed)")
        self._emit(f"{lid}_target = {target_expr}")
        self._emit(f"{lid}_protos = _VSA.compile_prototypes("
                   f"{{\"target\": {lid}_target}})")
        self._emit(f"{lid}_name, {state_var}, {lid}_iters = _VSA.loop(")
        self._indent += 1
        self._emit(f"{state_var}, {lid}_R, {lid}_protos,")
        self._emit(f"target_name=\"target\", threshold={threshold}, max_iters=500)")
        self._indent -= 1

    def _translate_call(self, call: ast.Call) -> str:
        callee = call.callee
        if isinstance(callee, ast.Identifier):
            if callee.name in self._UNSUPPORTED_BUILTINS:
                raise CodegenNotSupported(
                    call,
                    f"`{callee.name}` is not supported on the pure-numpy "
                    f"substrate; use the fly-brain backend if you need it",
                )
        return super()._translate_call(call)

    def _emit_prelude(self) -> None:
        self._emit('"""Generated by sutra_compiler.codegen_numpy. Do not edit by hand."""')
        self._emit("from __future__ import annotations")
        self._emit()
        self._emit("import numpy as _np")
        self._emit()
        self._emit()
        self._emit("class _NumpyVSA:")
        self._indent += 1
        self._emit('"""Frozen-LLM-backed VSA runtime. Sign-flip binding, normalized bundle."""')
        self._emit()
        self._emit("def __init__(self, dim, seed, llm_model):")
        self._indent += 1
        self._emit("self.dim = dim")
        self._emit("self.seed = seed")
        self._emit("self.llm_model = llm_model")
        self._emit("self._codebook = {}")
        self._emit("self._llm_ok = None  # tri-state: None=untried, True=working, False=fell back")
        self._indent -= 1
        self._emit()
        self._emit("def _ollama_embed(self, name):")
        self._indent += 1
        self._emit('"""Try the frozen LLM via Ollama. Returns numpy vec or None on failure."""')
        self._emit("try:")
        self._indent += 1
        self._emit("import ollama")
        self._emit("r = ollama.embed(model=self.llm_model, input=name)")
        self._emit("v = _np.array(r['embeddings'][0], dtype=_np.float64)")
        self._emit("# Mean-center: sign-flip binding assumes zero-mean vectors.")
        self._emit("# Raw LLM embeddings cluster in a cone (all-positive-ish), which")
        self._emit("# collapses sign(role) to a near-constant pattern and destroys")
        self._emit("# role-filler separation. Centering restores the algebra.")
        self._emit("v = v - _np.mean(v)")
        self._emit("n = _np.linalg.norm(v)")
        self._emit("if n > 0: v = v / n")
        self._emit("# Truncate or pad to self.dim if the LLM dim differs.")
        self._emit("if v.shape[0] != self.dim:")
        self._indent += 1
        self._emit("if v.shape[0] > self.dim:")
        self._indent += 1
        self._emit("v = v[:self.dim]")
        self._indent -= 1
        self._emit("else:")
        self._indent += 1
        self._emit("v = _np.concatenate([v, _np.zeros(self.dim - v.shape[0])])")
        self._indent -= 1
        self._emit("n = _np.linalg.norm(v)")
        self._emit("if n > 0: v = v / n")
        self._indent -= 1
        self._emit("return v")
        self._indent -= 1
        self._emit("except Exception:")
        self._indent += 1
        self._emit("return None")
        self._indent -= 1
        self._indent -= 1
        self._emit()
        self._emit("def _seeded_embed(self, name):")
        self._indent += 1
        self._emit('"""Fallback when Ollama is unavailable: deterministic seeded RNG."""')
        self._emit("h = hash(name) & 0x7fffffff")
        self._emit("rng = _np.random.RandomState((self.seed ^ h) & 0x7fffffff)")
        self._emit("v = rng.randn(self.dim)")
        self._emit("return v / _np.linalg.norm(v)")
        self._indent -= 1
        self._emit()
        self._emit("def embed(self, name):")
        self._indent += 1
        self._emit("if name not in self._codebook:")
        self._indent += 1
        self._emit("# Try LLM once; if it works, keep using it. If it fails, stick with RNG.")
        self._emit("if self._llm_ok is None:")
        self._indent += 1
        self._emit("v = self._ollama_embed(name)")
        self._emit("self._llm_ok = v is not None")
        self._emit("if not self._llm_ok:")
        self._indent += 1
        self._emit("import sys")
        self._emit("print(f'[sutra] Ollama unavailable for model {self.llm_model!r}; '")
        self._emit("      f'falling back to seeded random vectors.', file=sys.stderr)")
        self._emit("v = self._seeded_embed(name)")
        self._indent -= 1
        self._indent -= 1
        self._emit("elif self._llm_ok:")
        self._indent += 1
        self._emit("v = self._ollama_embed(name)")
        self._emit("if v is None: v = self._seeded_embed(name)")
        self._indent -= 1
        self._emit("else:")
        self._indent += 1
        self._emit("v = self._seeded_embed(name)")
        self._indent -= 1
        self._emit("self._codebook[name] = v")
        self._indent -= 1
        self._emit("return self._codebook[name].copy()")
        self._indent -= 1
        self._emit()
        self._emit("def bind(self, a, b):")
        self._indent += 1
        self._emit("# Sign-flip binding (spec: permute -> sign_flip).")
        self._emit("return a * _np.sign(b)")
        self._indent -= 1
        self._emit()
        self._emit("def unbind(self, role, bound):")
        self._indent += 1
        self._emit("# Sign-flip is self-inverse: unbind(role, bind(role, x)) ~= x.")
        self._emit("return bound * _np.sign(role)")
        self._indent -= 1
        self._emit()
        self._emit("def bundle(self, *vectors):")
        self._indent += 1
        self._emit("s = _np.sum(vectors, axis=0)")
        self._emit("n = _np.linalg.norm(s)")
        self._emit("return s / n if n > 0 else s")
        self._indent -= 1
        self._emit()
        self._emit("def similarity(self, a, b):")
        self._indent += 1
        self._emit("na = _np.linalg.norm(a)")
        self._emit("nb = _np.linalg.norm(b)")
        self._emit("if na == 0 or nb == 0:")
        self._indent += 1
        self._emit("return 0.0")
        self._indent -= 1
        self._emit("return float(_np.dot(a, b) / (na * nb))")
        self._indent -= 1
        self._emit()
        self._emit("def make_random_rotation(self, angle, n_planes=1, seed=None):")
        self._indent += 1
        self._emit('"""Haar-random rotation, scaled so its largest eigenphase ~= angle.')
        self._emit('')
        self._emit('Uniform-angle Givens composition makes every plane orbit at the')
        self._emit('same frequency, so any trajectory is near-periodic and never')
        self._emit('explores the hypersphere. A Haar-random orthogonal matrix has a')
        self._emit('spectrum of eigenphases and produces quasi-periodic trajectories')
        self._emit('that actually sample the sphere. `angle` and `n_planes` are kept')
        self._emit('in the signature for API compatibility with the fly-brain VSA.')
        self._emit('"""')
        self._emit("rng = _np.random.RandomState(seed if seed is not None else self.seed)")
        self._emit("A = rng.randn(self.dim, self.dim)")
        self._emit("Q, _ = _np.linalg.qr(A)")
        self._emit("# Fractional matrix power via eigendecomposition so the caller")
        self._emit("# can still dial rotation magnitude via `angle`. Q^(angle/pi)")
        self._emit("# interpolates between identity (angle=0) and full Q (angle=pi).")
        self._emit("w, V = _np.linalg.eig(Q)")
        self._emit("phases = _np.angle(w) * (angle / _np.pi)")
        self._emit("R = (V * _np.exp(1j * phases)) @ _np.linalg.inv(V)")
        self._emit("return _np.real(R)")
        self._indent -= 1
        self._emit()
        self._emit("def compile_prototypes(self, prototype_vectors, frame_seed=None):")
        self._indent += 1
        self._emit('"""Pass-through on the numpy substrate: no KC sparsification here."""')
        self._emit("return dict(prototype_vectors)")
        self._indent -= 1
        self._emit()
        self._emit("def loop(self, initial_state, rotation, compiled_prototypes,")
        self._indent += 1
        self._emit("target_name=None, threshold=0.5, max_iters=50, frame_seed=None):")
        self._emit('"""Eigenrotation: iterate state <- R @ state until match."""')
        self._emit("state = initial_state.copy()")
        self._emit("for iters in range(1, max_iters + 1):")
        self._indent += 1
        self._emit("state = rotation @ state")
        self._emit("n = _np.linalg.norm(state)")
        self._emit("if n > 0: state = state / n")
        self._emit("best_name, best_score = None, -1.0")
        self._emit("for nm, proto in compiled_prototypes.items():")
        self._indent += 1
        self._emit("s = self.similarity(state, proto)")
        self._emit("if s > best_score:")
        self._indent += 1
        self._emit("best_score = s; best_name = nm")
        self._indent -= 1
        self._indent -= 1
        self._emit("if target_name is not None and best_name == target_name and best_score >= threshold:")
        self._indent += 1
        self._emit("return best_name, state, iters")
        self._indent -= 1
        self._emit("if target_name is None and best_score >= threshold:")
        self._indent += 1
        self._emit("return best_name, state, iters")
        self._indent -= 1
        self._indent -= 1
        self._emit("return best_name, state, max_iters")
        self._indent -= 1
        self._indent -= 1
        self._emit()
        self._emit()
        self._emit(
            f"_VSA = _NumpyVSA(dim={self.runtime_dim}, seed={self.runtime_seed}, "
            f"llm_model={self._llm_model!r})"
        )
        self._emit()
        self._emit()
        self._emit("def _argmax_cosine(query, candidates):")
        self._indent += 1
        self._emit('"""Candidate with the largest cosine similarity to query."""')
        self._emit("best = None")
        self._emit("best_score = float('-inf')")
        self._emit("for c in candidates:")
        self._indent += 1
        self._emit("s = _VSA.similarity(query, c)")
        self._emit("if s > best_score:")
        self._indent += 1
        self._emit("best_score = s")
        self._emit("best = c")
        self._indent -= 1
        self._indent -= 1
        self._emit("return best")
        self._indent -= 1
        self._emit()
        self._emit()
        self._emit_select_helper()
        self._emit()
        self._emit("def _vector_map_lookup(pairs, key):")
        self._indent += 1
        self._emit('"""Identity-first lookup for vector-keyed maps, cosine fallback."""')
        self._emit("for k, v in pairs:")
        self._indent += 1
        self._emit("if k is key:")
        self._indent += 1
        self._emit("return v")
        self._indent -= 1
        self._indent -= 1
        self._emit("best_v = None")
        self._emit("best_score = float('-inf')")
        self._emit("for k, v in pairs:")
        self._indent += 1
        self._emit("s = _VSA.similarity(key, k)")
        self._emit("if s > best_score:")
        self._indent += 1
        self._emit("best_score = s")
        self._emit("best_v = v")
        self._indent -= 1
        self._indent -= 1
        self._emit("return best_v")
        self._indent -= 1


def translate_module(module: ast.Module, **kwargs) -> str:
    """Translate a parsed Sutra module to self-contained numpy Python."""
    return NumpyCodegen(**kwargs).translate(module)
