"""AST → FlyBrainVSA Python source translator.

The fly-brain backend — emits code that targets the `FlyBrainVSA`
runtime in `fly-brain/vsa_operations.py`, with PN→KC connectivity
pinned through `_FixedFrameFlyBrainVSA.snap()` so every `snap()`
call uses the same biologically-seeded mushroom-body projection.

This module is intentionally thin: `FlyBrainCodegen` inherits
nearly all of its behavior (AST walk, builtin table, loop
translators) from `BaseCodegen` in `codegen_base.py`. The only
fly-brain-specific piece here is `_emit_prelude` — the runtime
imports, the `_FixedFrameFlyBrainVSA` subclass emission, the
`_VSA` instantiation, and the helper functions `_argmax_cosine` /
`_vector_map_lookup` that the translator's generated code calls
into.

Unsupported constructs (e.g. EmbedExpr without a frozen-LLM
runtime, DefuzzyExpr before the truth-axis runtime reaches this
backend) raise `CodegenNotSupported` with a source span, routed
through the base class's backend hooks.
"""

from __future__ import annotations

from . import ast_nodes as ast
from .codegen_base import BaseCodegen, CodegenNotSupported


class FlyBrainCodegen(BaseCodegen):
    """Emits a fly-brain-targeting Python module.

    Overrides only `_emit_prelude`; everything else (AST walk,
    builtin lowering, loop translators, literal hooks) is inherited.
    """

    def _emit_prelude(self) -> None:
        self._emit('"""Generated by sutra_compiler.codegen_flybrain. Do not edit by hand."""')
        self._emit("from __future__ import annotations")
        self._emit()
        self._emit("import numpy as _np")
        self._emit()
        self._emit("from vsa_operations import FlyBrainVSA")
        self._emit("from spike_vsa_bridge import SpikeVSABridge")
        self._emit()
        self._emit()
        self._emit("class _FixedFrameFlyBrainVSA(FlyBrainVSA):")
        self._indent += 1
        self._emit('"""Pins the PN->KC connectivity seed across all snap() calls."""')
        self._emit()
        self._emit("def snap(self, vector):")
        self._indent += 1
        if self.runtime_use_hemibrain:
            self._emit("bridge_kwargs = dict(use_hemibrain=True)")
        else:
            self._emit("bridge_kwargs = dict(n_kc=self.n_kc)")
        self._emit("bridge = SpikeVSABridge(")
        self._indent += 1
        self._emit("dim=self.dim, seed=self.seed, **bridge_kwargs,")
        self._indent -= 1
        self._emit(")")
        self._emit("# Fit the biologically-plausible learned MBON readout.")
        self._emit("# Class-level cache in SpikeVSABridge makes this a")
        self._emit("# trivial hit on every call after the first.")
        n_samples = 80 if self.runtime_use_hemibrain else 20
        self._emit(f"bridge.fit_learned_readout(n_samples={n_samples})")
        self._emit("decoded, _ = bridge.round_trip(vector, self.snap_duration_ms)")
        self._emit("return decoded")
        self._indent -= 1
        self._indent -= 1
        self._emit()
        self._emit()
        if self.runtime_use_hemibrain:
            self._emit(
                f"_VSA = _FixedFrameFlyBrainVSA("
                f"seed={self.runtime_seed}, use_hemibrain=True)"
            )
        else:
            self._emit(
                f"_VSA = _FixedFrameFlyBrainVSA(dim={self.runtime_dim}, "
                f"n_kc={self.runtime_n_kc}, seed={self.runtime_seed})"
            )
        self._emit()
        self._emit()
        self._emit("def _argmax_cosine(query, candidates):")
        self._indent += 1
        self._emit('"""Candidate with the largest cosine similarity to query.')
        self._emit('')
        self._emit("Vectorized: stacks `candidates` into a (N, d) matrix and")
        self._emit("computes all N cosines in a single matmul. Equivalent to the")
        self._emit("old Python for-loop over _VSA.similarity, but ~Nx faster on")
        self._emit("CPU and the shape the PyTorch/GPU backend will reuse without")
        self._emit("any further rewriting. N small-kernel launches becomes 1 big one.")
        self._emit('"""')
        self._emit("if not candidates:")
        self._indent += 1
        self._emit("return None")
        self._indent -= 1
        self._emit("M = _np.stack([_np.asarray(c, dtype=_np.float64) for c in candidates])")
        self._emit("q = _np.asarray(query, dtype=_np.float64)")
        self._emit("row_norms = _np.linalg.norm(M, axis=1)")
        self._emit("q_norm = _np.linalg.norm(q)")
        self._emit("if q_norm == 0:")
        self._indent += 1
        self._emit("return candidates[0]")
        self._indent -= 1
        self._emit("# Guard zero-norm rows so division doesn't emit a warning and")
        self._emit("# the cosine for a zero candidate is 0, matching _VSA.similarity.")
        self._emit("safe_rn = _np.where(row_norms > 0, row_norms, 1.0)")
        self._emit("scores = (M @ q) / (safe_rn * q_norm)")
        self._emit("scores = _np.where(row_norms > 0, scores, -_np.inf)")
        self._emit("return candidates[int(_np.argmax(scores))]")
        self._indent -= 1
        self._emit()
        self._emit()
        self._emit_select_helper()
        self._emit()
        self._emit("def _vector_map_lookup(pairs, key):")
        self._indent += 1
        self._emit('"""Identity-first lookup for vector-keyed maps, cosine fallback.')
        self._emit('')
        self._emit("Vectorized fallback: the cosine-nearest path stacks the key")
        self._emit("vectors into one matrix and matmuls, matching the shape")
        self._emit("_argmax_cosine uses. Identity-hit short-circuits before any")
        self._emit("matmul, which is the common case for literal vector keys.")
        self._emit('"""')
        self._emit("for k, v in pairs:")
        self._indent += 1
        self._emit("if k is key:")
        self._indent += 1
        self._emit("return v")
        self._indent -= 1
        self._indent -= 1
        self._emit("if not pairs:")
        self._indent += 1
        self._emit("return None")
        self._indent -= 1
        self._emit("keys = _np.stack([_np.asarray(k, dtype=_np.float64) for k, _ in pairs])")
        self._emit("q = _np.asarray(key, dtype=_np.float64)")
        self._emit("row_norms = _np.linalg.norm(keys, axis=1)")
        self._emit("q_norm = _np.linalg.norm(q)")
        self._emit("if q_norm == 0:")
        self._indent += 1
        self._emit("return pairs[0][1]")
        self._indent -= 1
        self._emit("safe_rn = _np.where(row_norms > 0, row_norms, 1.0)")
        self._emit("scores = (keys @ q) / (safe_rn * q_norm)")
        self._emit("scores = _np.where(row_norms > 0, scores, -_np.inf)")
        self._emit("return pairs[int(_np.argmax(scores))][1]")
        self._indent -= 1



# ============================================================
# Module-level helper
# ============================================================


def translate_module(
    module: ast.Module,
    *,
    runtime_dim: int = 50,
    runtime_seed: int = 42,
    runtime_n_kc: int = 2000,
    runtime_use_hemibrain: bool = False,
) -> str:
    """Translate a parsed Sutra `Module` to fly-brain-targeting Python.

    Convenience wrapper around `FlyBrainCodegen`. Raises
    `CodegenNotSupported` with a source span for any unsupported node.
    """
    gen = FlyBrainCodegen(
        runtime_dim=runtime_dim,
        runtime_seed=runtime_seed,
        runtime_n_kc=runtime_n_kc,
        runtime_use_hemibrain=runtime_use_hemibrain,
    )
    return gen.translate(module)
