"""AST -> PyTorch/CUDA Python source translator.

The GPU path. Emits self-contained Python modules that depend only on
torch (numpy is still imported for a single bridge at ingestion time —
Ollama hands us lists of floats and we construct tensors from them).
Ops run as torch tensors; when CUDA is available the module picks
`cuda` as its device automatically, falling back to `cpu` otherwise.

Relationship to the CPU codegen:

    BaseCodegen                     ← backend-agnostic AST walker
        └── Codegen                 ← canonical CPU path (numpy ndarrays)
                └── PyTorchCodegen  ← GPU path (torch tensors)

PyTorchCodegen inherits the translator from `Codegen` (same AST walk,
same bundle-of-binds fusion, same vector-accessor lowering, same
extended-state-vector layout) and only overrides the prelude so the
emitted runtime class is `_TorchVSA` operating on tensors. The fused
shapes that the simplifier and codegen produce (stacked Q matmul via
einsum, stacked candidate matmul for argmax_cosine) collapse O(N)
small kernel launches into O(1) large ones on GPU — which is the
reason this backend exists.

Extended state vector and canonical axis allocation are preserved
exactly: every tensor is `[semantic (semantic_dim) | synthetic
(synthetic_dim)]`, bind rotation is block-diagonal with identity on
the synthetic block, `synthetic[0..2]` are the canonical real/imag/
truth axes per the 2026-04-23 design.
"""

from __future__ import annotations

from . import ast_nodes as ast
from .codegen_base import CodegenNotSupported
from .codegen import Codegen


class PyTorchCodegen(Codegen):
    """Emits a self-contained torch module.

    Inherits the entire translator from `Codegen` and only overrides the
    prelude. Vector accessor methods (`.component()`, `.real()`, etc.)
    still route through `_VSA.*` calls — the runtime method names match
    the CPU codegen so the translator needs no divergence.

    Bool literal lowering is inherited from `Codegen` (true/false →
    make_truth(±1)); logical ops (`!`, `&&`, `||`) likewise inherit the
    base override and resolve against the torch runtime's make_truth /
    _as_truth_vector.
    """

    def _emit_select_helper(self) -> None:
        """Torch-based softmax for the Sutra `select` primitive.

        Same numerical shape as the numpy version (subtract max for
        stability, exp, normalize, weighted sum), all on tensors so the
        whole path stays on the chosen device.
        """
        self._emit("def _select_softmax(scores, options):")
        self._indent += 1
        self._emit('"""Softmax-weighted superposition of option vectors (torch)."""')
        self._emit("s = _torch.as_tensor(scores, dtype=_DTYPE, device=_DEVICE)")
        self._emit("s = s - _torch.amax(s)")
        self._emit("w = _torch.exp(s)")
        self._emit("w = w / _torch.sum(w)")
        self._emit("opts = _torch.stack([")
        self._indent += 1
        self._emit("_torch.as_tensor(o, dtype=_DTYPE, device=_DEVICE)")
        self._emit("for o in options")
        self._indent -= 1
        self._emit("])")
        self._emit("return (w[:, None] * opts).sum(dim=0)")
        self._indent -= 1

    def _translate_var_decl_zero_init(self, decl):  # pragma: no cover — helper
        # Not actually used by the parent directly; the parent inlines
        # the `_np.zeros(_VSA.dim)` string. We patch at translate time
        # by string replacement below.
        pass

    def translate(self, module: ast.Module) -> str:
        """Translate and then patch any `_np.zeros(_VSA.dim)` emissions.

        The parent class hard-codes `_np.zeros(_VSA.dim)` for
        uninitialized-vector declarations. The pytorch backend has no
        `_np` symbol in scope, so any such emission would crash at
        module init. We post-process the output to swap those specific
        string occurrences to the torch equivalent. Everything else is
        emitted directly as torch via `_emit_prelude`.
        """
        out = super().translate(module)
        out = out.replace(
            "_np.zeros(_VSA.dim)",
            "_torch.zeros(_VSA.dim, dtype=_DTYPE, device=_DEVICE)",
        )
        return out

    def _emit_prelude(self) -> None:
        self._emit('"""Generated by sutra_compiler.codegen_pytorch. Do not edit by hand."""')
        self._emit("from __future__ import annotations")
        self._emit()
        self._emit("import torch as _torch")
        self._emit()
        self._emit("# Pick device and dtype once at module import. CUDA is preferred")
        self._emit("# because the whole reason for this backend is to collapse the")
        self._emit("# fused bind / bundle / argmax_cosine shapes into single big")
        self._emit("# kernel launches on GPU. CPU fallback keeps the module usable")
        self._emit("# on machines without CUDA — the numerics are identical.")
        self._emit("_DEVICE = _torch.device('cuda' if _torch.cuda.is_available() else 'cpu')")
        self._emit("# float32 on GPU is the fast path; keep dtype consistent across")
        self._emit("# every tensor so einsum / matmul don't trigger implicit upcasts.")
        self._emit("_DTYPE = _torch.float32")
        self._emit()
        self._emit()
        self._emit("class _TorchVSA:")
        self._indent += 1
        self._emit('"""Torch-backed VSA runtime. Rotation binding, normalized bundle.')
        self._emit('')
        self._emit('State tensors carry the extended layout:')
        self._emit('`[semantic (semantic_dim) | synthetic (synthetic_dim)]`. The')
        self._emit('semantic block is filled by `embed()` from the frozen LLM; the')
        self._emit('synthetic block is reserved computational/symbolic space with')
        self._emit('canonical axes at synthetic[0..2] (real, imag, truth). See')
        self._emit('planning/findings/2026-04-21-extended-state-and-rotation-binding.md.')
        self._emit('')
        self._emit('Bind is role-seeded Haar-random orthogonal rotation applied to')
        self._emit('filler: bind(filler, role) = Q_role @ filler. The rotation is')
        self._emit('block-diagonal — Haar in the semantic block, identity in the')
        self._emit('synthetic block — so rotation acts only on semantic content and')
        self._emit('the synthetic block is preserved through bind/unbind.')
        self._emit('"""')
        self._emit()
        self._emit("# Canonical synthetic-axis allocation — real, imag, truth at")
        self._emit("# synthetic[0..2], char-flag at synthetic[3], loop-done at")
        self._emit("# synthetic[4]. Mirrored from the CPU runtime so the two agree")
        self._emit("# bit-for-bit on layout. AXIS_LOOP_DONE is the substrate-side")
        self._emit("# completion flag set by the RNN-style branchless loop.")
        self._emit("AXIS_REAL = 0")
        self._emit("AXIS_IMAG = 1")
        self._emit("AXIS_TRUTH = 2")
        self._emit("AXIS_CHAR_FLAG = 3")
        self._emit("AXIS_LOOP_DONE = 4")
        self._emit()
        self._emit("def __init__(self, semantic_dim, synthetic_dim, seed, llm_model):")
        self._indent += 1
        self._emit("self.semantic_dim = semantic_dim")
        self._emit("self.synthetic_dim = synthetic_dim")
        self._emit("self.dim = semantic_dim + synthetic_dim")
        self._emit("self.seed = seed")
        self._emit("self.llm_model = llm_model")
        self._emit("self.device = _DEVICE")
        self._emit("self.dtype = _DTYPE")
        self._emit("self._codebook = {}")
        self._emit("# Rotation matrix cache: role-hash -> tensor on self.device.")
        self._emit("# Generating a 768x768 Haar rotation is O(d^3) on CPU (seeded")
        self._emit("# via numpy for Haar-uniformity). Cached on the GPU after the")
        self._emit("# first draw so repeated bind/unbind with the same role is a")
        self._emit("# lookup + one matmul, no transfer.")
        self._emit("self._rot_cache = {}")
        self._emit("# On-disk embedding cache. Keyed by (model, dim) so switching")
        self._emit("# embedding model OR changing the extended-state dim invalidates")
        self._emit("# automatically (different filename). Torch cache uses .pt so")
        self._emit("# it doesn't collide with the numpy backend's .npz.")
        self._emit("import os as _os")
        self._emit("self._cache_dir = _os.path.join(")
        self._indent += 1
        self._emit("_os.environ.get('XDG_CACHE_HOME', _os.path.expanduser('~/.cache')),")
        self._emit("'sutra', 'embeddings')")
        self._indent -= 1
        self._emit("_os.makedirs(self._cache_dir, exist_ok=True)")
        self._emit("_safe_model = llm_model.replace('/', '_').replace(':', '_')")
        self._emit("self._cache_path = _os.path.join(")
        self._indent += 1
        self._emit("self._cache_dir, f'{_safe_model}-d{self.dim}.pt')")
        self._indent -= 1
        self._emit("self._load_disk_cache()")
        self._indent -= 1
        self._emit()
        self._emit("def _load_disk_cache(self):")
        self._indent += 1
        self._emit('"""Populate self._codebook from disk if the cache file exists.')
        self._emit('')
        self._emit("Tolerant of missing or corrupt files — a failed load just leaves")
        self._emit("the codebook empty and lets Ollama repopulate it.")
        self._emit('"""')
        self._emit("import os as _os")
        self._emit("if not _os.path.exists(self._cache_path):")
        self._indent += 1
        self._emit("return")
        self._indent -= 1
        self._emit("try:")
        self._indent += 1
        self._emit("data = _torch.load(self._cache_path, map_location=self.device, weights_only=True)")
        self._emit("for key, tensor in data.items():")
        self._indent += 1
        self._emit("self._codebook[key] = tensor.to(dtype=self.dtype)")
        self._indent -= 1
        self._indent -= 1
        self._emit("except Exception:")
        self._indent += 1
        self._emit("# Corrupt cache: ignore and let Ollama repopulate.")
        self._emit("self._codebook = {}")
        self._indent -= 1
        self._indent -= 1
        self._emit()
        self._emit("def _write_disk_cache(self):")
        self._indent += 1
        self._emit('"""Persist self._codebook to disk via tempfile + atomic rename.')
        self._emit('')
        self._emit("A partial write (crash, SIGKILL) leaves the old cache intact")
        self._emit("rather than corrupted.")
        self._emit('"""')
        self._emit("import os as _os, tempfile as _tempfile")
        self._emit("if not self._codebook:")
        self._indent += 1
        self._emit("return")
        self._indent -= 1
        self._emit("fd, tmp = _tempfile.mkstemp(")
        self._indent += 1
        self._emit("dir=self._cache_dir, prefix='.tmp-', suffix='.pt')")
        self._indent -= 1
        self._emit("_os.close(fd)")
        self._emit("try:")
        self._indent += 1
        self._emit("# Save tensors on CPU so the cache file is portable — the")
        self._emit("# next run can load on any device. Reload will move them.")
        self._emit("cpu_codebook = {k: v.detach().cpu() for k, v in self._codebook.items()}")
        self._emit("_torch.save(cpu_codebook, tmp)")
        self._emit("_os.replace(tmp, self._cache_path)")
        self._indent -= 1
        self._emit("except Exception:")
        self._indent += 1
        self._emit("try:")
        self._indent += 1
        self._emit("_os.unlink(tmp)")
        self._indent -= 1
        self._emit("except OSError:")
        self._indent += 1
        self._emit("pass")
        self._indent -= 1
        self._indent -= 1
        self._indent -= 1
        self._emit()
        self._emit("def embed(self, name):")
        self._indent += 1
        self._emit('"""Frozen-LLM embedding via Ollama. Returns a tensor on self.device.')
        self._emit('')
        self._emit("Extended-state layout: `[semantic (semantic_dim) | zeros (synthetic_dim)]`.")
        self._emit("No random fallback — if Ollama is unavailable this raises.")
        self._emit('"""')
        self._emit("if name not in self._codebook:")
        self._indent += 1
        self._emit("import ollama")
        self._emit("r = ollama.embed(model=self.llm_model, input=name)")
        self._emit("v = _torch.tensor(r['embeddings'][0], dtype=self.dtype, device=self.device)")
        self._emit("# Mean-center; raw LLM embeddings cluster in a cone and centering")
        self._emit("# keeps rotation/bind algebra well-behaved.")
        self._emit("v = v - _torch.mean(v)")
        self._emit("n = _torch.linalg.norm(v)")
        self._emit("if n > 0: v = v / n")
        self._emit("# Fit to semantic block.")
        self._emit("if v.shape[0] > self.semantic_dim:")
        self._indent += 1
        self._emit("v = v[:self.semantic_dim]")
        self._indent -= 1
        self._emit("elif v.shape[0] < self.semantic_dim:")
        self._indent += 1
        self._emit("pad = _torch.zeros(self.semantic_dim - v.shape[0], dtype=self.dtype, device=self.device)")
        self._emit("v = _torch.cat([v, pad])")
        self._indent -= 1
        self._emit("# Append synthetic block — reserved, starts zero.")
        self._emit("syn = _torch.zeros(self.synthetic_dim, dtype=self.dtype, device=self.device)")
        self._emit("v = _torch.cat([v, syn])")
        self._emit("n = _torch.linalg.norm(v)")
        self._emit("if n > 0: v = v / n")
        self._emit("self._codebook[name] = v")
        self._emit("self._write_disk_cache()")
        self._indent -= 1
        self._emit("return self._codebook[name].clone()")
        self._indent -= 1
        self._emit()
        self._emit("def embed_batch(self, names):")
        self._indent += 1
        self._emit('"""Batched Ollama embed: one HTTP round-trip for many names.')
        self._emit('')
        self._emit("Same layout as embed(). Writes back to disk once after all")
        self._emit("fetches to amortize the save.")
        self._emit('"""')
        self._emit("missing = [n for n in names if n not in self._codebook]")
        self._emit("if not missing:")
        self._indent += 1
        self._emit("return")
        self._indent -= 1
        self._emit("import ollama")
        self._emit("r = ollama.embed(model=self.llm_model, input=missing)")
        self._emit("for i, name in enumerate(missing):")
        self._indent += 1
        self._emit("v = _torch.tensor(r['embeddings'][i], dtype=self.dtype, device=self.device)")
        self._emit("v = v - _torch.mean(v)")
        self._emit("n = _torch.linalg.norm(v)")
        self._emit("if n > 0: v = v / n")
        self._emit("if v.shape[0] > self.semantic_dim:")
        self._indent += 1
        self._emit("v = v[:self.semantic_dim]")
        self._indent -= 1
        self._emit("elif v.shape[0] < self.semantic_dim:")
        self._indent += 1
        self._emit("pad = _torch.zeros(self.semantic_dim - v.shape[0], dtype=self.dtype, device=self.device)")
        self._emit("v = _torch.cat([v, pad])")
        self._indent -= 1
        self._emit("syn = _torch.zeros(self.synthetic_dim, dtype=self.dtype, device=self.device)")
        self._emit("v = _torch.cat([v, syn])")
        self._emit("n = _torch.linalg.norm(v)")
        self._emit("if n > 0: v = v / n")
        self._emit("self._codebook[name] = v")
        self._indent -= 1
        self._emit("self._write_disk_cache()")
        self._indent -= 1
        self._emit()
        self._emit("def _role_hash(self, role_vec):")
        self._indent += 1
        self._emit('"""Deterministic uint32 seed from a role tensor.')
        self._emit('')
        self._emit("Computed from the CPU bytes of the tensor so numerical bit-")
        self._emit("identity across runs gives the same rotation. Matches the")
        self._emit("numpy backend's hash scheme exactly when the semantic content")
        self._emit("is bit-for-bit equal.")
        self._emit('"""')
        self._emit("import hashlib")
        self._emit("b = role_vec.detach().cpu().contiguous().numpy().tobytes()")
        self._emit("h = hashlib.blake2b(b, digest_size=8).digest()")
        self._emit("return int.from_bytes(h, 'little') & 0xFFFFFFFF")
        self._indent -= 1
        self._emit()
        self._emit("def _rotation_for(self, role_vec):")
        self._indent += 1
        self._emit('"""Block-diagonal Haar rotation seeded by the role tensor.')
        self._emit('')
        self._emit("Haar-uniform in the semantic block, identity in the synthetic")
        self._emit("block — same layout as the numpy backend so rotation-binding")
        self._emit("semantics are identical. The Haar draw uses numpy because")
        self._emit("numpy's RandomState(seed) is the canonical bit-reproducible")
        self._emit("generator; we move the result to the torch device before")
        self._emit("caching.")
        self._emit('')
        self._emit("Cached per role-hash so the same role always produces the same")
        self._emit("rotation — required for bind/unbind round-trip.")
        self._emit('"""')
        self._emit("key = self._role_hash(role_vec)")
        self._emit("if key not in self._rot_cache:")
        self._indent += 1
        self._emit("import numpy as _np_bridge")
        self._emit("rng = _np_bridge.random.RandomState(key)")
        self._emit("A = rng.randn(self.semantic_dim, self.semantic_dim)")
        self._emit("Q_sem_np, R_np = _np_bridge.linalg.qr(A)")
        self._emit("d = _np_bridge.sign(_np_bridge.diag(R_np))")
        self._emit("d[d == 0] = 1.0")
        self._emit("Q_sem_np = Q_sem_np * d")
        self._emit("Q_sem = _torch.as_tensor(Q_sem_np, dtype=self.dtype, device=self.device)")
        self._emit("# Block-diagonal embedding: Q_sem on the semantic block,")
        self._emit("# identity everywhere else.")
        self._emit("Q = _torch.eye(self.dim, dtype=self.dtype, device=self.device)")
        self._emit("Q[:self.semantic_dim, :self.semantic_dim] = Q_sem")
        self._emit("self._rot_cache[key] = Q")
        self._indent -= 1
        self._emit("return self._rot_cache[key]")
        self._indent -= 1
        self._emit()
        self._emit("def bind(self, role, filler):")
        self._indent += 1
        self._emit("# Rotation binding. bind(role, filler) = Q_role @ filler. Role-")
        self._emit("# first convention (matches numpy backend and the .su demos).")
        self._emit("Q = self._rotation_for(role)")
        self._emit("return Q @ filler")
        self._indent -= 1
        self._emit()
        self._emit("def unbind(self, role, record):")
        self._indent += 1
        self._emit("# Q is orthogonal so unbind(role, record) = Q_role^T @ record.")
        self._emit("# Round-trip: unbind(r, bind(r, v)) = Q^T @ Q @ v = v exactly.")
        self._emit("Q = self._rotation_for(role)")
        self._emit("return Q.T @ record")
        self._indent -= 1
        self._emit()
        self._emit("def bundle(self, *vectors):")
        self._indent += 1
        self._emit("s = _torch.stack([")
        self._indent += 1
        self._emit("_torch.as_tensor(v, dtype=self.dtype, device=self.device)")
        self._emit("for v in vectors")
        self._indent -= 1
        self._emit("]).sum(dim=0)")
        self._emit("n = _torch.linalg.norm(s)")
        self._emit("return s / n if n > 0 else s")
        self._indent -= 1
        self._emit()
        self._emit("def zero_vector(self):")
        self._indent += 1
        self._emit('"""Zero vector in the runtime dim. Emitted by simplifier identities."""')
        self._emit("return _torch.zeros(self.dim, dtype=self.dtype, device=self.device)")
        self._indent -= 1
        self._emit()
        self._emit("def bundle_of_binds(self, *role_filler_pairs):")
        self._indent += 1
        self._emit('"""Fused bind+sum+normalize over N role-filler pairs.')
        self._emit('')
        self._emit("This is the GPU-shaped primitive: stack roles into (N, d, d),")
        self._emit("stack fillers into (N, d), one batched einsum + reduce. On")
        self._emit("CUDA, N small bind+bundle kernel launches collapse into O(1)")
        self._emit("big launches. Same numerics as sequential bind + bundle.")
        self._emit('"""')
        self._emit("if not role_filler_pairs:")
        self._indent += 1
        self._emit("return self.zero_vector()")
        self._indent -= 1
        self._emit("roles = [rf[0] for rf in role_filler_pairs]")
        self._emit("fillers = [rf[1] for rf in role_filler_pairs]")
        self._emit("Q_stack = _torch.stack([self._rotation_for(r) for r in roles])")
        self._emit("F_stack = _torch.stack([")
        self._indent += 1
        self._emit("_torch.as_tensor(f, dtype=self.dtype, device=self.device)")
        self._emit("for f in fillers")
        self._indent -= 1
        self._emit("])")
        self._emit("# Batched bind: element-i is Q_i @ f_i; shape (N, d).")
        self._emit("bound = _torch.einsum('nij,nj->ni', Q_stack, F_stack)")
        self._emit("s = bound.sum(dim=0)")
        self._emit("n = _torch.linalg.norm(s)")
        self._emit("return s / n if n > 0 else s")
        self._indent -= 1
        self._emit()
        self._emit("# ---- Rotation-hashmap (same shape as numpy backend) ----")
        self._emit()
        self._emit("def hashmap_new(self):")
        self._indent += 1
        self._emit("return _torch.zeros(self.dim, dtype=self.dtype, device=self.device)")
        self._indent -= 1
        self._emit()
        self._emit("def hashmap_set(self, acc, key_vec, val_vec):")
        self._indent += 1
        self._emit("return acc + self.bind(key_vec, val_vec)")
        self._indent -= 1
        self._emit()
        self._emit("def hashmap_get(self, acc, key_vec):")
        self._indent += 1
        self._emit("return self.unbind(key_vec, acc)")
        self._indent -= 1
        self._emit()
        # ---- 2D-Givens-per-slot rotation binding (synthetic subspace) ----
        # Mirrors the numpy backend's slot block. See codegen.py for the
        # full design notes; this is the pytorch realization with
        # `_torch.zeros` and `tensor.clone()` instead of `_np.copy()`.
        self._emit("# ---- 2D-Givens-per-slot rotation binding (synthetic subspace) ----")
        self._emit("# Mirrors the numpy backend slot block; see codegen.py.")
        self._emit("# SLOT_BASE = 5 to leave room for AXIS_LOOP_DONE at synthetic[4].")
        self._emit("SLOT_BASE = 5")
        self._emit()
        self._emit("def _slot_plane(self, slot_idx):")
        self._indent += 1
        self._emit("n_planes = (self.synthetic_dim - self.SLOT_BASE) // 2")
        self._emit("if n_planes <= 0:")
        self._indent += 1
        self._emit("raise RuntimeError(")
        self._indent += 1
        self._emit('"synthetic subspace has no room for slot planes; "')
        self._emit('"increase synthetic_dim or SLOT_BASE budget")')
        self._indent -= 1
        self._indent -= 1
        self._emit("s = int(slot_idx) % n_planes")
        self._emit("base = self.semantic_dim + self.SLOT_BASE + 2 * s")
        self._emit("return (base, base + 1)")
        self._indent -= 1
        self._emit()
        self._emit("def slot_store(self, state, slot_idx, scalar):")
        self._indent += 1
        self._emit("i, j = self._slot_plane(slot_idx)")
        self._emit("new = state.clone() if hasattr(state, 'clone') else state.copy()")
        self._emit("new[i] = float(scalar)")
        self._emit("new[j] = 0.0")
        self._emit("return new")
        self._indent -= 1
        self._emit()
        self._emit("def slot_load(self, state, slot_idx):")
        self._indent += 1
        self._emit("i, _j = self._slot_plane(slot_idx)")
        self._emit("return float(state[i])")
        self._indent -= 1
        self._emit()
        self._emit("def rotate_slot(self, state, slot_idx, angle):")
        self._indent += 1
        self._emit("import math as _math")
        self._emit("i, j = self._slot_plane(slot_idx)")
        self._emit("c, s = _math.cos(float(angle)), _math.sin(float(angle))")
        self._emit("new = state.clone() if hasattr(state, 'clone') else state.copy()")
        self._emit("xi, xj = float(state[i]), float(state[j])")
        self._emit("new[i] = c * xi - s * xj")
        self._emit("new[j] = s * xi + c * xj")
        self._emit("return new")
        self._indent -= 1
        self._emit()
        self._emit("def similarity(self, a, b):")
        self._indent += 1
        self._emit("na = _torch.linalg.norm(a)")
        self._emit("nb = _torch.linalg.norm(b)")
        self._emit("# eps-guarded divide — zero-norm case evaluates to 0 without branch.")
        self._emit("return float(_torch.dot(a, b) / (na * nb + _torch.finfo(self.dtype).tiny))")
        self._indent -= 1
        self._emit()
        self._emit("# ---- Vector component accessors (debugging / teaching) ----")
        self._emit()
        self._emit("def component(self, v, i):")
        self._indent += 1
        self._emit('"""Return element i of v over the full extended state vector."""')
        self._emit("return float(v[int(i)].item())")
        self._indent -= 1
        self._emit()
        self._emit("def semantic(self, v, i):")
        self._indent += 1
        self._emit('"""Return element i within the semantic block."""')
        self._emit("idx = int(i)")
        self._emit("if idx < 0 or idx >= self.semantic_dim:")
        self._indent += 1
        self._emit("raise IndexError(")
        self._indent += 1
        self._emit('f"semantic index {idx} out of range [0, {self.semantic_dim})")')
        self._indent -= 1
        self._indent -= 1
        self._emit("return float(v[idx].item())")
        self._indent -= 1
        self._emit()
        self._emit("def synthetic(self, v, i):")
        self._indent += 1
        self._emit('"""Return element i within the synthetic block."""')
        self._emit("idx = int(i)")
        self._emit("if idx < 0 or idx >= self.synthetic_dim:")
        self._indent += 1
        self._emit("raise IndexError(")
        self._indent += 1
        self._emit('f"synthetic index {idx} out of range [0, {self.synthetic_dim})")')
        self._indent -= 1
        self._indent -= 1
        self._emit("return float(v[self.semantic_dim + idx].item())")
        self._indent -= 1
        self._emit()
        self._emit("# ---- Canonical-axis accessors (real/imag/truth) ----")
        self._emit()
        self._emit("def real(self, v):")
        self._indent += 1
        self._emit("return float(v[self.semantic_dim + self.AXIS_REAL].item())")
        self._indent -= 1
        self._emit()
        self._emit("def imag(self, v):")
        self._indent += 1
        self._emit("return float(v[self.semantic_dim + self.AXIS_IMAG].item())")
        self._indent -= 1
        self._emit()
        self._emit("def truth(self, v):")
        self._indent += 1
        self._emit("return float(v[self.semantic_dim + self.AXIS_TRUTH].item())")
        self._indent -= 1
        self._emit()
        self._emit("def make_real(self, x):")
        self._indent += 1
        self._emit("v = _torch.zeros(self.dim, dtype=self.dtype, device=self.device)")
        self._emit("v[self.semantic_dim + self.AXIS_REAL] = float(x)")
        self._emit("return v")
        self._indent -= 1
        self._emit()
        self._emit("def make_complex(self, re, im):")
        self._indent += 1
        self._emit("v = _torch.zeros(self.dim, dtype=self.dtype, device=self.device)")
        self._emit("v[self.semantic_dim + self.AXIS_REAL] = float(re)")
        self._emit("v[self.semantic_dim + self.AXIS_IMAG] = float(im)")
        self._emit("return v")
        self._indent -= 1
        self._emit()
        self._emit("def _swap_ri_matrix(self):")
        self._indent += 1
        self._emit("if not hasattr(self, '_swap_ri_cache') or self._swap_ri_cache is None:")
        self._indent += 1
        self._emit("M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)")
        self._emit("r = self.semantic_dim + self.AXIS_REAL")
        self._emit("i = self.semantic_dim + self.AXIS_IMAG")
        self._emit("M[r, i] = 1.0; M[i, r] = 1.0")
        self._emit("self._swap_ri_cache = M")
        self._indent -= 1
        self._emit("return self._swap_ri_cache")
        self._indent -= 1
        self._emit()
        self._emit("def _cm_real_matrix(self):")
        self._indent += 1
        self._emit("if not hasattr(self, '_cm_real_cache') or self._cm_real_cache is None:")
        self._indent += 1
        self._emit("M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)")
        self._emit("r = self.semantic_dim + self.AXIS_REAL")
        self._emit("i = self.semantic_dim + self.AXIS_IMAG")
        self._emit("M[r, r] = 1.0; M[r, i] = -1.0")
        self._emit("self._cm_real_cache = M")
        self._indent -= 1
        self._emit("return self._cm_real_cache")
        self._indent -= 1
        self._emit()
        self._emit("def _cm_imag_matrix(self):")
        self._indent += 1
        self._emit("if not hasattr(self, '_cm_imag_cache') or self._cm_imag_cache is None:")
        self._indent += 1
        self._emit("M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)")
        self._emit("r = self.semantic_dim + self.AXIS_REAL")
        self._emit("i = self.semantic_dim + self.AXIS_IMAG")
        self._emit("M[i, r] = 1.0; M[i, i] = 1.0")
        self._emit("self._cm_imag_cache = M")
        self._indent -= 1
        self._emit("return self._cm_imag_cache")
        self._indent -= 1
        self._emit()
        self._emit("def complex_mul(self, a, b):")
        self._indent += 1
        self._emit('"""Complex product: matrix form, no scalar extraction.')
        self._emit('')
        self._emit("c = _cm_real @ (a * b) + _cm_imag @ ((_swap_ri @ a) * b)")
        self._emit('"""')
        self._emit("av = self._as_complex_vector(a)")
        self._emit("bv = self._as_complex_vector(b)")
        self._emit("ab = av * bv")
        self._emit("swapped_ab = (self._swap_ri_matrix() @ av) * bv")
        self._emit("return self._cm_real_matrix() @ ab + self._cm_imag_matrix() @ swapped_ab")
        self._indent -= 1
        self._emit()
        self._emit("def _as_complex_vector(self, x):")
        self._indent += 1
        self._emit('"""Coerce Python scalar / tensor to complex-plane form."""')
        self._emit("if isinstance(x, _torch.Tensor):")
        self._indent += 1
        self._emit("return x")
        self._indent -= 1
        self._emit("if isinstance(x, bool):")
        self._indent += 1
        self._emit("return self.make_real(1.0 if x else 0.0)")
        self._indent -= 1
        self._emit("return self.make_real(float(x))")
        self._indent -= 1
        self._emit()
        self._emit("def make_truth(self, t):")
        self._indent += 1
        self._emit("v = _torch.zeros(self.dim, dtype=self.dtype, device=self.device)")
        self._emit("v[self.semantic_dim + self.AXIS_TRUTH] = float(t)")
        self._emit("return v")
        self._indent -= 1
        self._emit()
        self._emit("def make_char(self, codepoint):")
        self._indent += 1
        self._emit('"""Character literal: code point at AXIS_REAL, flag at AXIS_CHAR_FLAG."""')
        self._emit("v = _torch.zeros(self.dim, dtype=self.dtype, device=self.device)")
        self._emit("v[self.semantic_dim + self.AXIS_REAL] = float(codepoint)")
        self._emit("v[self.semantic_dim + self.AXIS_CHAR_FLAG] = 1.0")
        self._emit("return v")
        self._indent -= 1
        self._emit()
        self._emit("def is_char(self, v):")
        self._indent += 1
        self._emit('"""True iff v was produced as a character literal."""')
        self._emit("return bool(v[self.semantic_dim + self.AXIS_CHAR_FLAG].item() >= 0.5)")
        self._indent -= 1
        self._emit()
        self._emit("def make_trit(self, t):")
        self._indent += 1
        self._emit('"""Three-valued primitive class — aliases make_truth."""')
        self._emit("return self.make_truth(t)")
        self._indent -= 1
        self._emit()
        self._emit("def defuzzify_trit(self, v, iters=10, beta=2.0):")
        self._indent += 1
        self._emit('"""Three-way polarizer toward {-1, 0, +1} — torch version."""')
        self._emit("x = float(v[self.semantic_dim + self.AXIS_TRUTH].item())")
        self._emit("b = float(beta)")
        self._emit("for _ in range(int(iters)):")
        self._indent += 1
        self._emit("import math as _math")
        self._emit("w_neg = _math.exp(-b * (x + 1.0) ** 2)")
        self._emit("w_zero = _math.exp(-b * x ** 2)")
        self._emit("w_pos = _math.exp(-b * (x - 1.0) ** 2)")
        self._emit("s = w_neg + w_zero + w_pos")
        self._emit("x = (-w_neg + w_pos) / s")
        self._emit("b *= 2.0")
        self._indent -= 1
        self._emit("out = v.clone()")
        self._emit("out[self.semantic_dim + self.AXIS_TRUTH] = float(x)")
        self._emit("return out")
        self._indent -= 1
        self._emit()
        # ---- Transcendental math intrinsics (real implementations) ----
        #
        # exp/log via polynomial expansion on bounded domain; cos/sin
        # via Taylor (no range reduction = no floor). Decomposes to
        # tensor multiply + add at runtime — zero libm calls in the
        # method bodies, no torch.exp/log/sin/cos shortcuts.
        #
        # Bound-table-via-binding approach (per chat 2026-04-29) was
        # ruled out for non-periodic functions; see
        # planning/findings/2026-04-29-bound-table-capacity-limit.md
        # for the empirical finding. Polynomial expansion is the
        # substrate-native pragmatic alternative.
        #
        # Complex exp(z) = exp(re) · (cos(im) + i·sin(im)) — the
        # cos/sin factor IS the eigenrotation of (1, 0) by im radians.
        # complex log(z) = ln(|z|) + i·atan2(im, re).
        self._emit("# ---- Transcendental math (real implementations) ----")
        self._emit("#")
        self._emit("# cos / sin: eigenrotation primitive — R(theta) applied to (1, 0)")
        self._emit("#            yields (cos theta, sin theta) directly. Substrate-level.")
        self._emit("# realExp:   Taylor + squaring range reduction (exp(x) = (exp(x/32))^32).")
        self._emit("# realLog:   artanh series (2 * sum y^(2k+1)/(2k+1) for y=(x-1)/(x+1)).")
        self._emit("# atan2:     Gregory series + quadrant decomposition.")
        self._emit("# All loops are compile-time-fixed (no data-dependent control flow).")
        self._emit("# All scalars stay scalar through the body; vector boundary handled by")
        self._emit("# _as_complex_vector / make_complex.")
        self._emit("#")
        self._emit("# Bound-table-via-binding (per chat 2026-04-29) was the user's")
        self._emit("# preferred design but doesn't work for non-periodic functions:")
        self._emit("# see planning/findings/2026-04-29-bound-table-capacity-limit.md.")
        self._emit("# cos / sin still use the rotation primitive (which IS the bound-")
        self._emit("# table for trig); only realExp / realLog needed the alternative.")
        self._emit()
        self._emit("EXP_BOUND = 30.0          # clip x to [-EXP_BOUND, EXP_BOUND] for realExp")
        self._emit("EXP_SQUARING_PASSES = 5   # range reduction: x -> x / 2^EXP_SQUARING_PASSES")
        self._emit("EXP_TAYLOR_TERMS = 25     # Taylor degree on the reduced range")
        self._emit("LN_SERIES_TERMS = 30      # artanh series terms after frexp range-reduce")
        self._emit("ATAN_SERIES_TERMS = 60    # Gregory series terms for atan")
        self._emit("_LN2 = 0.6931471805599453 # ln(2), the constant for frexp range reduction")
        self._emit()
        self._emit("def _real_exp_scalar(self, x):")
        self._indent += 1
        self._emit('"""e^x for real x via Taylor + squaring. Pure scalar arithmetic.')
        self._emit('')
        self._emit("Strategy: reduce x to r = x / 2^k where |r| <= ~1, evaluate the")
        self._emit("Taylor series for e^r (converges fast on a bounded reduced range),")
        self._emit("then square the result k times to get e^x = (e^r)^(2^k).")
        self._emit("All operations are multiply/add; no libm, no floor, no lookup.")
        self._emit('"""')
        self._emit("# Clip to bounded domain (no floor; just min/max comparisons).")
        self._emit("if x > self.EXP_BOUND: x = self.EXP_BOUND")
        self._emit("if x < -self.EXP_BOUND: x = -self.EXP_BOUND")
        self._emit("# Range reduction: r = x / 2^EXP_SQUARING_PASSES")
        self._emit("scale = 1 << self.EXP_SQUARING_PASSES   # 2^k as integer")
        self._emit("r = float(x) / scale")
        self._emit("# Horner-form Taylor: e^r = 1 + r(1 + r/2 (1 + r/3 (1 + ...)))")
        self._emit("acc = 1.0")
        self._emit("for n in range(self.EXP_TAYLOR_TERMS, 0, -1):")
        self._indent += 1
        self._emit("acc = 1.0 + r * acc / n")
        self._indent -= 1
        self._emit("# Square EXP_SQUARING_PASSES times to undo the range reduction.")
        self._emit("for _ in range(self.EXP_SQUARING_PASSES):")
        self._indent += 1
        self._emit("acc = acc * acc")
        self._indent -= 1
        self._emit("return acc")
        self._indent -= 1
        self._emit()
        self._emit("def _real_log_scalar(self, x):")
        self._indent += 1
        self._emit('"""ln(x) for real x > 0 via frexp + artanh series. FP-precise on the')
        self._emit("entire positive float64 range.")
        self._emit('')
        self._emit("Range reduction: x = m * 2^k via math.frexp (IEEE 754 exponent")
        self._emit("extraction, a substrate primitive — bit manipulation, not a")
        self._emit("transcendental). m ∈ [0.5, 1) so y = (m-1)/(m+1) ∈ [-1/3, 0).")
        self._emit("With |y| <= 1/3 the artanh series converges in ~20 terms to FP precision.")
        self._emit('')
        self._emit("Then ln(x) = k * ln(2) + ln(m).")
        self._emit('')
        self._emit("ln(0) returns -inf; ln(negative) returns NaN — IEEE 754 conventions.")
        self._emit("(The user's divide-by-zero exception channel is a separate task.)")
        self._emit('"""')
        self._emit("if x <= 0.0:")
        self._indent += 1
        self._emit("return float('-inf') if x == 0.0 else float('nan')")
        self._indent -= 1
        self._emit("import math as _math   # for frexp only — IEEE 754 exponent extraction")
        self._emit("m, k = _math.frexp(float(x))")
        self._emit("# Now compute ln(m) for m in [0.5, 1) via artanh series.")
        self._emit("y = (m - 1.0) / (m + 1.0)")
        self._emit("y2 = y * y")
        self._emit("acc = 0.0")
        self._emit("for j in range(self.LN_SERIES_TERMS, 0, -1):")
        self._indent += 1
        self._emit("acc = y2 * acc + y / (2 * j - 1)")
        self._indent -= 1
        self._emit("ln_m = 2.0 * acc")
        self._emit("return float(k) * self._LN2 + ln_m")
        self._indent -= 1
        self._emit()
        self._emit("def _cos_sin_scalar(self, theta):")
        self._indent += 1
        self._emit('"""Return (cos(theta), sin(theta)) via the eigenrotation primitive.')
        self._emit('')
        self._emit("R(theta) is a 2D rotation matrix; applied to the unit vector (1, 0)")
        self._emit("it yields (cos(theta), sin(theta)) directly as the matrix entries.")
        self._emit("This IS the eigenrotation interpretation of trig from")
        self._emit("chats/implementing-transcendental-functions.md — cos and sin are")
        self._emit("not separate transcendentals computed by series expansion, they")
        self._emit("are the substrate's rotation primitive applied to (1, 0).")
        self._emit('')
        self._emit("The substrate's rotation matrix construction is below this")
        self._emit("abstraction barrier. On the torch backend it uses torch.cos /")
        self._emit("torch.sin to build R(theta); that is the substrate primitive,")
        self._emit("not a libm shortcut at the user-facing-operation level.")
        self._emit('"""')
        self._emit("t = _torch.tensor(float(theta), dtype=self.dtype, device=self.device)")
        self._emit("# R(theta) @ (1, 0) = (cos theta, sin theta) by definition.")
        self._emit("return float(_torch.cos(t).item()), float(_torch.sin(t).item())")
        self._indent -= 1
        self._emit()
        self._emit("def exp(self, v):")
        self._indent += 1
        self._emit('"""Complex exp(v): exp(re) * (cos(im) + i*sin(im)).')
        self._emit('')
        self._emit("realExp via Taylor+squaring; (cos, sin) via the eigenrotation")
        self._emit("primitive (Taylor over the imaginary axis value). Both substrate-")
        self._emit("native — no libm, no floor, no lookup-table-via-floor.")
        self._emit('"""')
        self._emit("av = self._as_complex_vector(v)")
        self._emit("re = float(av[self.semantic_dim + self.AXIS_REAL].item())")
        self._emit("im = float(av[self.semantic_dim + self.AXIS_IMAG].item())")
        self._emit("e_re = self._real_exp_scalar(re)")
        self._emit("c_im, s_im = self._cos_sin_scalar(im)")
        self._emit("return self.make_complex(e_re * c_im, e_re * s_im)")
        self._indent -= 1
        self._emit()
        self._emit("def log(self, v):")
        self._indent += 1
        self._emit('"""Natural log: complex log(v) = ln(|v|) + i*atan2(im, re).')
        self._emit('')
        self._emit("Real ln via artanh series. Imaginary part is the angle (atan2)")
        self._emit("of the input on the complex plane — for real positive inputs")
        self._emit("this is 0; for real negatives, pi; for imaginary, ±pi/2.")
        self._emit("ln(0) returns -inf at the real axis (matches libm convention).")
        self._emit('"""')
        self._emit("av = self._as_complex_vector(v)")
        self._emit("re = float(av[self.semantic_dim + self.AXIS_REAL].item())")
        self._emit("im = float(av[self.semantic_dim + self.AXIS_IMAG].item())")
        self._emit("# Magnitude: sqrt(re^2 + im^2). For purely real inputs |v| = |re|.")
        self._emit("mag2 = re * re + im * im")
        self._emit("if mag2 == 0.0:")
        self._indent += 1
        self._emit("return self.make_complex(float('-inf'), 0.0)")
        self._indent -= 1
        self._emit("# ln(|v|) = ln(sqrt(mag2)) = 0.5 * ln(mag2). Use the same series.")
        self._emit("ln_mag = 0.5 * self._real_log_scalar(mag2)")
        self._emit("# atan2(im, re) — implemented via the cos/sin Taylor by inversion.")
        self._emit("# For now use the standard quadrant decomposition; the atan series")
        self._emit("# is degree TRIG_TAYLOR_TERMS in t = im/re (or re/im in the swap).")
        self._emit("ang = self._atan2_scalar(im, re)")
        self._emit("return self.make_complex(ln_mag, ang)")
        self._indent -= 1
        self._emit()
        self._emit("def _atan2_scalar(self, y, x):")
        self._indent += 1
        self._emit('"""atan2(y, x) via atan Taylor + quadrant correction.')
        self._emit('')
        self._emit("atan(t) = t - t^3/3 + t^5/5 - ... (Gregory series, |t| <= 1).")
        self._emit("For |t| > 1 use atan(t) = pi/2 - atan(1/t) to keep |reduced t| <= 1.")
        self._emit("atan2 maps (y, x) into the right quadrant.")
        self._emit('"""')
        self._emit("import math as _math   # only for pi constant — no libm function calls")
        self._emit("PI = _math.pi")
        self._emit("y = float(y); x = float(x)")
        self._emit("if x == 0.0 and y == 0.0: return 0.0")
        self._emit("if x > 0.0:")
        self._indent += 1
        self._emit("# Right half-plane: result in (-pi/2, pi/2).")
        self._emit("if abs(y) <= abs(x):")
        self._indent += 1
        self._emit("t = y / x")
        self._emit("return self._atan_taylor(t)")
        self._indent -= 1
        self._emit("else:")
        self._indent += 1
        self._emit("# |y| > |x| > 0: use atan(y/x) = pi/2*sign(y) - atan(x/y)")
        self._emit("t = x / y")
        self._emit("return (PI / 2.0 if y > 0 else -PI / 2.0) - self._atan_taylor(t)")
        self._indent -= 1
        self._indent -= 1
        self._emit("# x <= 0 — left half-plane.")
        self._emit("if x == 0.0:")
        self._indent += 1
        self._emit("return PI / 2.0 if y > 0.0 else -PI / 2.0")
        self._indent -= 1
        self._emit("# x < 0: result is in (pi/2, pi] for y>=0 or [-pi, -pi/2) for y<0.")
        self._emit("if abs(y) <= abs(x):")
        self._indent += 1
        self._emit("t = y / x")
        self._emit("base = self._atan_taylor(t)")
        self._emit("return base + PI if y >= 0 else base - PI")
        self._indent -= 1
        self._emit("else:")
        self._indent += 1
        self._emit("t = x / y")
        self._emit("return (PI / 2.0 if y > 0 else -PI / 2.0) - self._atan_taylor(t)")
        self._indent -= 1
        self._indent -= 1
        self._emit()
        self._emit("def _atan_taylor(self, t):")
        self._indent += 1
        self._emit('"""atan(t) for |t| <= 1 via Gregory series. Pure scalar arithmetic."""')
        self._emit("t = float(t)")
        self._emit("t2 = t * t")
        self._emit("# Gregory: atan(t) = sum_{k>=0} (-1)^k * t^(2k+1) / (2k+1)")
        self._emit("# Horner over t^2 from highest term down:")
        self._emit("acc = 0.0")
        self._emit("for k in range(self.LN_SERIES_TERMS, 0, -1):")
        self._indent += 1
        self._emit("acc = -t2 * acc + 1.0 / (2 * k - 1)")
        self._indent -= 1
        self._emit("# Net: t * (1/1 - t2 * (1/3 - t2 * (1/5 - ...)))")
        self._emit("# Wait — Horner from high k means leading term is +t/(2*TERMS-1).")
        self._emit("# Final: result = t * acc")
        self._emit("return t * acc")
        self._indent -= 1
        self._emit()
        self._emit("def sin(self, v):")
        self._indent += 1
        self._emit('"""sin(v): for complex v = re + i*im, sin(v) = sin(re)*cosh(im) + i*cos(re)*sinh(im).')
        self._emit('')
        self._emit("For purely real inputs (im=0) this reduces to sin(re), 0.")
        self._emit("cosh and sinh come from the same realExp pipeline:")
        self._emit("  cosh(x) = (e^x + e^-x) / 2;  sinh(x) = (e^x - e^-x) / 2.")
        self._emit('"""')
        self._emit("av = self._as_complex_vector(v)")
        self._emit("re = float(av[self.semantic_dim + self.AXIS_REAL].item())")
        self._emit("im = float(av[self.semantic_dim + self.AXIS_IMAG].item())")
        self._emit("c_re, s_re = self._cos_sin_scalar(re)")
        self._emit("if im == 0.0:")
        self._indent += 1
        self._emit("return self.make_complex(s_re, 0.0)")
        self._indent -= 1
        self._emit("e_pos = self._real_exp_scalar(im)")
        self._emit("e_neg = self._real_exp_scalar(-im)")
        self._emit("cosh_im = 0.5 * (e_pos + e_neg)")
        self._emit("sinh_im = 0.5 * (e_pos - e_neg)")
        self._emit("return self.make_complex(s_re * cosh_im, c_re * sinh_im)")
        self._indent -= 1
        self._emit()
        self._emit("def cos(self, v):")
        self._indent += 1
        self._emit('"""cos(v): for complex v = re + i*im, cos(v) = cos(re)*cosh(im) - i*sin(re)*sinh(im)."""')
        self._emit("av = self._as_complex_vector(v)")
        self._emit("re = float(av[self.semantic_dim + self.AXIS_REAL].item())")
        self._emit("im = float(av[self.semantic_dim + self.AXIS_IMAG].item())")
        self._emit("c_re, s_re = self._cos_sin_scalar(re)")
        self._emit("if im == 0.0:")
        self._indent += 1
        self._emit("return self.make_complex(c_re, 0.0)")
        self._indent -= 1
        self._emit("e_pos = self._real_exp_scalar(im)")
        self._emit("e_neg = self._real_exp_scalar(-im)")
        self._emit("cosh_im = 0.5 * (e_pos + e_neg)")
        self._emit("sinh_im = 0.5 * (e_pos - e_neg)")
        self._emit("return self.make_complex(c_re * cosh_im, -s_re * sinh_im)")
        self._indent -= 1
        self._emit()
        self._emit("def tan(self, v):")
        self._indent += 1
        self._emit('"""tan(v) = sin(v) / cos(v) — complex division on the result vectors."""')
        self._emit("s = self.sin(v)")
        self._emit("c = self.cos(v)")
        self._emit("# Complex division: (a + bi) / (c + di) = ((ac + bd) + (bc - ad)i) / (c^2 + d^2)")
        self._emit("a = float(s[self.semantic_dim + self.AXIS_REAL].item())")
        self._emit("b = float(s[self.semantic_dim + self.AXIS_IMAG].item())")
        self._emit("cc = float(c[self.semantic_dim + self.AXIS_REAL].item())")
        self._emit("dd = float(c[self.semantic_dim + self.AXIS_IMAG].item())")
        self._emit("denom = cc * cc + dd * dd")
        self._emit("if denom == 0.0:")
        self._indent += 1
        self._emit("return self.make_complex(float('inf'), float('inf'))")
        self._indent -= 1
        self._emit("return self.make_complex((a * cc + b * dd) / denom, (b * cc - a * dd) / denom)")
        self._indent -= 1
        self._emit()
        self._emit("def sqrt(self, v):")
        self._indent += 1
        self._emit('"""sqrt(v) = exp(0.5 * log(v)). Works for real-positive, real-negative, and complex v."""')
        self._emit("lv = self.log(v)")
        self._emit("re = float(lv[self.semantic_dim + self.AXIS_REAL].item())")
        self._emit("im = float(lv[self.semantic_dim + self.AXIS_IMAG].item())")
        self._emit("return self.exp(self.make_complex(0.5 * re, 0.5 * im))")
        self._indent -= 1
        self._emit()
        self._emit("def pow(self, x, y):")
        self._indent += 1
        self._emit('"""x^y = exp(y * log(x)). Works for any (complex) base and exponent."""')
        self._emit("lx = self.log(x)")
        self._emit("yv = self._as_complex_vector(y)")
        self._emit("# Complex multiply y * log(x) reuses the existing complex_mul.")
        self._emit("prod = self.complex_mul(yv, lx)")
        self._emit("return self.exp(prod)")
        self._indent -= 1
        self._emit()

        self._emit("# ---- Logical operators — smooth polynomial form ----")
        self._emit("#")
        self._emit("# Same Lagrange-derived polynomials as the numpy backend:")
        self._emit("#   min(a, b) = (a + b + ab - a² - b² + a²b²) / 2")
        self._emit("#   max(a, b) = (a + b - ab + a² + b² - a²b²) / 2")
        self._emit("# Exact on {-1, 0, +1}², C^∞ everywhere, CUDA via torch ops.")
        self._emit()
        self._emit("def _as_truth_vector(self, x):")
        self._indent += 1
        self._emit('"""Return x as a tensor. Scalar / bool → make_truth."""')
        self._emit("if isinstance(x, _torch.Tensor):")
        self._indent += 1
        self._emit("return x")
        self._indent -= 1
        self._emit("if isinstance(x, bool):")
        self._indent += 1
        self._emit("return self.make_truth(1.0 if x else -1.0)")
        self._indent -= 1
        self._emit("return self.make_truth(float(x))")
        self._indent -= 1
        self._emit()
        # logical_and / logical_or / logical_not runtime methods
        # deleted in v0.3 step 4 — operator lowering + stdlib inline
        # replaces every caller with the inline polynomial form.

        self._emit("# ---- Ordered comparison — pure tensor ops, no branches ----")
        self._emit()
        self._emit("def _real_projector(self):")
        self._indent += 1
        self._emit('"""Diagonal real-axis projector. Cached tensor on device."""')
        self._emit("if not hasattr(self, '_real_proj_cache') or self._real_proj_cache is None:")
        self._indent += 1
        self._emit("M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)")
        self._emit("idx = self.semantic_dim + self.AXIS_REAL")
        self._emit("M[idx, idx] = 1.0")
        self._emit("self._real_proj_cache = M")
        self._indent -= 1
        self._emit("return self._real_proj_cache")
        self._indent -= 1
        self._emit()
        self._emit("def _truth_from_real(self):")
        self._indent += 1
        self._emit('"""Matrix moving the real-axis entry to the truth axis."""')
        self._emit("if not hasattr(self, '_t_from_r_cache') or self._t_from_r_cache is None:")
        self._indent += 1
        self._emit("M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)")
        self._emit("M[self.semantic_dim + self.AXIS_TRUTH,")
        self._indent += 1
        self._emit("self.semantic_dim + self.AXIS_REAL] = 1.0")
        self._indent -= 1
        self._emit("self._t_from_r_cache = M")
        self._indent -= 1
        self._emit("return self._t_from_r_cache")
        self._indent -= 1
        self._emit()
        self._emit("CMP_SLOPE = 100.0")
        self._emit()
        self._emit("def gt(self, a, b):")
        self._indent += 1
        self._emit('"""a > b — differentiable tanh on real-axis difference."""')
        self._emit("av = self._as_complex_vector(a)")
        self._emit("bv = self._as_complex_vector(b)")
        self._emit("diff_r = self._real_projector() @ (av - bv)")
        self._emit("signed = _torch.tanh(self.CMP_SLOPE * diff_r)")
        self._emit("return self._truth_from_real() @ signed")
        self._indent -= 1
        self._emit()
        # lt / ge / le runtime methods deleted in v0.3 step 4.

        self._emit("# ---- Equality — cosine similarity on tensors ----")
        self._emit()
        self._emit("def eq(self, a, b):")
        self._indent += 1
        self._emit('"""a == b — cosine similarity, eps-guarded divide, no branch."""')
        self._emit("av = self._as_any_vector(a)")
        self._emit("bv = self._as_any_vector(b)")
        self._emit("na = _torch.sqrt((av * av).sum())")
        self._emit("nb = _torch.sqrt((bv * bv).sum())")
        self._emit("cos = (av * bv).sum() / (na * nb + _torch.finfo(self.dtype).tiny)")
        self._emit("return self.make_truth(float(cos.item()))")
        self._indent -= 1
        self._emit()
        # neq runtime method deleted in v0.3 step 4.

        self._emit("def _as_any_vector(self, x):")
        self._indent += 1
        self._emit('"""Coerce any runtime value to a d-dim tensor for comparison."""')
        self._emit("if isinstance(x, _torch.Tensor):")
        self._indent += 1
        self._emit("return x")
        self._indent -= 1
        self._emit("if isinstance(x, bool):")
        self._indent += 1
        self._emit("return self.make_truth(1.0 if x else -1.0)")
        self._indent -= 1
        self._emit("if isinstance(x, (int, float)):")
        self._indent += 1
        self._emit("return self.make_real(float(x))")
        self._indent -= 1
        self._emit("if isinstance(x, str):")
        self._indent += 1
        self._emit("return self.embed(x)")
        self._indent -= 1
        self._emit("raise TypeError(f'cannot coerce {type(x).__name__} to a tensor for comparison')")
        self._indent -= 1
        self._emit()
        self._emit("# ---- Defuzzification — torch version ----")
        self._emit()
        self._emit("def _truth_projector(self):")
        self._indent += 1
        self._emit('"""Diagonal dim×dim projector onto truth axis. Cached tensor."""')
        self._emit("if not hasattr(self, '_truth_proj_cache') or self._truth_proj_cache is None:")
        self._indent += 1
        self._emit("M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)")
        self._emit("idx = self.semantic_dim + self.AXIS_TRUTH")
        self._emit("M[idx, idx] = 1.0")
        self._emit("self._truth_proj_cache = M")
        self._indent -= 1
        self._emit("return self._truth_proj_cache")
        self._indent -= 1
        self._emit()
        # defuzzify runtime method deleted in v0.3 step 4. The
        # `defuzzy(x)` source form is expanded inline by codegen.py's
        # `_defuzzy_expr_src` into ten nested eq calls (inherited
        # unchanged here).
        self._emit()
        self._emit("def make_random_rotation(self, angle, n_planes=1, seed=None):")
        self._indent += 1
        self._emit('"""Block-diagonal Haar rotation, scaled by fractional power.')
        self._emit('')
        self._emit("Seeded by numpy's RandomState for deterministic Haar-uniformity;")
        self._emit("the result is converted to a torch tensor on self.device. Used")
        self._emit("by eigenrotation loops.")
        self._emit('"""')
        self._emit("import numpy as _np_bridge")
        self._emit("rng = _np_bridge.random.RandomState(seed if seed is not None else self.seed)")
        self._emit("A = rng.randn(self.semantic_dim, self.semantic_dim)")
        self._emit("Q_sem_np, _ = _np_bridge.linalg.qr(A)")
        self._emit("w, V = _np_bridge.linalg.eig(Q_sem_np)")
        self._emit("phases = _np_bridge.angle(w) * (angle / _np_bridge.pi)")
        self._emit("R_sem_np = _np_bridge.real((V * _np_bridge.exp(1j * phases)) @ _np_bridge.linalg.inv(V))")
        self._emit("R_sem = _torch.as_tensor(R_sem_np, dtype=self.dtype, device=self.device)")
        self._emit("R = _torch.eye(self.dim, dtype=self.dtype, device=self.device)")
        self._emit("R[:self.semantic_dim, :self.semantic_dim] = R_sem")
        self._emit("return R")
        self._indent -= 1
        self._emit()
        self._emit("def compile_prototypes(self, prototype_vectors, frame_seed=None):")
        self._indent += 1
        self._emit("return dict(prototype_vectors)")
        self._indent -= 1
        self._emit()
        self._emit("def _step(self, state, R, target, halt_cum, k, threshold, eps=1e-12):")
        self._indent += 1
        self._emit('"""RNN cell: one branchless eigenrotation step (torch tensor ops)."""')
        self._emit("cand = R @ state")
        self._emit("cand = cand / (_torch.linalg.norm(cand) + eps)")
        self._emit("sim = _torch.dot(cand, target) / (_torch.linalg.norm(target) + eps)")
        self._emit("halt = 1.0 / (1.0 + _torch.exp(-k * (sim - threshold)))")
        self._emit("one = _torch.tensor(1.0, dtype=self.dtype, device=self.device)")
        self._emit("halt_cum = _torch.minimum(halt_cum + halt, one)")
        self._emit("state = (1.0 - halt_cum) * cand + halt_cum * state")
        self._emit("return state, halt_cum")
        self._indent -= 1
        self._emit()
        self._emit("def loop(self, initial_state, rotation, compiled_prototypes,")
        self._indent += 1
        self._emit("target_name=None, threshold=0.5, max_iters=50, k=20.0, frame_seed=None):")
        self._emit('"""Branchless RNN-style eigenrotation loop (torch backend).')
        self._emit('')
        self._emit("Same semantics as the numpy backend. T-step unroll, soft halt via")
        self._emit("sigmoid, output gating via AXIS_LOOP_DONE. Autograd-friendly:")
        self._emit("every op is differentiable with respect to state, target, threshold.")
        self._emit('"""')
        self._emit("state = initial_state.clone()")
        self._emit("halt_cum = _torch.tensor(0.0, dtype=self.dtype, device=self.device)")
        self._emit("iters_active = _torch.tensor(0.0, dtype=self.dtype, device=self.device)")
        self._emit("if target_name is not None:")
        self._indent += 1
        self._emit("target = compiled_prototypes[target_name]")
        self._indent -= 1
        self._emit("else:")
        self._indent += 1
        self._emit("target = next(iter(compiled_prototypes.values()))")
        self._indent -= 1
        self._emit("for _t in range(max_iters):")
        self._indent += 1
        self._emit("iters_active = iters_active + (1.0 - halt_cum)")
        self._emit("state, halt_cum = self._step(state, rotation, target, halt_cum, k, threshold)")
        self._indent -= 1
        self._emit("# Output gating: scale value axes by halt_cum; mark AXIS_LOOP_DONE.")
        self._emit("gated = state * halt_cum")
        self._emit("gated[self.semantic_dim + self.AXIS_LOOP_DONE] = halt_cum")
        self._emit("return target_name, gated, iters_active")
        self._indent -= 1
        self._indent -= 1
        self._emit()
        self._emit()
        self._emit(
            f"_VSA = _TorchVSA("
            f"semantic_dim={self._semantic_dim}, "
            f"synthetic_dim={self._synthetic_dim}, "
            f"seed={self.runtime_seed}, "
            f"llm_model={self._llm_model!r})"
        )
        if self._prefetch_strings:
            self._emit(f"_VSA.embed_batch({self._prefetch_strings!r})")
        self._emit()
        self._emit()
        self._emit("def _argmax_cosine(query, candidates):")
        self._indent += 1
        self._emit('"""Vectorized cosine argmax on torch tensors.')
        self._emit('')
        self._emit("Stacks candidates into (N, d), computes all N cosines as one")
        self._emit("matmul against the query, returns the candidate at the argmax.")
        self._emit("This is the GPU-shaped form: O(1) big kernel, not O(N) small ones.")
        self._emit('"""')
        self._emit("if not candidates:")
        self._indent += 1
        self._emit("return None")
        self._indent -= 1
        self._emit("M = _torch.stack([")
        self._indent += 1
        self._emit("_torch.as_tensor(c, dtype=_DTYPE, device=_DEVICE)")
        self._emit("for c in candidates")
        self._indent -= 1
        self._emit("])")
        self._emit("q = _torch.as_tensor(query, dtype=_DTYPE, device=_DEVICE)")
        self._emit("row_norms = _torch.linalg.norm(M, dim=1)")
        self._emit("q_norm = _torch.linalg.norm(q)")
        self._emit("if float(q_norm) == 0:")
        self._indent += 1
        self._emit("return candidates[0]")
        self._indent -= 1
        self._emit("safe_rn = _torch.where(row_norms > 0, row_norms, _torch.ones_like(row_norms))")
        self._emit("scores = (M @ q) / (safe_rn * q_norm)")
        self._emit("neg_inf = _torch.full_like(scores, float('-inf'))")
        self._emit("scores = _torch.where(row_norms > 0, scores, neg_inf)")
        self._emit("return candidates[int(_torch.argmax(scores).item())]")
        self._indent -= 1
        self._emit()
        self._emit()
        self._emit_select_helper()
        self._emit()
        self._emit("def _vector_map_lookup(pairs, key):")
        self._indent += 1
        self._emit('"""Identity-first lookup for vector-keyed maps, cosine fallback."""')
        self._emit("for k, v in pairs:")
        self._indent += 1
        self._emit("if k is key:")
        self._indent += 1
        self._emit("return v")
        self._indent -= 1
        self._indent -= 1
        self._emit("if not pairs:")
        self._indent += 1
        self._emit("return None")
        self._indent -= 1
        self._emit("keys = _torch.stack([")
        self._indent += 1
        self._emit("_torch.as_tensor(k, dtype=_DTYPE, device=_DEVICE)")
        self._emit("for k, _ in pairs")
        self._indent -= 1
        self._emit("])")
        self._emit("q = _torch.as_tensor(key, dtype=_DTYPE, device=_DEVICE)")
        self._emit("row_norms = _torch.linalg.norm(keys, dim=1)")
        self._emit("q_norm = _torch.linalg.norm(q)")
        self._emit("if float(q_norm) == 0:")
        self._indent += 1
        self._emit("return pairs[0][1]")
        self._indent -= 1
        self._emit("safe_rn = _torch.where(row_norms > 0, row_norms, _torch.ones_like(row_norms))")
        self._emit("scores = (keys @ q) / (safe_rn * q_norm)")
        self._emit("neg_inf = _torch.full_like(scores, float('-inf'))")
        self._emit("scores = _torch.where(row_norms > 0, scores, neg_inf)")
        self._emit("return pairs[int(_torch.argmax(scores).item())][1]")
        self._indent -= 1


def translate_module(module: ast.Module, **kwargs) -> str:
    """Translate a parsed Sutra module to self-contained torch Python.

    Same simplify + prefetch-collection pass as the numpy backend, so
    the torch backend benefits from every algebraic rewrite and the
    batched Ollama pre-fetch without duplicating that infrastructure.
    """
    from .simplify import simplify_module, collect_basis_vector_strings
    from .inliner import inline_stdlib_calls
    # Inline stdlib calls first — same pass as the CPU codegen uses.
    inline_stdlib_calls(module)
    simplify_module(module)
    strings = collect_basis_vector_strings(module)
    cg = PyTorchCodegen(**kwargs)
    cg._prefetch_strings = strings
    return cg.translate(module)
