"""AST -> pure-numpy Python source translator.

This is the demo-path backend. It emits self-contained Python modules
that depend only on numpy — no fly-brain imports, no spiking simulator,
no learned MBON readouts. VSA ops run as plain matrix operations on CPU.

The fly-brain backend (`codegen_flybrain.py`) stays for fly-brain-only
work. The demo path (what the paper points at, what fresh clones run)
goes through this file.

Design is a thin subclass of `FlyBrainCodegen`: the translator logic for
expressions, statements, loops, declarations is identical — only the
prelude changes. `snap` is not supported here (the demo substrate has no
cleanup circuit; programs that need `snap` should target the fly-brain
backend).
"""

from __future__ import annotations

from typing import List

from . import ast_nodes as ast
from .codegen_flybrain import FlyBrainCodegen, CodegenNotSupported


class NumpyCodegen(FlyBrainCodegen):
    """Emits a self-contained numpy-only module.

    Overrides the prelude and rejects `snap()` at codegen time. Everything
    else (function bodies, bind/bundle/unbind/similarity/argmax_cosine,
    map lookup, loop unrolling) is inherited unchanged.
    """

    def __init__(self, *, runtime_dim: int = 256, runtime_seed: int = 42) -> None:
        # Larger default dim than fly-brain (50) — numpy is cheap and
        # higher dim gives cleaner bind/unbind separation.
        super().__init__(
            runtime_dim=runtime_dim,
            runtime_seed=runtime_seed,
            runtime_n_kc=0,
            runtime_use_hemibrain=False,
        )

    # Ops not supported by the pure-numpy substrate. `snap` requires a
    # cleanup circuit (MB spiking model or equivalent); rotation-based
    # loop primitives need the same. Programs that use these should
    # target `codegen_flybrain` instead.
    _UNSUPPORTED_BUILTINS = frozenset({
        "snap",
        "make_rotation",
        "compile_prototypes",
        "geometric_loop",
    })

    def _translate_call(self, call: ast.Call) -> str:
        callee = call.callee
        if isinstance(callee, ast.Identifier):
            if callee.name in self._UNSUPPORTED_BUILTINS:
                raise CodegenNotSupported(
                    call,
                    f"`{callee.name}` is not supported on the pure-numpy "
                    f"substrate; use the fly-brain backend if you need it",
                )
        return super()._translate_call(call)

    def _emit_prelude(self) -> None:
        self._emit('"""Generated by sutra_compiler.codegen_numpy. Do not edit by hand."""')
        self._emit("from __future__ import annotations")
        self._emit()
        self._emit("import numpy as _np")
        self._emit()
        self._emit()
        self._emit("class _NumpyVSA:")
        self._indent += 1
        self._emit('"""Pure-numpy VSA runtime. Sign-flip binding, normalized bundle."""')
        self._emit()
        self._emit("def __init__(self, dim, seed):")
        self._indent += 1
        self._emit("self.dim = dim")
        self._emit("self.seed = seed")
        self._emit("self._codebook = {}")
        self._indent -= 1
        self._emit()
        self._emit("def embed(self, name):")
        self._indent += 1
        self._emit("if name not in self._codebook:")
        self._indent += 1
        self._emit("h = hash(name) & 0x7fffffff")
        self._emit("rng = _np.random.RandomState((self.seed ^ h) & 0x7fffffff)")
        self._emit("v = rng.randn(self.dim)")
        self._emit("v = v / _np.linalg.norm(v)")
        self._emit("self._codebook[name] = v")
        self._indent -= 1
        self._emit("return self._codebook[name].copy()")
        self._indent -= 1
        self._emit()
        self._emit("def bind(self, a, b):")
        self._indent += 1
        self._emit("# Sign-flip binding (spec: permute -> sign_flip).")
        self._emit("return a * _np.sign(b)")
        self._indent -= 1
        self._emit()
        self._emit("def unbind(self, role, bound):")
        self._indent += 1
        self._emit("# Sign-flip is self-inverse: unbind(role, bind(role, x)) ~= x.")
        self._emit("return bound * _np.sign(role)")
        self._indent -= 1
        self._emit()
        self._emit("def bundle(self, *vectors):")
        self._indent += 1
        self._emit("s = _np.sum(vectors, axis=0)")
        self._emit("n = _np.linalg.norm(s)")
        self._emit("return s / n if n > 0 else s")
        self._indent -= 1
        self._emit()
        self._emit("def similarity(self, a, b):")
        self._indent += 1
        self._emit("na = _np.linalg.norm(a)")
        self._emit("nb = _np.linalg.norm(b)")
        self._emit("if na == 0 or nb == 0:")
        self._indent += 1
        self._emit("return 0.0")
        self._indent -= 1
        self._emit("return float(_np.dot(a, b) / (na * nb))")
        self._indent -= 1
        self._indent -= 1
        self._emit()
        self._emit()
        self._emit(
            f"_VSA = _NumpyVSA(dim={self.runtime_dim}, seed={self.runtime_seed})"
        )
        self._emit()
        self._emit()
        self._emit("def _argmax_cosine(query, candidates):")
        self._indent += 1
        self._emit('"""Candidate with the largest cosine similarity to query."""')
        self._emit("best = None")
        self._emit("best_score = float('-inf')")
        self._emit("for c in candidates:")
        self._indent += 1
        self._emit("s = _VSA.similarity(query, c)")
        self._emit("if s > best_score:")
        self._indent += 1
        self._emit("best_score = s")
        self._emit("best = c")
        self._indent -= 1
        self._indent -= 1
        self._emit("return best")
        self._indent -= 1
        self._emit()
        self._emit()
        self._emit_select_helper()
        self._emit()
        self._emit("def _vector_map_lookup(pairs, key):")
        self._indent += 1
        self._emit('"""Identity-first lookup for vector-keyed maps, cosine fallback."""')
        self._emit("for k, v in pairs:")
        self._indent += 1
        self._emit("if k is key:")
        self._indent += 1
        self._emit("return v")
        self._indent -= 1
        self._indent -= 1
        self._emit("best_v = None")
        self._emit("best_score = float('-inf')")
        self._emit("for k, v in pairs:")
        self._indent += 1
        self._emit("s = _VSA.similarity(key, k)")
        self._emit("if s > best_score:")
        self._indent += 1
        self._emit("best_score = s")
        self._emit("best_v = v")
        self._indent -= 1
        self._indent -= 1
        self._emit("return best_v")
        self._indent -= 1


def translate_module(module: ast.Module, **kwargs) -> str:
    """Translate a parsed Sutra module to self-contained numpy Python."""
    return NumpyCodegen(**kwargs).translate(module)
