"""OCaml → Sutra lowering pass.

Walks a tree-sitter-ocaml parse tree and emits Sutra (.su) source.
Modeled on `sutra-from-ts/sutra_from_ts/lower.py`.

Why OCaml first (per todo.md §"Multi-language transpiler frontends"):
Sutra is a purely functional language, so ML-family syntax — algebraic
data types, pattern matching, expression-oriented bodies — is the
closest structural match. The functional source languages transpile
*cleanly* where JS fights the substrate.

Scope today (MVP — this is the first frontend tick):

- Top-level `let name p1 p2 … = body` value definitions with ≥ 1
  parameter lower to Sutra `function` declarations. The OCaml entry
  convention `let main () = …` (a single `unit` parameter) lowers to a
  zero-argument `function … main()`.
- Parameters: plain `a` (untyped — defaults to `int`, see note below) or
  typed `(x : int)`. A trailing return-type annotation (`… : int = body`)
  is read when present, else the return type defaults to `int`.
- Expression bodies: infix arithmetic (`+ - * /` and the float forms
  `+. -. *. /.`), comparisons (`= <> < > <= >=`), variable references,
  integer/float literals, function application (`f a b` → `f(a, b)`),
  and parenthesised expressions.

Type inference is deliberately *not* attempted yet: OCaml is globally
Hindley–Milner inferred, and replicating that is a later item. The MVP
defaults unannotated parameters and return types to `int` (OCaml's `+`
family is int-only; `+.` is float), which is correct for the integer
arithmetic fixtures and explicit for everything else — annotate the
OCaml source to get other types until inference lands.

Anything outside this scope lowers to a `// UNSUPPORTED-*` Sutra comment
(or an inline `/* UNSUPPORTED-EXPR: … */`) so the caller can see exactly
what blocked translation, the same convention `sutra-from-ts` uses.
"""

from __future__ import annotations

import pathlib
from typing import Optional


_HEADER = (
    "// Generated by sutra-from-ocaml. See sdk/sutra-from-ocaml/README.md.\n"
    "\n"
)

# OCaml type constructor → Sutra type name. Unmapped constructors fall
# back to the MVP default (`int`); widen this table as fixtures need
# float/bool/string/record types.
_OCAML_TYPE_TO_SUTRA = {
    "int": "int",
    "float": "float",
    "bool": "bool",
    "string": "String",
    "unit": "void",
}

_DEFAULT_TYPE = "int"

# OCaml infix operator text → Sutra operator. The float-arithmetic forms
# (`+.` …) collapse onto the same Sutra arithmetic ops — Sutra's number
# axis is unified, so there is no separate float operator surface. OCaml
# structural `=` / `<>` become Sutra `==` / `!=`.
_OP_MAP = {
    "+": "+", "-": "-", "*": "*", "/": "/",
    "+.": "+", "-.": "-", "*.": "*", "/.": "/",
    "=": "==", "<>": "!=",
    "<": "<", ">": ">", "<=": "<=", ">=": ">=",
}


# Nullary variant constructors -> their integer tag, collected per
# `lower()` call. A variant `type color = Red | Green | Blue` becomes an
# enum carried by Sutra `int` (same as the TS enum->int mapping): Red=0,
# Green=1, Blue=2. Module-level because threading it through every
# `_lower_expression` recursion would be heavy churn; safe today because
# the OCaml `lower()` is single-pass and non-re-entrant (no imports yet).
# If OCaml gains module imports, move this onto a threaded context.
_CONSTRUCTORS: dict[str, int] = {}


def _node_text(node, source: bytes) -> str:
    return source[node.start_byte:node.end_byte].decode("utf-8")


def _normalize_number(text: str) -> str:
    """OCaml numeric literal text -> a literal Sutra's lexer accepts.

    Sutra's lexer takes decimal ints and floats only (it rejects `0xFF`,
    reading `0` then `xFF`). OCaml allows hex/octal/binary, `_` digit
    separators, and `l`/`L`/`n` width suffixes — normalize all of those to
    a plain decimal int, and floats to their `_`-stripped form. Anything
    we don't recognize is returned unchanged (so it surfaces visibly at
    compile time rather than being silently mangled)."""
    raw = text.replace("_", "")
    # Strip OCaml int width suffixes (int32 `l`, int64 `L`, nativeint `n`).
    if raw and raw[-1] in "lLn" and not raw.lower().startswith("0x"):
        raw = raw[:-1]
    low = raw.lower()
    try:
        if low.startswith("0x"):
            return str(int(raw, 16))
        if low.startswith("0o"):
            return str(int(raw, 8))
        if low.startswith("0b"):
            return str(int(raw, 2))
    except ValueError:
        return text
    # Hex with a trailing width suffix (e.g. `0xFFl`) — strip then convert.
    if low.startswith("0x") and low[-1] in "ln":
        try:
            return str(int(raw[:-1], 16))
        except ValueError:
            return text
    return raw


def _value_binding_type(body, source: bytes) -> str:
    """Best-effort type for an unannotated `let x = expr` value binding.
    OCaml is HM-inferred globally; we don't replicate that. We only
    distinguish the cases the substrate cares about: a float literal
    (`3.14`, `1e9`) or a float-operator infix (`a +. b`) -> `float`; a
    boolean -> `bool`; everything else falls back to the `int` default."""
    t = body.type
    if t == "number":
        txt = _node_text(body, source).lower()
        if "." in txt or ("e" in txt and not txt.startswith("0x")):
            return "float"
        return "int"
    if t == "boolean":
        return "bool"
    if t == "infix_expression":
        op = body.child_by_field_name("operator")
        if op is not None and _node_text(op, source) in {"+.", "-.", "*.", "/."}:
            return "float"
    return _DEFAULT_TYPE


def _is_identifier(name: str) -> bool:
    """True if `name` is a plain Sutra-safe identifier. OCaml binders like
    `()` (unit) or names carrying a `'` (prime) are not lowerable as a
    Sutra variable name."""
    if not name:
        return False
    if not (name[0].isalpha() or name[0] == "_"):
        return False
    return all(c.isalnum() or c == "_" for c in name)


def _blend(cond_src: str, then_src: str, else_src: str) -> str:
    """The Sutra strong-defuzz two-way blend used for both `if/then/else`
    and `match` cases: weight = (1 + truth_axis(defuzzy(cond)))/2;
    result = weight*then + (1-weight)*else. Each product term is fully
    parenthesised so a bare `* (atom)` never sits before an infix
    operator (which the Sutra parser would read as a cast — CastExpr)."""
    w = f"truth_axis(defuzzy({cond_src}))"
    return f"(((1 + {w}) * ({then_src})) + ((1 - {w}) * ({else_src}))) / 2"


def _is_type_node(node) -> bool:
    """True for the OCaml grammar's type-expression nodes (the things
    that show up as a return-type annotation or inside a typed_pattern)."""
    return node.type == "type_constructor_path" or node.type.endswith("_type")


def _map_type(type_node, source: bytes, record_types=frozenset()) -> str:
    if type_node is None:
        return _DEFAULT_TYPE
    text = _node_text(type_node, source).strip()
    if text in record_types:
        # A record type is carried by a Sutra Axon (the structural-typing
        # carrier), same as the TS interface->Axon mapping.
        return "Axon"
    return _OCAML_TYPE_TO_SUTRA.get(text, _DEFAULT_TYPE)


def _lower_expression(node, source: bytes) -> str:
    t = node.type
    if t == "number":
        return _normalize_number(_node_text(node, source))
    if t == "boolean":
        # OCaml `true` / `false` -> Sutra `true` / `false`.
        return _node_text(node, source)
    if t == "value_path":
        # A variable / function reference. MVP carries the path text
        # through verbatim (`a`, and later `Module.name`).
        return _node_text(node, source)
    if t == "parenthesized_expression":
        inner = node.named_children[0] if node.named_children else None
        return f"({_lower_expression(inner, source)})" if inner is not None else "()"
    if t == "prefix_expression":
        # `!r` dereferences a ref cell; on the substrate the cell IS the
        # Sutra local, so a read is just the variable. `-x` / `~-x` is
        # unary negation.
        opn = next((c for c in node.named_children
                    if c.type == "prefix_operator"), None)
        operand = next((c for c in node.named_children
                        if c.type != "prefix_operator"), None)
        op_text = _node_text(opn, source) if opn is not None else ""
        operand_src = _lower_expression(operand, source) if operand is not None else "0"
        if op_text == "!":
            return operand_src
        if op_text in ("-", "~-"):
            return f"-({operand_src})"
        return f"/* UNSUPPORTED-PREFIX: {op_text} */"
    if t == "infix_expression":
        left = node.child_by_field_name("left")
        op = node.child_by_field_name("operator")
        right = node.child_by_field_name("right")
        op_text = _node_text(op, source) if op is not None else "+"
        if op_text == ":=":
            # Assignment is a *statement* (`r := e` returns unit); it has
            # no value in expression position. Lowered by _lower_stmt_expr
            # inside a sequence; reaching here means it was used as a value.
            return "/* UNSUPPORTED-EXPR: assignment used as a value */"
        op_sutra = _OP_MAP.get(op_text, op_text)
        left_src = _lower_expression(left, source) if left is not None else "0"
        right_src = _lower_expression(right, source) if right is not None else "0"
        return f"{left_src} {op_sutra} {right_src}"
    if t == "application_expression":
        kids = node.named_children
        if not kids:
            return "/* UNSUPPORTED-APP: empty */"
        # OCaml `not x` is a function application; lower it to Sutra's
        # logical-negation operator `!(x)` rather than a call to an
        # undefined `not`.
        if (kids[0].type == "value_path"
                and _node_text(kids[0], source) == "not"
                and len(kids) == 2):
            return f"!({_lower_expression(kids[1], source)})"
        # `ref e` allocates a cell holding e; on the substrate the cell is
        # a plain Sutra local, so the allocation lowers to the initial
        # value e (the `let r = ref e` binding becomes `<ty> r = e;`).
        if (kids[0].type == "value_path"
                and _node_text(kids[0], source) == "ref"
                and len(kids) == 2):
            return _lower_expression(kids[1], source)
        fn_src = _lower_expression(kids[0], source)
        arg_srcs = [_lower_expression(a, source) for a in kids[1:]]
        return f"{fn_src}({', '.join(arg_srcs)})"
    if t == "if_expression":
        # OCaml `if c then a else b` is an *expression*. Lower it to the
        # same strong-defuzz blend the TS frontend uses for if/else:
        #   weight = (1 + truth_axis(defuzzy(c))) / 2
        #   result = weight * a + (1 - weight) * b
        # i.e. ((1 + truth_axis(defuzzy(c))) * a
        #       + (1 - truth_axis(defuzzy(c))) * b) / 2
        # When c defuzzes true (+1) the blend is a; false (-1) it is b;
        # at the midpoint it interpolates. Differentiable, fuzzy, no
        # host-side branch — the substrate decides. An `if c then a`
        # with no else is the implicit-zero-else form (OCaml types that
        # unit; we mirror the TS select-with-implicit-zero shape).
        cond = node.child_by_field_name("condition")
        then_c = None
        else_c = None
        for c in node.named_children:
            if c.type == "then_clause":
                then_c = c
            elif c.type == "else_clause":
                else_c = c
        cond_src = _lower_expression(cond, source) if cond is not None else "false"
        then_expr = (
            then_c.named_children[0]
            if then_c is not None and then_c.named_children else None
        )
        then_src = _lower_expression(then_expr, source) if then_expr is not None else "0"
        if else_c is not None and else_c.named_children:
            else_src = _lower_expression(else_c.named_children[0], source)
            return _blend(cond_src, then_src, else_src)
        # if without else: implicit-zero else.
        w = f"truth_axis(defuzzy({cond_src}))"
        return f"(((1 + {w}) * ({then_src}))) / 2"
    if t == "constructor_path":
        # A nullary variant constructor used as a value (`Green`) lowers
        # to its integer tag. Parameterised constructors (`Some x`) are
        # not enums and are not supported.
        cname = _node_text(node, source)
        if cname in _CONSTRUCTORS:
            return str(_CONSTRUCTORS[cname])
        return (f"/* UNSUPPORTED-EXPR: constructor {cname} "
                "(only nullary variants lower, as enum ints) */")
    if t == "match_expression":
        return _lower_match(node, source)
    if t == "field_get_expression":
        # `p.x` record field access. In OCaml this node ONLY appears for
        # record fields (module access parses as value_path), so no type
        # check is needed. Numeric fields must be decoded off the axon
        # number-axis with `.real()` — WITHOUT it, axon field reads come
        # back as the raw filler vector and arithmetic on them collapses
        # to ~0 on the substrate (measured 2026-06-05; the TS interface
        # path has the same latent runtime bug). MVP scope: numeric
        # record fields.
        obj = node.named_children[0] if node.named_children else None
        field = next(
            (c for c in node.named_children if c.type == "field_path"), None
        )
        obj_src = _lower_expression(obj, source) if obj is not None else "/* ? */"
        field_name = _node_text(field, source) if field is not None else ""
        return f'{obj_src}.item("{field_name}").real()'
    if t == "record_expression":
        # Building a record is multi-statement axon construction (Axon r;
        # r.add(...); …), only valid in body/statement position — handled
        # by _lower_body_to_statements. In a nested expression position we
        # have nowhere to emit the statements.
        return ("/* UNSUPPORTED-EXPR: record_expression must be a function "
                "body (nested record construction not supported) */")
    return f"/* UNSUPPORTED-EXPR: {t} */"


def _lower_match(node, source: bytes) -> str:
    """Lower `match scrut with k1 -> r1 | k2 -> r2 | _ -> rd` to a nested
    strong-defuzz blend — the same machinery as if/then/else, chained.
    MVP scope: integer-literal patterns plus a trailing `_` wildcard
    catch-all. Anything else (constructor / record / or- / guarded
    patterns, no final wildcard) lowers to an UNSUPPORTED marker rather
    than silently producing a non-exhaustive or wrong blend."""
    kids = node.named_children
    if not kids:
        return "/* UNSUPPORTED-MATCH: empty */"
    scrut_src = _lower_expression(kids[0], source)
    cases = [c for c in kids[1:] if c.type == "match_case"]
    if not cases:
        return "/* UNSUPPORTED-MATCH: no cases */"

    # (kind, test_or_None, result_src); kind in {"literal", "ctor", "wild"}
    parsed: list[tuple[str, Optional[str], str]] = []
    for c in cases:
        cc = c.named_children
        if len(cc) != 2:
            # A guarded case (`| p when g -> r`) or or-pattern has a
            # different child count — not handled.
            return "/* UNSUPPORTED-MATCH-CASE: guard/or-pattern not supported */"
        pat, res = cc[0], cc[1]
        res_src = _lower_expression(res, source)
        if pat.type == "number":
            parsed.append(("literal", f"{scrut_src} == {_node_text(pat, source)}", res_src))
        elif pat.type == "value_pattern" and _node_text(pat, source) == "_":
            parsed.append(("wild", None, res_src))
        elif pat.type == "constructor_path":
            cname = _node_text(pat, source)
            if cname not in _CONSTRUCTORS:
                return f"/* UNSUPPORTED-MATCH-PATTERN: unknown constructor {cname} */"
            parsed.append(("ctor", f"{scrut_src} == {_CONSTRUCTORS[cname]}", res_src))
        else:
            return f"/* UNSUPPORTED-MATCH-PATTERN: {pat.type} */"

    # The LAST case is the base/catch-all (its result is the innermost
    # else, its test dropped). Exact for `_` and for an exhaustive variant
    # match (every constructor listed). A trailing *integer-literal* case
    # is rejected — an int match without `_` is non-exhaustive.
    if parsed[-1][0] == "literal":
        return "/* UNSUPPORTED-MATCH: integer-literal match needs a trailing `_` wildcard */"
    for kind, _test, _res in parsed[:-1]:
        if kind == "wild":
            return "/* UNSUPPORTED-MATCH: wildcard `_` must be the last case */"

    expr = parsed[-1][2]
    for _kind, test, res in reversed(parsed[:-1]):
        expr = _blend(test, res, expr)
    return expr


def _lower_param(param_node, source: bytes,
                 record_types=frozenset()) -> Optional[tuple[str, str]]:
    """Lower one `parameter` node → (name, sutra_type), or None for the
    `unit` parameter (`let main () = …`), which contributes no Sutra
    parameter."""
    child = param_node.named_children[0] if param_node.named_children else None
    if child is None:
        return None
    if child.type == "unit":
        return None
    if child.type == "value_pattern":
        return (_node_text(child, source), _DEFAULT_TYPE)
    if child.type == "typed_pattern":
        vp = None
        tp = None
        for c in child.named_children:
            if c.type == "value_pattern":
                vp = c
            elif _is_type_node(c):
                tp = c
        name = _node_text(vp, source) if vp is not None else "_arg"
        ptype = _map_type(tp, source, record_types) if tp is not None else _DEFAULT_TYPE
        return (name, ptype)
    # Other pattern kinds (tuple / constructor destructuring) are a later
    # item; carry the name through as an int-typed param for now.
    return (_node_text(child, source), _DEFAULT_TYPE)


def _lower_record_body(body, source: bytes, indent: str) -> str:
    """Lower a `record_expression` function body `{ f1 = e1; … }` to Sutra
    axon construction: `Axon _record; _record.add("f1", e1); …; return
    _record;`. Mirrors the TS object-literal->axon lowering."""
    lines = f"{indent}Axon _record;\n"
    for fe in body.named_children:
        if fe.type != "field_expression":
            continue
        fp = next((c for c in fe.named_children if c.type == "field_path"), None)
        val = next((c for c in fe.named_children if c.type != "field_path"), None)
        fname = _node_text(fp, source) if fp is not None else ""
        val_src = _lower_expression(val, source) if val is not None else "0"
        lines += f'{indent}_record.add("{fname}", {val_src});\n'
    lines += f"{indent}return _record;\n"
    return lines


def _lower_local_binding(vd, source: bytes, indent: str,
                         record_types=frozenset()) -> str:
    """Lower one `value_definition` from a `let … in` into a Sutra local
    declaration (`<type> name = <expr>;`). OCaml `let` is immutable, so
    no `slot`. A *local function* binding (params present) can't nest in
    Sutra — emit an UNSUPPORTED marker rather than broken output."""
    lb = None
    for c in vd.named_children:
        if c.type == "let_binding":
            lb = c
            break
    if lb is None or not lb.named_children:
        return f"{indent}// UNSUPPORTED-LOCAL-BINDING: malformed\n"
    kids = lb.named_children
    name = _node_text(kids[0], source)
    if any(k.type == "parameter" for k in kids[1:-1]):
        return (
            f"{indent}// UNSUPPORTED-LOCAL-FN: nested function '{name}' "
            "(Sutra has no nested function declarations)\n"
        )
    value = kids[-1]
    ret_type = None
    for k in kids[1:-1]:
        if _is_type_node(k):
            ret_type = _map_type(k, source, record_types)
    ty = ret_type if ret_type is not None else _DEFAULT_TYPE
    return f"{indent}{ty} {name} = {_lower_expression(value, source)};\n"


def _lower_stmt_expr(node, source: bytes, indent: str) -> str:
    """Lower one side-effecting expression in STATEMENT position (a
    non-final element of a sequence `e1; e2; …`). The common imperative
    case is a ref assignment `r := e` -> Sutra `r = e;`; anything else
    (e.g. a call evaluated for its effect) lowers to a bare expression
    statement `expr;`."""
    if node.type == "infix_expression":
        op = node.child_by_field_name("operator")
        if op is not None and _node_text(op, source) == ":=":
            left = node.child_by_field_name("left")
            right = node.child_by_field_name("right")
            lhs = _lower_expression(left, source) if left is not None else "_"
            rhs = _lower_expression(right, source) if right is not None else "0"
            return f"{indent}{lhs} = {rhs};\n"
    return f"{indent}{_lower_expression(node, source)};\n"


def _lower_body_to_statements(body, source: bytes, indent: str,
                              record_types=frozenset()) -> str:
    """Lower a function-body expression into Sutra statements. A
    `let x = e in rest` becomes a local declaration followed by the
    lowering of `rest`; a `sequence_expression` (`e1; …; eN`) becomes
    statements for `e1 … e(N-1)` and the lowering of `eN`; a
    `record_expression` body becomes axon construction; the final
    (non-let) expression becomes `return …;`."""
    if body.type == "record_expression":
        return _lower_record_body(body, source, indent)
    if body.type == "let_expression":
        kids = body.named_children
        if len(kids) >= 2:
            *bindings, in_body = kids
            out = ""
            for b in bindings:
                if b.type == "value_definition":
                    out += _lower_local_binding(b, source, indent, record_types)
                else:
                    out += f"{indent}// UNSUPPORTED-LET-IN-PART: {b.type}\n"
            out += _lower_body_to_statements(in_body, source, indent, record_types)
            return out
    if body.type == "sequence_expression":
        kids = body.named_children
        if kids:
            *stmts, last = kids
            out = ""
            for s in stmts:
                out += _lower_stmt_expr(s, source, indent)
            out += _lower_body_to_statements(last, source, indent, record_types)
            return out
    return f"{indent}return {_lower_expression(body, source)};\n"


# Sutra comparison operator → its logical negation. Used to turn an
# OCaml halt-condition (`if n = 0 then base else recurse`) into the
# loop's *continue* condition.
_NEG_CMP = {"==": "!=", "!=": "==", "<": ">=", ">": "<=", "<=": ">", ">=": "<"}


def _self_call_args(node, name: str, arity: int, source: bytes):
    """If `node` is exactly `name arg1 … arg{arity}` (a self-application
    at the right arity), return the list of arg nodes; else None."""
    if node.type != "application_expression":
        return None
    kids = node.named_children
    if not kids:
        return None
    fn = kids[0]
    if fn.type != "value_path" or _node_text(fn, source) != name:
        return None
    args = kids[1:]
    if len(args) != arity:
        return None
    return args


def _negate_cond(cond, source: bytes) -> Optional[str]:
    """Negate a simple infix-comparison condition (return the Sutra
    source of its logical negation), or None if it is not a single
    comparison the MVP can invert."""
    if cond is None or cond.type != "infix_expression":
        return None
    op = cond.child_by_field_name("operator")
    left = cond.child_by_field_name("left")
    right = cond.child_by_field_name("right")
    if op is None or left is None or right is None:
        return None
    sutra_op = _OP_MAP.get(_node_text(op, source))
    neg = _NEG_CMP.get(sutra_op) if sutra_op else None
    if neg is None:
        return None
    return f"{_lower_expression(left, source)} {neg} {_lower_expression(right, source)}"


def _try_lower_tail_recursive(
    name: str, params: list[tuple[str, str]], ret: str, body, source: bytes,
) -> Optional[str]:
    """Try to lower a TAIL-recursive `let rec` of the accumulator shape
    `let rec f p1 … pk = if COND then BASE else f a1 … ak` (or with the
    self-call in the THEN branch) to a Sutra declared `while_loop`. The
    recursion becomes bounded substrate iteration — no self-calling
    function (which would not terminate through the fuzzy-if blend).
    Returns the emitted Sutra (loop decl + function) or None if the body
    is not this exact shape (caller then falls back to UNSUPPORTED).

    Verified on the substrate: `let rec sum_to acc n = if n = 0 then acc
    else sum_to (acc + n) (n - 1)` with `sum_to 0 5` decodes to 15."""
    if body.type != "if_expression":
        return None
    cond = body.child_by_field_name("condition")
    then_c = else_c = None
    for c in body.named_children:
        if c.type == "then_clause":
            then_c = c
        elif c.type == "else_clause":
            else_c = c
    if then_c is None or else_c is None or not then_c.named_children \
            or not else_c.named_children:
        return None
    then_e = then_c.named_children[0]
    else_e = else_c.named_children[0]
    arity = len(params)
    then_args = _self_call_args(then_e, name, arity, source)
    else_args = _self_call_args(else_e, name, arity, source)
    # Exactly ONE branch must be the self-call (the other is the base).
    if (then_args is None) == (else_args is None):
        return None
    if else_args is not None:
        cont = _negate_cond(cond, source)  # halt when COND, loop while not
        rec_args, base = else_args, then_e
    else:
        cont = _lower_expression(cond, source)  # loop while COND
        rec_args, base = then_args, else_e
    if cont is None:
        return None

    loop_name = f"_rec_{name}"
    state_decls = ", ".join(f"{ty} {nm} = 0" for nm, ty in params)
    # Simultaneous state update via temporaries: compute every new value
    # from the OLD params first (`T _ti = e_i;`), then assign all params
    # (`p_i = _ti;`). A naive sequential `p1 = e1; p2 = e2;` is wrong when
    # a later arg reads a param an earlier line already overwrote — e.g. a
    # swap `f y x` (measured: `swaploop 7 9 2` gave 9 instead of 7).
    temp_decls = "".join(
        f"    {ty} _t{i} = {_lower_expression(arg, source)};\n"
        for i, ((_nm, ty), arg) in enumerate(zip(params, rec_args))
    )
    assigns = "".join(f"    {nm} = _t{i};\n" for i, (nm, _ty) in enumerate(params))
    body_lines = temp_decls + assigns
    loop_decl = f"while_loop {loop_name}({cont}, {state_decls}) {{\n{body_lines}}}\n"

    slot_lines = "".join(f"    slot {ty} _{nm}_r = {nm};\n" for nm, ty in params)
    slot_args = ", ".join(f"_{nm}_r" for nm, _ty in params)
    writeback = "".join(f"    {nm} = _{nm}_r;\n" for nm, _ty in params)
    params_src = ", ".join(f"{ty} {nm}" for nm, ty in params)
    base_src = _lower_expression(base, source)
    fn = (
        f"function {ret} {name}({params_src}) {{\n"
        f"{slot_lines}"
        f"    loop {loop_name}({cont}, {slot_args});\n"
        f"{writeback}"
        f"    return {base_src};\n"
        f"}}\n"
    )
    return loop_decl + fn


def _lower_let_binding(lb, source: bytes, record_types=frozenset(),
                       is_rec: bool = False) -> str:
    kids = lb.named_children
    if not kids:
        return "// UNSUPPORTED-LET: empty let_binding\n"
    name = _node_text(kids[0], source)
    body = kids[-1]
    middle = kids[1:-1]

    has_param = any(k.type == "parameter" for k in middle)
    if not has_param:
        # A zero-parameter `let x = expr` is a value binding, not a
        # function. Lower it to a Sutra top-level constant
        # `<ty> <name> = <expr>;` — top-level var decls are visible inside
        # functions on the substrate (verified). Only simple, lowerable
        # bodies qualify; sequences / refs / the `let () = …` entry point
        # have no `name`-shaped binder or no single-expression body, so
        # they stay UNSUPPORTED rather than emit a footgun.
        if is_rec:
            return (
                f"// UNSUPPORTED-LET-REC: value binding '{name}' "
                "(recursive value, not a function)\n"
            )
        if not _is_identifier(name):
            return (
                f"// UNSUPPORTED-LET: value binding '{name}' "
                "(binder is not a plain identifier)\n"
            )
        # A type annotation (`let x : int = …`) overrides the inferred type.
        ann_type = next((_map_type(k, source, record_types)
                         for k in middle if _is_type_node(k)), None)
        expr_src = _lower_expression(body, source)
        if "UNSUPPORTED" in expr_src:
            return (
                f"// UNSUPPORTED-LET: value binding '{name}' "
                f"(body does not lower to a simple expression: {body.type})\n"
            )
        ty = ann_type if ann_type is not None else _value_binding_type(body, source)
        return f"{ty} {name} = {expr_src};\n"

    params: list[tuple[str, str]] = []
    ret_type: Optional[str] = None
    for k in middle:
        if k.type == "parameter":
            p = _lower_param(k, source, record_types)
            if p is not None:
                params.append(p)
        elif _is_type_node(k):
            ret_type = _map_type(k, source, record_types)
    ret = ret_type if ret_type is not None else _DEFAULT_TYPE

    if is_rec:
        # `let rec` is general recursion. Sutra's if/else is a defuzz
        # BLEND that evaluates BOTH branches unconditionally, so a
        # self-calling function never terminates on the substrate.
        # TAIL recursion of the accumulator shape lowers to a bounded
        # Sutra `while_loop` instead (substrate-verified). Anything that
        # is NOT that shape (non-tail recursion like factorial, or a
        # non-comparison halt condition) we surface as UNSUPPORTED rather
        # than emit a runtime footgun.
        tail = _try_lower_tail_recursive(name, params, ret, body, source)
        if tail is not None:
            return tail
        return (
            f"// UNSUPPORTED-LET-REC: recursive function '{name}' is not the "
            "tail-recursive accumulator shape; Sutra's fuzzy if/else evaluates "
            "both branches, so general recursion does not terminate — needs a "
            "loop/recur encoding (queue.md Transpiler track)\n"
        )

    params_src = ", ".join(f"{ty} {nm}" for nm, ty in params)
    body_src = _lower_body_to_statements(body, source, "    ", record_types)
    return f"function {ret} {name}({params_src}) {{\n{body_src}}}\n"


def lower(source: str, source_path: Optional[pathlib.Path] = None) -> str:
    """Top-level entry point. OCaml source string → Sutra source string.

    `source_path` is accepted for harness parity with `sutra-from-ts`
    (where it drives import resolution); the OCaml MVP has no module
    handling yet, so it is currently unused.
    """
    import tree_sitter
    import tree_sitter_ocaml as tso

    lang = tree_sitter.Language(tso.language_ocaml())
    parser = tree_sitter.Parser(lang)
    src_bytes = source.encode("utf-8")
    tree = parser.parse(src_bytes)

    # Prepass: collect record type names so record-typed params map to a
    # Sutra Axon. `type X = { … }` parses as
    # type_definition > type_binding > type_constructor (X) +
    # record_declaration.
    record_types: set[str] = set()
    _CONSTRUCTORS.clear()
    for child in tree.root_node.named_children:
        if child.type != "type_definition":
            continue
        for tb in child.named_children:
            if tb.type != "type_binding":
                continue
            tc = next(
                (c for c in tb.named_children if c.type == "type_constructor"), None
            )
            rd = next(
                (c for c in tb.named_children if c.type == "record_declaration"), None
            )
            if tc is not None and rd is not None:
                record_types.add(_node_text(tc, src_bytes))
            # Variant `type X = A | B | …` -> nullary constructors become
            # enum tags (A=0, B=1, …). The tag index advances for every
            # constructor (preserving OCaml's order) but only nullary
            # ones are mapped; a parameterised constructor (`C of t`) is
            # left out, so using it lowers to UNSUPPORTED.
            vd = next(
                (c for c in tb.named_children if c.type == "variant_declaration"), None
            )
            if vd is not None:
                idx = 0
                for cd in vd.named_children:
                    if cd.type != "constructor_declaration":
                        continue
                    names = cd.named_children
                    cn = next(
                        (c for c in names if c.type == "constructor_name"), None
                    )
                    if cn is not None and len(names) == 1:
                        _CONSTRUCTORS[_node_text(cn, src_bytes)] = idx
                    idx += 1

    out: list[str] = [_HEADER]
    for child in tree.root_node.named_children:
        if child.type == "value_definition":
            # `let rec` carries the `rec` keyword as an anonymous token;
            # detect it from the leading tokens so the recursion guard
            # in _lower_let_binding fires.
            toks = _node_text(child, src_bytes).split(None, 2)
            is_rec = len(toks) >= 2 and toks[0] == "let" and toks[1] == "rec"
            for lb in child.named_children:
                if lb.type == "let_binding":
                    out.append(
                        _lower_let_binding(lb, src_bytes, record_types, is_rec=is_rec)
                    )
        elif child.type == "type_definition":
            # Erased — the record type name was collected in the prepass;
            # the declaration emits nothing (like a TS interface).
            continue
        elif child.type == "comment":
            continue
        else:
            out.append(f"// UNSUPPORTED-TOPLEVEL: {child.type}\n")
    return "".join(out)
