"""OCaml → Sutra lowering pass.

Walks a tree-sitter-ocaml parse tree and emits Sutra (.su) source.
Modeled on `sutra-from-ts/sutra_from_ts/lower.py`.

Why OCaml first (per todo.md §"Multi-language transpiler frontends"):
Sutra is a purely functional language, so ML-family syntax — algebraic
data types, pattern matching, expression-oriented bodies — is the
closest structural match. The functional source languages transpile
*cleanly* where JS fights the substrate.

Scope today (MVP — this is the first frontend tick):

- Top-level `let name p1 p2 … = body` value definitions with ≥ 1
  parameter lower to Sutra `function` declarations. The OCaml entry
  convention `let main () = …` (a single `unit` parameter) lowers to a
  zero-argument `function … main()`.
- Parameters: plain `a` (untyped — defaults to `int`, see note below) or
  typed `(x : int)`. A trailing return-type annotation (`… : int = body`)
  is read when present, else the return type defaults to `int`.
- Expression bodies: infix arithmetic (`+ - * /` and the float forms
  `+. -. *. /.`), comparisons (`= <> < > <= >=`), variable references,
  integer/float literals, function application (`f a b` → `f(a, b)`),
  and parenthesised expressions.

Type inference is deliberately *not* attempted yet: OCaml is globally
Hindley–Milner inferred, and replicating that is a later item. The MVP
defaults unannotated parameters and return types to `int` (OCaml's `+`
family is int-only; `+.` is float), which is correct for the integer
arithmetic fixtures and explicit for everything else — annotate the
OCaml source to get other types until inference lands.

Anything outside this scope lowers to a `// UNSUPPORTED-*` Sutra comment
(or an inline `/* UNSUPPORTED-EXPR: … */`) so the caller can see exactly
what blocked translation, the same convention `sutra-from-ts` uses.
"""

from __future__ import annotations

import pathlib
from typing import Optional


_HEADER = (
    "// Generated by sutra-from-ocaml. See sdk/sutra-from-ocaml/README.md.\n"
    "\n"
)

# OCaml type constructor → Sutra type name. Unmapped constructors fall
# back to the MVP default (`int`); widen this table as fixtures need
# float/bool/string/record types.
_OCAML_TYPE_TO_SUTRA = {
    "int": "int",
    "float": "float",
    "bool": "bool",
    "string": "String",
    "unit": "void",
}

_DEFAULT_TYPE = "int"

# OCaml infix operator text → Sutra operator. The float-arithmetic forms
# (`+.` …) collapse onto the same Sutra arithmetic ops — Sutra's number
# axis is unified, so there is no separate float operator surface. OCaml
# structural `=` / `<>` become Sutra `==` / `!=`; `mod` → Sutra `%`
# (truncated remainder, `_VSA.fmod`); `&&` / `||` carry through to Sutra's
# fuzzy three-valued logical operators. An operator NOT in this table
# lowers to an UNSUPPORTED marker (NOT passed through verbatim — e.g. the
# bitwise/shift ops `land lor lxor lsl lsr asr` have no Sutra operator and
# need a substrate bitwise stdlib; the string/list ops `^` `@` need their
# own handling). Passing an unknown operator through produced invalid Sutra.
_OP_MAP = {
    "+": "+", "-": "-", "*": "*", "/": "/",
    "+.": "+", "-.": "-", "*.": "*", "/.": "/",
    "=": "==", "<>": "!=",
    "<": "<", ">": ">", "<=": "<=", ">=": ">=",
    "mod": "%", "&&": "&&", "||": "||",
}

# OCaml bitwise operators -> the substrate Bits stdlib (stdlib/bitwise.su).
# Sutra has no bitwise operator; these are 32-bit, non-negative. Shifts
# (`lsl`/`lsr`) are handled separately as arithmetic identities.
_BITWISE_FN = {"land": "Bits.band", "lor": "Bits.bor", "lxor": "Bits.bxor"}


# Nullary variant constructors -> their integer tag, collected per
# `lower()` call. A variant `type color = Red | Green | Blue` becomes an
# enum carried by Sutra `int` (same as the TS enum->int mapping): Red=0,
# Green=1, Blue=2. Module-level because threading it through every
# `_lower_expression` recursion would be heavy churn; safe today because
# the OCaml `lower()` is single-pass and non-re-entrant (no imports yet).
# If OCaml gains module imports, move this onto a threaded context.
_CONSTRUCTORS: dict[str, int] = {}

# Parameterised-variant constructors. A variant type with ANY constructor that
# carries an argument (`C of t`) uses a UNIFORM tagged-axon `{_tag, _val}`
# representation for ALL its constructors (nullary ones store `_val`=0) —
# generalizing the built-in option `Some/None` path. `_VARIANT_CTORS` maps each
# such constructor name -> (tag, arity in {0,1}). A variant with ONLY nullary
# constructors stays enum-int (`_CONSTRUCTORS`); its names are NOT added here.
# MVP: single-argument constructors and numeric payloads (string payloads are
# out — strings are not axon fillers, Emma 2026-06-08).
_VARIANT_CTORS: dict = {}

# Hoisted `while_loop` declarations collected while lowering function
# bodies. A Sutra loop is a top-level declaration, but an OCaml `while`
# is discovered deep inside a body — so we emit a uniquely-named
# `while_loop` decl into this list and prepend them all (after the header,
# before the functions) in `lower()`. Same module-level / single-pass
# caveat as `_CONSTRUCTORS`. The next loop's index is `len(_HOISTED_LOOPS)`.
_HOISTED_LOOPS: list[str] = []

# Hoisted top-level function declarations from CLOSED nested functions
# (`let f x = … in …`). Sutra has no nested functions, so a closed one
# (free vars ⊆ its params ∪ top-level names) is lifted to a sibling
# `function`. Prepended in `lower()` alongside `_HOISTED_LOOPS`.
_HOISTED_DECLS: list[str] = []

# Names bound at top level (functions + value bindings), collected in the
# `lower()` prepass. Used to decide whether a nested function is closed
# (a free var that is a top-level name is fine; one that is an enclosing
# local is a capture we don't support yet).
_TOPLEVEL_NAMES: set = set()

# Top-level functions whose return type is `Axon` (record/tuple/option body
# or an Axon-mapping return annotation), collected in the `lower()` prepass.
# A local bound to a call of one of these is itself typed `Axon`, so a
# subsequent field/projection access (`p.x`, `fst p`) dispatches to the axon
# accessor instead of clashing with torch's tensor `.item()`.
_AXON_RETURNING: set = set()

# OCaml array/bytes allocations split per ACCESS PATTERN (Emma 2026-06-13):
#   - An array touched INSIDE a `while` loop (a vector accumulator carried across
#     iterations, e.g. the attention-on-RAM `acc`) -> the global RAM device. The
#     while->loop substrate transform carries only SCALAR slots, so a vector store
#     mutated across iterations must live in RAM (ram-pointers.md / the
#     attention-on-RAM O2 finding). `_RAM_ARRAYS` maps name -> compile-time base
#     (spaced by `_RAM_STRIDE`); `a.(i)` -> ramRead(base+i), `a.(i) <- v` ->
#     ramWrite. `Bytes.make` (raw linear-memory shape) is always RAM.
#   - A STRAIGHT-LINE `Array.make` array (no loop access) -> a per-instance
#     `dict<int,int>` int-dict local (preallocated synthetic-space slots; exact,
#     no global-device aliasing — FIXED 2026-06-13). `a.(i)` -> `a[i]`,
#     `a.(i) <- v` -> `a[i] = v`. `_INT_DICT_ARRAYS` is the set of such names.
# This is the principled discriminator: the loop-carried-vector constraint is
# exactly why the attn parsers need RAM; ordinary arrays don't and get the exact
# per-instance object. No need to touch the (hard) attention-on-RAM parsers.
_RAM_ARRAYS: dict = {}
_RAM_STRIDE = 4096
_INT_DICT_ARRAYS: set = set()


def _array_alloc_kind(value, source: bytes):
    """'array' for `Array.make`/`Array.create`, 'bytes' for `Bytes.make`, else
    None. `Bytes` is always RAM; `Array` chooses RAM vs int-dict by access."""
    if value is None or value.type != "application_expression":
        return None
    head = value.named_children[0] if value.named_children else None
    if head is None or head.type != "value_path":
        return None
    name = _node_text(head, source)
    if name in ("Array.make", "Array.create"):
        return "array"
    if name == "Bytes.make":
        return "bytes"
    return None


def _is_array_alloc(value, source: bytes) -> bool:
    """True if `value` is any array/bytes allocation."""
    return _array_alloc_kind(value, source) is not None


def _enclosing_definition(node):
    """Walk up to the outermost ancestor below the compilation unit (a top-level
    definition) — the scope to scan for an array's loop access."""
    n = node
    while n.parent is not None and n.parent.type not in ("compilation_unit", "source"):
        n = n.parent
    return n


def _array_loop_accessed(name: str, scope, source: bytes) -> bool:
    """True if `name` is read/written via `a.(i)` ANYWHERE inside a `while` loop
    within `scope` — the loop-carried-vector pattern that requires RAM."""
    def walk(n, in_loop: bool) -> bool:
        if in_loop and n.type == "array_get_expression":
            kids = n.named_children
            arr = kids[0] if kids else None
            if arr is not None and _node_text(arr, source) == name:
                return True
        nl = in_loop or n.type == "while_expression"
        return any(walk(c, nl) for c in n.named_children)
    return walk(scope, False)

# Active name -> Sutra-source substitutions for the body of a `match` arm
# that binds a name (a catch-all `| x -> …` binds the scrutinee to `x`).
# `match` lowers to a defuzz-blend *expression*, which can't introduce a
# Sutra statement-level local, so the bound name is substituted into the
# arm body at `value_path` sites. Module-level (single-pass, non-reentrant)
# with explicit save/restore in `_lower_match` for nested matches.
_MATCH_SUBST: dict = {}

# Maps a tree-sitter node `.id` -> a temp-var name, for aggregate-literal call
# arguments (record / tuple / variant construction) that were hoisted to a temp
# Axon BEFORE the enclosing return expression. When `_lower_expression` reaches
# such a node it emits the temp name instead of the (unsupported) inline literal.
# Lets `f {..} + g {..}` work: the aggregates hoist, the call sites reference the
# temps. Populated + cleared per return-expression by `_hoist_aggregate_args_deep`.
_ARG_HOIST: dict = {}

# Sentinel for "key absent" in save/restore (distinct from a real None value).
_MISSING = object()


def _value_paths(node, source: bytes) -> set:
    """All `value_path` identifiers appearing anywhere under `node`."""
    out: set = set()

    def walk(n):
        if n.type == "value_path":
            out.add(_node_text(n, source))
        for c in n.named_children:
            walk(c)

    walk(node)
    return out


def _fn_returns_axon(lb, source: bytes, record_types) -> bool:
    """True if a `let_binding` defines a FUNCTION whose return type is Axon
    — an Axon-mapping return annotation, or a record / tuple / option body.
    Used to type local bindings of such calls as `Axon`."""
    kids = lb.named_children
    if not kids or not any(k.type == "parameter" for k in kids[1:-1]):
        return False
    for k in kids[1:-1]:
        if _is_type_node(k) and _map_type(k, source, record_types) == "Axon":
            return True
    body = kids[-1]
    if body.type == "record_expression":
        return True
    ub = _unwrap_parens(body)
    if ub is not None and (ub.type == "tuple_expression"
                           or _option_kind(ub, source) is not None
                           or _variant_value_kind(ub, source) is not None):
        return True
    return False


def _collect_ref_vars(node, source: bytes, refs: dict) -> list:
    """Return the in-scope mutable refs (by declaration order in `refs`)
    that appear as a `value_path` anywhere under `node`. These are the
    recurrent state a `while` body reads/writes, which must be threaded
    through the Sutra loop as state params."""
    seen: set = set()

    def walk(n):
        if n.type == "value_path":
            nm = _node_text(n, source)
            if nm in refs:
                seen.add(nm)
        for c in n.named_children:
            walk(c)

    walk(node)
    # Preserve `refs` insertion order (declaration order) for stable output.
    return [nm for nm in refs if nm in seen]


def _node_text(node, source: bytes) -> str:
    return source[node.start_byte:node.end_byte].decode("utf-8")


def _normalize_number(text: str) -> str:
    """OCaml numeric literal text -> a literal Sutra's lexer accepts.

    Sutra's lexer takes decimal ints and floats only (it rejects `0xFF`,
    reading `0` then `xFF`). OCaml allows hex/octal/binary, `_` digit
    separators, and `l`/`L`/`n` width suffixes — normalize all of those to
    a plain decimal int, and floats to their `_`-stripped form. Anything
    we don't recognize is returned unchanged (so it surfaces visibly at
    compile time rather than being silently mangled)."""
    raw = text.replace("_", "")
    # Strip OCaml int width suffixes (int32 `l`, int64 `L`, nativeint `n`).
    if raw and raw[-1] in "lLn" and not raw.lower().startswith("0x"):
        raw = raw[:-1]
    low = raw.lower()
    try:
        if low.startswith("0x"):
            return str(int(raw, 16))
        if low.startswith("0o"):
            return str(int(raw, 8))
        if low.startswith("0b"):
            return str(int(raw, 2))
    except ValueError:
        return text
    # Hex with a trailing width suffix (e.g. `0xFFl`) — strip then convert.
    if low.startswith("0x") and low[-1] in "ln":
        try:
            return str(int(raw[:-1], 16))
        except ValueError:
            return text
    return raw


_CHAR_ESCAPES = {
    "n": 10, "t": 9, "r": 13, "b": 8, "\\": 92, "'": 39, '"': 34, " ": 32,
}


def _char_codepoint(content: str) -> Optional[int]:
    """OCaml `character_content` (the text inside `'…'`) -> its codepoint
    integer. OCaml chars are bytes; the ISO-5 stack machine uses them as
    such (`Char.code`, `land 0xff`, byte stores), so a char literal lowers
    to its codepoint. Handles the named escapes, `\\ddd` (decimal) and
    `\\xHH` (hex). Returns None if it can't decode (caller emits UNSUPPORTED)."""
    if content == "":
        return None
    if content[0] != "\\":
        return ord(content[0])
    rest = content[1:]
    if not rest:
        return None
    if rest[0] in _CHAR_ESCAPES and len(rest) == 1:
        return _CHAR_ESCAPES[rest[0]]
    if rest[0] == "x":
        try:
            return int(rest[1:], 16)
        except ValueError:
            return None
    if rest.isdigit():
        try:
            return int(rest)
        except ValueError:
            return None
    return None


def _value_binding_type(body, source: bytes) -> str:
    """Best-effort type for an unannotated `let x = expr` value binding.
    OCaml is HM-inferred globally; we don't replicate that. We only
    distinguish the cases the substrate cares about: a float literal
    (`3.14`, `1e9`) or a float-operator infix (`a +. b`) -> `float`; a
    boolean -> `bool`; everything else falls back to the `int` default."""
    t = body.type
    if t == "number":
        txt = _node_text(body, source).lower()
        if "." in txt or ("e" in txt and not txt.startswith("0x")):
            return "float"
        return "int"
    if t == "boolean":
        return "bool"
    if t == "string":
        return "String"
    if t == "character":
        return "int"  # a char lowers to its codepoint int
    if t == "infix_expression":
        op = body.child_by_field_name("operator")
        if op is not None and _node_text(op, source) in {"+.", "-.", "*.", "/."}:
            return "float"
    return _DEFAULT_TYPE


def _is_identifier(name: str) -> bool:
    """True if `name` is a plain Sutra-safe identifier. OCaml binders like
    `()` (unit) or names carrying a `'` (prime) are not lowerable as a
    Sutra variable name."""
    if not name:
        return False
    if not (name[0].isalpha() or name[0] == "_"):
        return False
    return all(c.isalnum() or c == "_" for c in name)


def _blend(cond_src: str, then_src: str, else_src: str) -> str:
    """The Sutra strong-defuzz two-way blend used for both `if/then/else`
    and `match` cases: weight = (1 + truth_axis(defuzzy(cond)))/2;
    result = weight*then + (1-weight)*else. Each product term is fully
    parenthesised so a bare `* (atom)` never sits before an infix
    operator (which the Sutra parser would read as a cast — CastExpr)."""
    w = f"truth_axis(defuzzy({cond_src}))"
    return f"(((1 + {w}) * ({then_src})) + ((1 - {w}) * ({else_src}))) / 2"


def _is_type_node(node) -> bool:
    """True for the OCaml grammar's type-expression nodes (the things
    that show up as a return-type annotation or inside a typed_pattern)."""
    return node.type == "type_constructor_path" or node.type.endswith("_type")


def _map_type(type_node, source: bytes, record_types=frozenset()) -> str:
    if type_node is None:
        return _DEFAULT_TYPE
    # A tuple type (`int * int`) is carried by the same positional-record
    # Axon that a tuple value lowers to.
    if type_node.type == "tuple_type":
        return "Axon"
    # An option type (`int option`) is carried by a tagged axon
    # `{_tag, _val}` — same Axon carrier.
    if type_node.type == "constructed_type" \
            and _node_text(type_node, source).strip().endswith("option"):
        return "Axon"
    text = _node_text(type_node, source).strip()
    if text in record_types:
        # A record type is carried by a Sutra Axon (the structural-typing
        # carrier), same as the TS interface->Axon mapping.
        return "Axon"
    return _OCAML_TYPE_TO_SUTRA.get(text, _DEFAULT_TYPE)


def _lower_expression(node, source: bytes) -> str:
    # An aggregate-literal argument hoisted to a temp Axon (see _ARG_HOIST):
    # emit the temp name instead of trying to lower the inline literal.
    if _ARG_HOIST and node is not None and node.id in _ARG_HOIST:
        return _ARG_HOIST[node.id]
    t = node.type
    if t == "number":
        return _normalize_number(_node_text(node, source))
    if t == "boolean":
        # OCaml `true` / `false` -> Sutra `true` / `false`.
        return _node_text(node, source)
    if t == "string":
        # OCaml string literal -> Sutra String literal. The `"…"` text
        # carries through; the common C-style escapes (\n \t \\ \" \r)
        # are shared. OCaml's `\ddd` decimal escape is NOT translated
        # (rare; would need re-encoding) — flagged here, not silently
        # mangled.
        txt = _node_text(node, source)
        return txt
    if t == "character":
        # OCaml char literal -> its codepoint int (chars are bytes; see
        # _char_codepoint).
        cc = next((c for c in node.named_children
                   if c.type == "character_content"), None)
        content = _node_text(cc, source) if cc is not None else ""
        cp = _char_codepoint(content)
        if cp is None:
            return f"/* UNSUPPORTED-EXPR: character {content!r} */"
        return str(cp)
    if t == "value_path":
        # A variable / function reference. MVP carries the path text
        # through verbatim (`a`, and later `Module.name`). Inside a
        # name-binding `match` arm, a bound name is substituted.
        name = _node_text(node, source)
        if name in _MATCH_SUBST:
            return _MATCH_SUBST[name]
        return name
    if t == "parenthesized_expression":
        inner = node.named_children[0] if node.named_children else None
        return f"({_lower_expression(inner, source)})" if inner is not None else "()"
    if t == "prefix_expression":
        # `!r` dereferences a ref cell; on the substrate the cell IS the
        # Sutra local, so a read is just the variable. `-x` / `~-x` is
        # unary negation.
        opn = next((c for c in node.named_children
                    if c.type == "prefix_operator"), None)
        operand = next((c for c in node.named_children
                        if c.type != "prefix_operator"), None)
        op_text = _node_text(opn, source) if opn is not None else ""
        operand_src = _lower_expression(operand, source) if operand is not None else "0"
        if op_text == "!":
            return operand_src
        if op_text in ("-", "~-"):
            return f"-({operand_src})"
        return f"/* UNSUPPORTED-PREFIX: {op_text} */"
    if t == "sign_expression":
        # A signed literal/expression: `-1`, `+x`, `- expr`. tree-sitter parses
        # `(-1)` as sign_expression(sign_operator, operand), distinct from the
        # `prefix_expression` used for `!r`. `-` -> arithmetic negation.
        opn = next((c for c in node.named_children
                    if c.type == "sign_operator"), None)
        operand = next((c for c in node.named_children
                        if c.type != "sign_operator"), None)
        op_text = _node_text(opn, source) if opn is not None else "+"
        operand_src = _lower_expression(operand, source) if operand is not None else "0"
        if op_text in ("-", "~-"):
            return f"-({operand_src})"
        return operand_src
    if t == "infix_expression":
        left = node.child_by_field_name("left")
        op = node.child_by_field_name("operator")
        right = node.child_by_field_name("right")
        op_text = _node_text(op, source) if op is not None else "+"
        if op_text == ":=":
            # Assignment is a *statement* (`r := e` returns unit); it has
            # no value in expression position. Lowered by _lower_stmt_expr
            # inside a sequence; reaching here means it was used as a value.
            return "/* UNSUPPORTED-EXPR: assignment used as a value */"
        left_src = _lower_expression(left, source) if left is not None else "0"
        right_src = _lower_expression(right, source) if right is not None else "0"
        # Bitwise AND/OR/XOR -> the substrate Bits stdlib (stdlib/bitwise.su,
        # 32-bit, non-negative). No Sutra bitwise operator exists.
        if op_text in _BITWISE_FN:
            return f"{_BITWISE_FN[op_text]}({left_src}, {right_src})"
        # Shifts by a CONSTANT are exact arithmetic identities: `a lsl k` =
        # a·2^k, `a lsr k` = floor(a/2^k) (unsigned). Variable shifts and
        # `asr` (negative-sensitive) are not handled yet.
        if op_text in ("lsl", "lsr"):
            if right is not None and right.type == "number":
                try:
                    k = int(_normalize_number(_node_text(right, source)))
                except ValueError:
                    k = None
                if k is not None and 0 <= k < 63:
                    shift = 1 << k
                    if op_text == "lsl":
                        return f"{left_src} * {shift}"
                    return f"Math.floor({left_src} / {shift})"
            return f"/* UNSUPPORTED-OP: {op_text} by non-constant */"
        op_sutra = _OP_MAP.get(op_text)
        if op_sutra is None:
            # Unknown operator (`asr`, string/list `^` `@`, …). No Sutra
            # equivalent — surface it, don't pass through as invalid Sutra.
            return f"/* UNSUPPORTED-OP: {op_text} */"
        return f"{left_src} {op_sutra} {right_src}"
    if t == "application_expression":
        kids = node.named_children
        if not kids:
            return "/* UNSUPPORTED-APP: empty */"
        # OCaml `failwith "…"` raises Failure on an error path. Sutra has
        # "no runtime errors by mechanism", so it lowers to a sentinel `0`
        # (the path is not taken for valid input; a real value would need a
        # typed error sentinel). `raise <exn>` for loop-break is the
        # machine's explicit HALT, handled in the machine, not here.
        if (kids[0].type == "value_path"
                and _node_text(kids[0], source) == "failwith"):
            return "0"
        # OCaml `not x` is a function application; lower it to Sutra's
        # logical-negation operator `!(x)` rather than a call to an
        # undefined `not`.
        if (kids[0].type == "value_path"
                and _node_text(kids[0], source) == "not"
                and len(kids) == 2):
            return f"!({_lower_expression(kids[1], source)})"
        # `ref e` allocates a cell holding e; on the substrate the cell is
        # a plain Sutra local, so the allocation lowers to the initial
        # value e (the `let r = ref e` binding becomes `<ty> r = e;`).
        if (kids[0].type == "value_path"
                and _node_text(kids[0], source) == "ref"
                and len(kids) == 2):
            return _lower_expression(kids[1], source)
        # `fst t` / `snd t` read positional fields of a tuple-axon
        # (`_0`/`_1`). MVP: numeric tuple elements (decoded via `.real()`).
        if (kids[0].type == "value_path" and len(kids) == 2
                and _node_text(kids[0], source) in ("fst", "snd")):
            field = "_0" if _node_text(kids[0], source) == "fst" else "_1"
            # Tuple field read — substrate-pure: the axon field comes back as a
            # number-VECTOR (no `.real()`; `real()` was removed from the language).
            # Measured 2026-06-07: the field read is clean (real-axis exact) at the
            # CLI runtime_dim, and downstream arithmetic is vector arithmetic. The
            # earlier "needs `.real()`" note was wrong — the prior failure was the
            # CLI printing the raw tensor, fixed at the terminal boundary, not the
            # field read.
            return f'realvec({_lower_expression(kids[1], source)}.item("{field}"))'
        fn_src = _lower_expression(kids[0], source)
        arg_srcs = [_lower_expression(a, source) for a in kids[1:]]
        return f"{fn_src}({', '.join(arg_srcs)})"
    if t == "if_expression":
        # OCaml `if c then a else b` is an *expression*. Lower it to the
        # same strong-defuzz blend the TS frontend uses for if/else:
        #   weight = (1 + truth_axis(defuzzy(c))) / 2
        #   result = weight * a + (1 - weight) * b
        # i.e. ((1 + truth_axis(defuzzy(c))) * a
        #       + (1 - truth_axis(defuzzy(c))) * b) / 2
        # When c defuzzes true (+1) the blend is a; false (-1) it is b;
        # at the midpoint it interpolates. Differentiable, fuzzy, no
        # host-side branch — the substrate decides. An `if c then a`
        # with no else is the implicit-zero-else form (OCaml types that
        # unit; we mirror the TS select-with-implicit-zero shape).
        cond = node.child_by_field_name("condition")
        then_c = None
        else_c = None
        for c in node.named_children:
            if c.type == "then_clause":
                then_c = c
            elif c.type == "else_clause":
                else_c = c
        cond_src = _lower_expression(cond, source) if cond is not None else "false"
        then_expr = (
            then_c.named_children[0]
            if then_c is not None and then_c.named_children else None
        )
        then_src = _lower_expression(then_expr, source) if then_expr is not None else "0"
        if else_c is not None and else_c.named_children:
            else_src = _lower_expression(else_c.named_children[0], source)
            return _blend(cond_src, then_src, else_src)
        # if without else: implicit-zero else.
        w = f"truth_axis(defuzzy({cond_src}))"
        return f"(((1 + {w}) * ({then_src}))) / 2"
    if t == "constructor_path":
        # A nullary variant constructor used as a value (`Green`) lowers
        # to its integer tag. Parameterised constructors (`Some x`) are
        # not enums and are not supported.
        cname = _node_text(node, source)
        if cname in _CONSTRUCTORS:
            return str(_CONSTRUCTORS[cname])
        return (f"/* UNSUPPORTED-EXPR: constructor {cname} "
                "(only nullary variants lower, as enum ints) */")
    if t == "match_expression":
        return _lower_match(node, source)
    if t == "field_get_expression":
        # `p.x` record field access. In OCaml this node ONLY appears for
        # record fields (module access parses as value_path), so no type
        # check is needed. Substrate-pure: the axon field comes back as a
        # number-VECTOR (no `.real()` — that accessor was removed from the
        # language). The field read is clean at the CLI runtime_dim (measured
        # 2026-06-07) and downstream arithmetic is vector arithmetic. MVP
        # scope: numeric record fields.
        obj = node.named_children[0] if node.named_children else None
        field = next(
            (c for c in node.named_children if c.type == "field_path"), None
        )
        obj_src = _lower_expression(obj, source) if obj is not None else "/* ? */"
        field_name = _node_text(field, source) if field is not None else ""
        return f'realvec({obj_src}.item("{field_name}"))'
    if t == "array_get_expression":
        # `a.(i)` -> RAM read at the array's base + index. Returns the element
        # as a number-VECTOR (substrate-pure) — NOT `.real()`, which would
        # collapse to a host scalar (no introspection in the language; the
        # element flows into substrate arithmetic/comparison/addressing as a
        # vector). The array must be a known RAM-backed binding
        # (`let a = Array.make …`).
        kids = node.named_children
        arr = kids[0] if kids else None
        idx = kids[1] if len(kids) > 1 else None
        arr_name = _node_text(arr, source) if arr is not None else ""
        idx_src = _lower_expression(idx, source) if idx is not None else "0"
        if arr_name in _INT_DICT_ARRAYS:
            return f"{arr_name}[{idx_src}]"
        if arr_name not in _RAM_ARRAYS:
            return f"/* UNSUPPORTED-EXPR: array_get on unknown array '{arr_name}' */"
        base = _RAM_ARRAYS[arr_name]
        addr = idx_src if base == 0 else f"{base} + {idx_src}"
        return f"ramRead({addr})"
    if t == "record_expression":
        # Building a record is multi-statement axon construction (Axon r;
        # r.add(...); …), only valid in body/statement position — handled
        # by _lower_body_to_statements. In a nested expression position we
        # have nowhere to emit the statements.
        return ("/* UNSUPPORTED-EXPR: record_expression must be a function "
                "body (nested record construction not supported) */")
    if t == "let_expression":
        # `let x = e in body` in EXPRESSION position (a nested sub-expr, not
        # a function body — that path emits real Sutra locals). Here there
        # is nowhere to emit a local, so a PURE simple binding is inlined by
        # substituting the bound name in the body (reusing _MATCH_SUBST).
        # Only simple-atom values (identifier/number) are substituted — a
        # compound value (`a + b`) would need parens that risk the
        # `(x) <op>`->cast ambiguity, and a `ref`/nested-fn binding needs a
        # real local; those stay UNSUPPORTED rather than emit wrong output.
        kids = node.named_children
        if len(kids) < 2:
            return "/* UNSUPPORTED-EXPR: malformed let_expression */"
        *binds, body_e = kids
        applied: list[tuple[str, object]] = []
        try:
            for b in binds:
                if b.type != "value_definition":
                    return f"/* UNSUPPORTED-EXPR: let_expression part {b.type} */"
                lb = next((c for c in b.named_children
                           if c.type == "let_binding"), None)
                if lb is None or not lb.named_children:
                    return "/* UNSUPPORTED-EXPR: malformed let binding */"
                lbk = lb.named_children
                name = _node_text(lbk[0], source)
                if any(k.type == "parameter" for k in lbk[1:-1]):
                    return "/* UNSUPPORTED-EXPR: nested function in let-expression */"
                val = lbk[-1]
                if val.type == "number":
                    val_src = _normalize_number(_node_text(val, source))
                elif val.type == "value_path":
                    val_src = _lower_expression(val, source)
                else:
                    return ("/* UNSUPPORTED-EXPR: let-expression value not a "
                            "simple atom (substitution would risk precedence) */")
                if "UNSUPPORTED" in val_src:
                    return val_src
                saved = _MATCH_SUBST.get(name, _MISSING)
                _MATCH_SUBST[name] = val_src
                applied.append((name, saved))
            return _lower_expression(body_e, source)
        finally:
            for name, saved in reversed(applied):
                if saved is _MISSING:
                    _MATCH_SUBST.pop(name, None)
                else:
                    _MATCH_SUBST[name] = saved
    return f"/* UNSUPPORTED-EXPR: {t} */"


def _is_option_match(node, source: bytes) -> bool:
    """True if any case of a `match_expression` is an option pattern
    (`Some _` / `None`)."""
    for c in node.named_children:
        if c.type != "match_case":
            continue
        pat = c.named_children[0] if c.named_children else None
        if pat is None:
            continue
        if pat.type == "constructor_pattern":
            cp = next((k for k in pat.named_children
                       if k.type == "constructor_path"), None)
            if cp is not None and _node_text(cp, source) == "Some":
                return True
        if pat.type == "constructor_path" and _node_text(pat, source) == "None":
            return True
    return False


def _is_variant_match(node, source: bytes) -> bool:
    """True if any case matches an axon-mode (parameterised) variant
    constructor — `C x` or bare `C` where `C` is in `_VARIANT_CTORS`."""
    for c in node.named_children:
        if c.type != "match_case":
            continue
        pat = c.named_children[0] if c.named_children else None
        if pat is None:
            continue
        if pat.type == "constructor_pattern":
            cp = next((k for k in pat.named_children
                       if k.type == "constructor_path"), None)
            if cp is not None and _node_text(cp, source) in _VARIANT_CTORS:
                return True
        if pat.type == "constructor_path" and _node_text(pat, source) in _VARIANT_CTORS:
            return True
    return False


def _lower_variant_match_body(node, source: bytes, indent: str) -> str:
    """Lower `match v with C1 x -> … | C2 -> … | _ -> …` for an axon-mode
    variant, in FUNCTION-BODY position. Same shape as the option match: read the
    tag/payload into `int` locals first (an inline axon field read does not defuzz
    to a clean boolean), then a nested blend tests `_vtag == <ctor tag>`; a
    constructor-with-arg binds its payload to `_vval`. Numeric payloads only."""
    kids = node.named_children
    scrut_src = _lower_expression(kids[0], source)
    cases = [c for c in kids[1:] if c.type == "match_case"]
    if not cases:
        return f"{indent}// UNSUPPORTED-MATCH: no cases\n"
    out = f'{indent}int _vtag = realvec({scrut_src}.item("_tag"));\n'
    out += f'{indent}int _vval = realvec({scrut_src}.item("_val"));\n'
    # Multi-arg ctors store their payload in `_val0`, `_val1`, … — read those
    # slots too when any matched ctor has arity >= 2.
    _multi = 0
    for c in cases:
        p0 = c.named_children[0] if c.named_children else None
        cpath = None
        if p0 is not None and p0.type == "constructor_pattern":
            cpath = next((k for k in p0.named_children
                          if k.type == "constructor_path"), None)
        elif p0 is not None and p0.type == "constructor_path":
            cpath = p0
        if cpath is not None and _node_text(cpath, source) in _VARIANT_CTORS:
            _multi = max(_multi, _VARIANT_CTORS[_node_text(cpath, source)][1])
    if _multi >= 2:
        for i in range(_multi):
            out += f'{indent}int _val{i} = realvec({scrut_src}.item("_val{i}"));\n'
    parsed: list[tuple[Optional[str], str]] = []  # (test_or_None, res_src)
    for c in cases:
        cc = c.named_children
        if len(cc) != 2:
            return f"{indent}// UNSUPPORTED-MATCH-CASE: guard/or-pattern in variant match\n"
        pat, res = cc[0], cc[1]
        if pat.type == "constructor_pattern":
            cp = next((k for k in pat.named_children
                       if k.type == "constructor_path"), None)
            name = _node_text(cp, source) if cp is not None else ""
            if name not in _VARIANT_CTORS:
                return f"{indent}// UNSUPPORTED-MATCH-PATTERN: unknown variant ctor {name}\n"
            tag = _VARIANT_CTORS[name][0]
            # Payload binding: a multi-arg ctor binds a (parenthesized) tuple
            # pattern, component i -> `_val{i}`; a single-arg ctor binds one
            # value_pattern -> `_vval`.
            tuple_pat = None
            for k in pat.named_children:
                kk = (k.named_children[0]
                      if k.type == "parenthesized_pattern" and k.named_children
                      else k)
                if kk is not None and kk.type == "tuple_pattern":
                    tuple_pat = kk
                    break
            if tuple_pat is not None:
                binds = [vp for vp in tuple_pat.named_children
                         if vp.type == "value_pattern"]
                saved: dict = {}
                for i, vp in enumerate(binds):
                    nm = _node_text(vp, source)
                    if nm != "_":
                        saved[nm] = _MATCH_SUBST.get(nm, _MISSING)
                        _MATCH_SUBST[nm] = f"_val{i}"
                try:
                    res_src = _lower_expression(res, source)
                finally:
                    for nm, sv in saved.items():
                        if sv is _MISSING:
                            _MATCH_SUBST.pop(nm, None)
                        else:
                            _MATCH_SUBST[nm] = sv
            else:
                argpat = next((k for k in pat.named_children
                               if k.type == "value_pattern"), None)
                if argpat is not None and _node_text(argpat, source) != "_":
                    bound = _node_text(argpat, source)  # bind payload -> _vval
                    saved1 = _MATCH_SUBST.get(bound, _MISSING)
                    _MATCH_SUBST[bound] = "_vval"
                    try:
                        res_src = _lower_expression(res, source)
                    finally:
                        if saved1 is _MISSING:
                            _MATCH_SUBST.pop(bound, None)
                        else:
                            _MATCH_SUBST[bound] = saved1
                else:
                    res_src = _lower_expression(res, source)
            parsed.append((f"_vtag == {tag}", res_src))
        elif pat.type == "constructor_path" and _node_text(pat, source) in _VARIANT_CTORS:
            tag = _VARIANT_CTORS[_node_text(pat, source)][0]
            parsed.append((f"_vtag == {tag}", _lower_expression(res, source)))
        elif pat.type == "value_pattern" and _node_text(pat, source) == "_":
            parsed.append((None, _lower_expression(res, source)))
        else:
            return f"{indent}// UNSUPPORTED-MATCH-PATTERN: {pat.type} in variant match\n"
    expr = parsed[-1][1]
    for test, res in reversed(parsed[:-1]):
        expr = _blend(test, res, expr)
    out += f"{indent}return {expr};\n"
    return out


def _lower_option_match_body(node, source: bytes, indent: str) -> str:
    """Lower `match o with Some x -> e1 | None -> e2` in FUNCTION-BODY
    position. The scrutinee is a tagged axon `{_tag,_val}`; its fields are
    bound to `int` locals FIRST, then the blend tests `_otag`. This is
    required, not cosmetic: an inline axon field read `o.item("_tag").real()
    == 1` does NOT coerce to a clean boolean (measured: defuzzes to truth 0
    for the false branch), but the same comparison off an `int` local
    defuzzes to -1 correctly. So option matches are only supported as a
    function body (where the locals can be emitted), not nested in an
    expression."""
    kids = node.named_children
    scrut_src = _lower_expression(kids[0], source)
    cases = [c for c in kids[1:] if c.type == "match_case"]
    if not cases:
        return f"{indent}// UNSUPPORTED-MATCH: no cases\n"
    # Substrate-pure: the tag and payload come back as number-VECTORS (no
    # `.real()` — removed from the language). The tag drives the match dispatch
    # numerically; the payload is used in vector arithmetic.
    out = f'{indent}int _otag = realvec({scrut_src}.item("_tag"));\n'
    out += f'{indent}int _oval = realvec({scrut_src}.item("_val"));\n'
    parsed: list[tuple[Optional[str], str]] = []  # (test_or_None, res_src)
    for c in cases:
        cc = c.named_children
        if len(cc) != 2:
            return f"{indent}// UNSUPPORTED-MATCH-CASE: guard/or-pattern\n"
        pat, res = cc[0], cc[1]
        if pat.type == "constructor_pattern":
            cp = next((k for k in pat.named_children
                       if k.type == "constructor_path"), None)
            if cp is None or _node_text(cp, source) != "Some":
                return f"{indent}// UNSUPPORTED-MATCH-PATTERN: only option Some/None\n"
            argpat = next((k for k in pat.named_children
                           if k.type == "value_pattern"), None)
            if argpat is not None and _node_text(argpat, source) != "_":
                bound = _node_text(argpat, source)
                saved = _MATCH_SUBST.get(bound, _MISSING)
                _MATCH_SUBST[bound] = "_oval"
                try:
                    res_src = _lower_expression(res, source)
                finally:
                    if saved is _MISSING:
                        _MATCH_SUBST.pop(bound, None)
                    else:
                        _MATCH_SUBST[bound] = saved
            else:
                res_src = _lower_expression(res, source)
            parsed.append(("_otag == 1", res_src))
        elif pat.type == "constructor_path" and _node_text(pat, source) == "None":
            parsed.append(("_otag == 0", _lower_expression(res, source)))
        elif pat.type == "value_pattern" and _node_text(pat, source) == "_":
            parsed.append((None, _lower_expression(res, source)))
        else:
            return f"{indent}// UNSUPPORTED-MATCH-PATTERN: {pat.type} in option match\n"
    expr = parsed[-1][1]
    for test, res in reversed(parsed[:-1]):
        expr = _blend(test, res, expr)
    out += f"{indent}return {expr};\n"
    return out


def _or_pattern_leaves(pat) -> list:
    """Flatten an `or_pattern` (`1 | 2 | 3`, possibly left-nested as
    `(1 | 2) | 3`) into its leaf sub-patterns, in order."""
    leaves: list = []
    for c in pat.named_children:
        if c.type == "or_pattern":
            leaves.extend(_or_pattern_leaves(c))
        else:
            leaves.append(c)
    return leaves


def _record_pattern_fields(pat, source: bytes) -> list:
    """[(field_name, bind_name)] for a `record_pattern`. Field-punning `{x; y}`
    binds the field name itself; `{x = a}` binds the explicit name `a`."""
    out: list = []
    for fp in pat.named_children:
        if fp.type != "field_pattern":
            continue
        field = None
        bind = None
        for ch in fp.named_children:
            if ch.type == "field_path":
                field = _node_text(ch, source).split(".")[-1]
            elif ch.type == "value_pattern":
                bind = _node_text(ch, source)
        if field is not None:
            out.append((field, bind or field))
    return out


def _lower_match(node, source: bytes) -> str:
    """Lower `match scrut with k1 -> r1 | k2 -> r2 | _ -> rd` to a nested
    strong-defuzz blend — the same machinery as if/then/else, chained.
    MVP scope: integer-literal patterns plus a trailing `_` wildcard
    catch-all. Anything else (constructor / record / or- / guarded
    patterns, no final wildcard) lowers to an UNSUPPORTED marker rather
    than silently producing a non-exhaustive or wrong blend."""
    kids = node.named_children
    if not kids:
        return "/* UNSUPPORTED-MATCH: empty */"
    if _is_option_match(node, source):
        # Option matches read tagged-axon fields that must be bound to
        # `int` locals first (an inline axon `.real()` read does not
        # defuzz to a clean boolean) — only doable in function-body
        # position, handled by `_lower_option_match_body`. In an expression
        # position there is nowhere to emit the locals.
        return ("/* UNSUPPORTED-MATCH: option match must be a function body "
                "(needs tag/val locals) */")
    scrut_src = _lower_expression(kids[0], source)
    cases = [c for c in kids[1:] if c.type == "match_case"]
    if not cases:
        return "/* UNSUPPORTED-MATCH: no cases */"

    # (kind, test_or_None, result_src); kind in {"literal", "ctor", "wild"}
    parsed: list[tuple[str, Optional[str], str]] = []
    for c in cases:
        cc = c.named_children
        guard_node = next((x for x in cc if x.type == "guard"), None)
        if guard_node is not None:
            # Guarded case `| pat when g -> r`: fires iff `pat` matches AND `g`
            # holds. Since a guard can fail, a guarded case ALWAYS carries a test
            # (kind "literal") and is never the terminal catch-all — there must be
            # a following fallback. Pattern may bind a name (`| x when …`), be `_`,
            # or be an int/variant literal.
            others = [x for x in cc if x.type != "guard"]
            gcond = guard_node.named_children[0] if guard_node.named_children else None
            if len(others) != 2 or gcond is None:
                return "/* UNSUPPORTED-MATCH-CASE: malformed guarded case */"
            gpat, gres = others[0], others[1]
            bound = None
            pat_test = None
            if gpat.type == "value_pattern" and _node_text(gpat, source) != "_":
                bound = _node_text(gpat, source)  # binds the scrutinee
            elif gpat.type == "value_pattern":
                pat_test = None  # `_` matches anything
            elif gpat.type == "number":
                pat_test = f"{scrut_src} == {_node_text(gpat, source)}"
            elif (gpat.type == "constructor_path"
                  and _node_text(gpat, source) in _CONSTRUCTORS):
                pat_test = f"{scrut_src} == {_CONSTRUCTORS[_node_text(gpat, source)]}"
            else:
                return f"/* UNSUPPORTED-MATCH-CASE: guarded pattern {gpat.type} */"
            saved = _MISSING
            if bound is not None:
                saved = _MATCH_SUBST.get(bound, _MISSING)
                simple = _is_identifier(scrut_src) or scrut_src.lstrip("-").isdigit()
                _MATCH_SUBST[bound] = scrut_src if simple else f"({scrut_src})"
            try:
                guard_src = _lower_expression(gcond, source)
                gres_src = _lower_expression(gres, source)
            finally:
                if bound is not None:
                    if saved is _MISSING:
                        _MATCH_SUBST.pop(bound, None)
                    else:
                        _MATCH_SUBST[bound] = saved
            test = guard_src if pat_test is None else f"({pat_test}) && ({guard_src})"
            parsed.append(("literal", test, gres_src))
            continue
        if len(cc) != 2:
            return "/* UNSUPPORTED-MATCH-CASE: unexpected case shape */"
        pat, res = cc[0], cc[1]
        if pat.type == "value_pattern" and _node_text(pat, source) != "_":
            # A name-binding catch-all `| x -> body`: `x` binds the whole
            # scrutinee. Lower the body with `x` substituted by the
            # scrutinee source (save/restore for nested matches). Treated
            # as a wildcard for blend structure (must be the last case).
            bound = _node_text(pat, source)
            saved = _MATCH_SUBST.get(bound, _MISSING)
            # Substitute bare for a simple-atom scrutinee (identifier or
            # number — the common `match var with …` case). Parenthesizing
            # would create a leading `(x) <op>` that Sutra mis-parses as a
            # cast (the unresolved CastExpr grammar ambiguity); a complex
            # scrutinee is wrapped best-effort and may hit that ambiguity.
            simple = _is_identifier(scrut_src) or scrut_src.lstrip("-").isdigit()
            _MATCH_SUBST[bound] = scrut_src if simple else f"({scrut_src})"
            try:
                res_src = _lower_expression(res, source)
            finally:
                if saved is _MISSING:
                    _MATCH_SUBST.pop(bound, None)
                else:
                    _MATCH_SUBST[bound] = saved
            parsed.append(("wild", None, res_src))
            continue
        if pat.type == "record_pattern":
            # `| {x; y} -> body`: destructuring a record (an axon). Irrefutable
            # (one record shape) -> a terminal catch-all that binds each field
            # name to its substrate field read `realvec(scrut.item("f"))` (the
            # same projection record field access uses), then lowers the body.
            fields = _record_pattern_fields(pat, source)
            if not fields:
                return "/* UNSUPPORTED-MATCH-PATTERN: empty record pattern */"
            simple = _is_identifier(scrut_src) or scrut_src.lstrip("-").isdigit()
            base = scrut_src if simple else f"({scrut_src})"
            saved: dict = {}
            for field, bind in fields:
                saved[bind] = _MATCH_SUBST.get(bind, _MISSING)
                _MATCH_SUBST[bind] = f'realvec({base}.item("{field}"))'
            try:
                res_src = _lower_expression(res, source)
            finally:
                for bind, sv in saved.items():
                    if sv is _MISSING:
                        _MATCH_SUBST.pop(bind, None)
                    else:
                        _MATCH_SUBST[bind] = sv
            parsed.append(("wild", None, res_src))
            continue
        res_src = _lower_expression(res, source)
        if pat.type == "number":
            parsed.append(("literal", f"{scrut_src} == {_node_text(pat, source)}", res_src))
        elif pat.type == "value_pattern" and _node_text(pat, source) == "_":
            parsed.append(("wild", None, res_src))
        elif pat.type == "constructor_path":
            cname = _node_text(pat, source)
            if cname not in _CONSTRUCTORS:
                return f"/* UNSUPPORTED-MATCH-PATTERN: unknown constructor {cname} */"
            parsed.append(("ctor", f"{scrut_src} == {_CONSTRUCTORS[cname]}", res_src))
        elif pat.type == "or_pattern":
            # `k1 | k2 | … -> r`: the case fires if the scrutinee equals ANY
            # alternative — a disjunction of the per-leaf equality tests.
            # Leaves must be int literals or nullary-variant constructors
            # (the patterns we already test by `==`); anything else is not
            # supported (binding/nested patterns inside an or- need more).
            subtests: list[str] = []
            bad = None
            for leaf in _or_pattern_leaves(pat):
                if leaf.type == "number":
                    subtests.append(f"{scrut_src} == {_node_text(leaf, source)}")
                elif (leaf.type == "constructor_path"
                      and _node_text(leaf, source) in _CONSTRUCTORS):
                    subtests.append(
                        f"{scrut_src} == {_CONSTRUCTORS[_node_text(leaf, source)]}")
                else:
                    bad = leaf.type
                    break
            if bad is not None or not subtests:
                return ("/* UNSUPPORTED-MATCH-PATTERN: or-pattern leaf "
                        f"{bad or 'empty'} (only int/variant literals) */")
            test = " || ".join(f"({s})" for s in subtests)
            parsed.append(("literal", test, res_src))
        else:
            return f"/* UNSUPPORTED-MATCH-PATTERN: {pat.type} */"

    # The LAST case is the base/catch-all (its result is the innermost
    # else, its test dropped). Exact for `_` and for an exhaustive variant
    # match (every constructor listed). A trailing *integer-literal* case
    # is rejected — an int match without `_` is non-exhaustive.
    if parsed[-1][0] == "literal":
        return "/* UNSUPPORTED-MATCH: integer-literal match needs a trailing `_` wildcard */"
    for kind, _test, _res in parsed[:-1]:
        if kind == "wild":
            return "/* UNSUPPORTED-MATCH: wildcard `_` must be the last case */"

    expr = parsed[-1][2]
    for _kind, test, res in reversed(parsed[:-1]):
        expr = _blend(test, res, expr)
    return expr


def _lower_param(param_node, source: bytes,
                 record_types=frozenset()) -> Optional[tuple[str, str]]:
    """Lower one `parameter` node → (name, sutra_type), or None for the
    `unit` parameter (`let main () = …`), which contributes no Sutra
    parameter."""
    child = param_node.named_children[0] if param_node.named_children else None
    if child is None:
        return None
    if child.type == "unit":
        return None
    if child.type == "value_pattern":
        return (_node_text(child, source), _DEFAULT_TYPE)
    if child.type == "typed_pattern":
        vp = None
        tp = None
        for c in child.named_children:
            if c.type == "value_pattern":
                vp = c
            elif _is_type_node(c):
                tp = c
        name = _node_text(vp, source) if vp is not None else "_arg"
        ptype = _map_type(tp, source, record_types) if tp is not None else _DEFAULT_TYPE
        return (name, ptype)
    # Other pattern kinds (tuple / constructor destructuring) are a later
    # item; carry the name through as an int-typed param for now.
    return (_node_text(child, source), _DEFAULT_TYPE)


def _emit_record_construction(body, source: bytes, indent: str, var: str) -> str:
    """Emit Sutra axon construction for a `record_expression` into local `var`
    (`Axon var; var.add("f", e); …`) — WITHOUT a trailing return, so it can be
    reused both as a function body and as a hoisted call argument."""
    lines = f"{indent}Axon {var};\n"
    for fe in body.named_children:
        if fe.type != "field_expression":
            continue
        fp = next((c for c in fe.named_children if c.type == "field_path"), None)
        val = next((c for c in fe.named_children if c.type != "field_path"), None)
        fname = _node_text(fp, source) if fp is not None else ""
        val_src = _lower_expression(val, source) if val is not None else "0"
        lines += f'{indent}{var}.add("{fname}", {val_src});\n'
    return lines


def _lower_record_body(body, source: bytes, indent: str) -> str:
    """Lower a `record_expression` function body `{ f1 = e1; … }` to Sutra
    axon construction + return. Mirrors the TS object-literal->axon lowering."""
    return (_emit_record_construction(body, source, indent, "_record")
            + f"{indent}return _record;\n")


def _hoist_record_args(node, source: bytes, indent: str):
    """If `node` is a call `f a1 … aN` with one or more *aggregate-literal*
    arguments (a record `{…}` or a tuple `(e0, …)`), hoist each such argument into
    a temp Axon local and return the statement block `Axon _argK; …; return
    f(…, _argK, …);`. Returns None when there is no such argument (the caller falls
    through to the normal `return f(…);`). Record/tuple construction is statement-
    based (no inline axon literal), so an aggregate passed directly as an argument
    needs this lift. NOTE: a single parenthesized expression `(e)` is NOT a tuple —
    only a `tuple_expression` (comma-separated) is hoisted."""
    kids = node.named_children
    if len(kids) < 2:
        return None
    func, args = kids[0], kids[1:]
    prelude = ""
    arg_srcs = []
    found = False
    for i, a in enumerate(args):
        ua = _unwrap_parens(a)
        if ua is not None and ua.type == "record_expression":
            found = True
            var = f"_arg{i}"
            prelude += _emit_record_construction(ua, source, indent, var)
            arg_srcs.append(var)
        elif ua is not None and ua.type == "tuple_expression":
            found = True
            var = f"_arg{i}"
            prelude += _emit_tuple_construction(ua, source, indent, var)
            arg_srcs.append(var)
        elif _variant_value_kind(ua, source) is not None:
            # An axon-mode variant value passed directly as an argument
            # (`eval (Neg 5)`) — same statement-based construction as records.
            found = True
            var = f"_arg{i}"
            prelude += _emit_variant_construction(
                _variant_value_kind(ua, source), source, indent, var)
            arg_srcs.append(var)
        else:
            arg_srcs.append(_lower_expression(a, source))
    if not found:
        return None
    func_src = _lower_expression(func, source)
    return prelude + f"{indent}return {func_src}({', '.join(arg_srcs)});\n"


def _emit_tuple_construction(body, source: bytes, indent: str, var: str) -> str:
    """Emit Sutra axon construction for a `tuple_expression` into local `var`
    (positional fields `_0`, `_1`, …) — WITHOUT a trailing return, so it can be
    reused as a function body or as a hoisted call argument."""
    lines = f"{indent}Axon {var};\n"
    for i, el in enumerate(body.named_children):
        lines += f'{indent}{var}.add("_{i}", {_lower_expression(el, source)});\n'
    return lines


def _aggregate_arg_emitter(ua, source: bytes, indent: str, var: str):
    """If `ua` (an unwrapped node) is an aggregate LITERAL — a record `{…}`, a
    `tuple_expression`, or an axon-mode variant construction — return its
    statement-based construction into `var`; otherwise None."""
    if ua is None:
        return None
    if ua.type == "record_expression":
        return _emit_record_construction(ua, source, indent, var)
    if ua.type == "tuple_expression":
        return _emit_tuple_construction(ua, source, indent, var)
    vk = _variant_value_kind(ua, source)
    if vk is not None:
        return _emit_variant_construction(vk, source, indent, var)
    return None


def _hoist_aggregate_args_deep(body, source: bytes, indent: str):
    """Hoist aggregate-literal arguments of ANY call nested inside the return
    expression `body` — e.g. `f {..} + g {..}`, where the aggregates are operands
    of an operator rather than the single body call `_hoist_record_args` handles.
    Each aggregate arg is built into a temp Axon (`_ah0`, `_ah1`, …) and registered
    in `_ARG_HOIST` so `_lower_expression` emits the temp at the call site. Returns
    `(prelude, added_node_ids)` or None. The caller lowers `body` then pops the ids.
    Scope: aggregates that are DIRECT call arguments (nested calls are recursed
    into); an aggregate nested inside another aggregate's field lowers normally."""
    prelude_parts: list[str] = []
    added: list[int] = []
    counter = [0]

    def visit(n):
        if n is None:
            return
        if n.type == "application_expression":
            kids = n.named_children
            if len(kids) >= 2:
                for a in kids[1:]:
                    ua = _unwrap_parens(a)
                    var = f"_ah{counter[0]}"
                    emit = _aggregate_arg_emitter(ua, source, indent, var)
                    if emit is not None:
                        prelude_parts.append(emit)
                        _ARG_HOIST[a.id] = var
                        added.append(a.id)
                        counter[0] += 1
                    else:
                        visit(a)
                visit(kids[0])
                return
        for c in n.named_children:
            visit(c)

    visit(body)
    if not prelude_parts:
        return None
    return "".join(prelude_parts), added


def _lower_tuple_body(body, source: bytes, indent: str) -> str:
    """Lower a `tuple_expression` function body `(e0, e1, …)` to Sutra axon
    construction (positional fields) + return. A tuple is an anonymous positional
    record; `fst`/`snd` read `_0`/`_1` back. MVP scope: numeric tuple elements."""
    return (_emit_tuple_construction(body, source, indent, "_tuple")
            + f"{indent}return _tuple;\n")


def _unwrap_parens(node):
    """Peel `parenthesized_expression` wrappers to the inner expression."""
    while node is not None and node.type == "parenthesized_expression" \
            and node.named_children:
        node = node.named_children[0]
    return node


def _option_kind(node, source: bytes):
    """Classify an expression as an OCaml option constructor:
    ('none',) for `None`, ('some', arg_node) for `Some e`, else None."""
    if node is None:
        return None
    if node.type == "constructor_path" and _node_text(node, source) == "None":
        return ("none",)
    if node.type == "application_expression":
        kids = node.named_children
        if (len(kids) == 2 and kids[0].type == "constructor_path"
                and _node_text(kids[0], source) == "Some"):
            return ("some", kids[1])
    return None


def _lower_option_body(kind, source: bytes, indent: str) -> str:
    """Lower an option value (`None` / `Some e`) in function-body position
    to a tagged axon `{_tag, _val}`: `None` -> tag 0, `Some e` -> tag 1 +
    value e. `match … with Some x -> … | None -> …` reads them back. Same
    body-position constraint as records/tuples. MVP: numeric `Some`
    payloads (read via `.real()`)."""
    lines = f"{indent}Axon _opt;\n"
    if kind[0] == "some":
        lines += f'{indent}_opt.add("_tag", 1);\n'
        lines += f'{indent}_opt.add("_val", {_lower_expression(kind[1], source)});\n'
    else:
        lines += f'{indent}_opt.add("_tag", 0);\n'
        lines += f'{indent}_opt.add("_val", 0);\n'
    lines += f"{indent}return _opt;\n"
    return lines


def _variant_value_kind(node, source: bytes):
    """Classify an expression as a construction of an axon-mode (parameterised)
    variant constructor: returns `(tag, arity, args)` or None, where `args` is a
    list of argument expression nodes (length == arity).
    `C x` (arity-1) -> (tag, 1, [x]); `C (a, b)` (arity-2) -> (tag, 2, [a, b]);
    bare `C` (arity-0 in an axon-mode type) -> (tag, 0, [])."""
    if node is None:
        return None
    if node.type == "constructor_path":
        name = _node_text(node, source)
        if name in _VARIANT_CTORS:
            tag, arity = _VARIANT_CTORS[name]
            # A bare constructor is a value only when nullary; a bare
            # parameterised ctor would be a partial application (a function
            # value) — not supported, so leave it UNSUPPORTED.
            if arity == 0:
                return (tag, 0, [])
        return None
    if node.type == "application_expression":
        kids = node.named_children
        if len(kids) == 2 and kids[0].type == "constructor_path":
            name = _node_text(kids[0], source)
            if name not in _VARIANT_CTORS:
                return None
            tag, arity = _VARIANT_CTORS[name]
            if arity == 1:
                return (tag, 1, [kids[1]])
            if arity >= 2:
                # `C (a, b, …)` — the argument is a (parenthesized) tuple whose
                # components are the payload. Arity must match the declaration.
                arg = _unwrap_parens(kids[1])
                if arg is not None and arg.type == "tuple_expression":
                    comps = list(arg.named_children)
                    if len(comps) == arity:
                        return (tag, arity, comps)
    return None


def _emit_variant_construction(kind, source: bytes, indent: str, var: str) -> str:
    """Emit axon construction for an axon-mode variant value (`C x` / `C (a,b)` /
    bare `C`) into local `var` WITHOUT a trailing return — reusable as a function
    body or a hoisted call argument. Slot naming: nullary -> `_val`=0; single-arg
    -> `_val` (backward-compatible); multi-arg -> `_val0`, `_val1`, … (one per
    payload component)."""
    tag, arity, args = kind
    out = (f"{indent}Axon {var};\n"
           f'{indent}{var}.add("_tag", {tag});\n')
    if arity <= 1:
        val = _lower_expression(args[0], source) if (arity == 1 and args) else "0"
        out += f'{indent}{var}.add("_val", {val});\n'
    else:
        for i in range(arity):
            out += f'{indent}{var}.add("_val{i}", {_lower_expression(args[i], source)});\n'
    return out


def _lower_variant_value_body(kind, source: bytes, indent: str) -> str:
    """Lower an axon-mode variant value (`C x` / bare `C`) in function-body
    position to a tagged axon `{_tag, _val}` + return — the same shape as the
    option body, generalized to any user constructor's tag."""
    return (_emit_variant_construction(kind, source, indent, "_variant")
            + f"{indent}return _variant;\n")


def _lower_local_binding(vd, source: bytes, indent: str,
                         record_types=frozenset(), refs: Optional[dict] = None) -> str:
    """Lower one `value_definition` from a `let … in` into a Sutra local
    declaration (`<type> name = <expr>;`). OCaml `let` is immutable, so
    no `slot`. A *local function* binding (params present) can't nest in
    Sutra — emit an UNSUPPORTED marker rather than broken output. A
    `let r = ref e` binds a mutable cell; record it in `refs` (name->type)
    so an enclosing `while` can thread it as loop state."""
    lb = None
    for c in vd.named_children:
        if c.type == "let_binding":
            lb = c
            break
    if lb is None or not lb.named_children:
        return f"{indent}// UNSUPPORTED-LOCAL-BINDING: malformed\n"
    kids = lb.named_children
    name = _node_text(kids[0], source)
    params_nodes = [k for k in kids[1:-1] if k.type == "parameter"]
    if params_nodes:
        # A nested function. Sutra has no nested declarations, but a CLOSED
        # one (its body's free value-paths are all its own params or
        # top-level names) can be hoisted to a sibling top-level function
        # via the same lowering. A nested function that captures an
        # enclosing local is a closure — not supported yet.
        body_node = kids[-1]
        param_names = {
            p[0] for p in (_lower_param(pn, source, record_types)
                           for pn in params_nodes) if p is not None
        }
        free = _value_paths(body_node, source) - param_names - _TOPLEVEL_NAMES - {name}
        if free:
            return (
                f"{indent}// UNSUPPORTED-LOCAL-FN: nested function '{name}' "
                f"captures enclosing local(s) {sorted(free)} "
                "(closure conversion not supported)\n"
            )
        _HOISTED_DECLS.append(_lower_let_binding(lb, source, record_types))
        return ""
    value = kids[-1]
    # A DIRECT axon-mode variant construction (`let z = Zero` / `let a = Lit 7`)
    # binds a tagged axon `{_tag,_val}`; emit the construction into `name` (typed
    # Axon by `_emit_variant_construction`), the same shape the body/arg positions
    # use. A nullary ctor (`Zero`) stores `_val`=0. (A `let a = lit 7` via an
    # Axon-returning *helper function* is handled below by `binds_axon_call`; this
    # branch is the direct-constructor case the helper path doesn't cover.)
    if _is_identifier(name):
        _vk = _variant_value_kind(_unwrap_parens(value), source)
        if _vk is not None:
            return _emit_variant_construction(_vk, source, indent, name)
    # Array/bytes allocation — backing chosen by access pattern (Emma 2026-06-13).
    _arr_kind = _array_alloc_kind(value, source)
    if _arr_kind is not None and _is_identifier(name):
        scope = _enclosing_definition(lb)
        loop_used = (_arr_kind == "array"
                     and _array_loop_accessed(name, scope, source))
        if _arr_kind == "array" and not loop_used:
            # Straight-line ordinary array -> a per-instance int-dict local. Slots
            # start at 0 (an `Array.make` fill value other than 0 is a documented
            # limitation — straight-line arrays write before read). `a.(i)` /
            # `a.(i) <- v` route to `a[i]` / `a[i] = v`.
            _INT_DICT_ARRAYS.add(name)
            return f"{indent}dict<int, int> {name};\n"
        # `Bytes.make`, or an `Array` mutated across a loop (vector accumulator)
        # -> the global RAM device at a compile-time base.
        base = len(_RAM_ARRAYS) * _RAM_STRIDE
        _RAM_ARRAYS[name] = base
        return f"{indent}// {name}: RAM-backed array at base {base}\n"
    ret_type = None
    for k in kids[1:-1]:
        if _is_type_node(k):
            ret_type = _map_type(k, source, record_types)
    # `let r = ref e` — a mutable cell. Type from the initial value e.
    is_ref = (value.type == "application_expression"
              and value.named_children
              and value.named_children[0].type == "value_path"
              and _node_text(value.named_children[0], source) == "ref"
              and len(value.named_children) == 2)
    # A local bound to a call of an Axon-returning function (record/tuple/
    # option) is itself an Axon, so a later `p.x` / `fst p` dispatches to the
    # axon accessor rather than torch's tensor `.item()`.
    _vu = _unwrap_parens(value)
    binds_axon_call = (
        _vu is not None and _vu.type == "application_expression"
        and _vu.named_children
        and _vu.named_children[0].type == "value_path"
        and _node_text(_vu.named_children[0], source) in _AXON_RETURNING
    )
    if ret_type is not None:
        ty = ret_type
    elif binds_axon_call:
        ty = "Axon"
    elif is_ref:
        ty = _value_binding_type(value.named_children[1], source)
    else:
        ty = _DEFAULT_TYPE
    if is_ref and refs is not None and _is_identifier(name):
        refs[name] = ty
    return f"{indent}{ty} {name} = {_lower_expression(value, source)};\n"


def _lower_while(node, source: bytes, indent: str, refs: dict) -> str:
    """Lower an OCaml `while COND do BODY done` to a Sutra `while_loop`.
    The loop's recurrent state is the set of in-scope mutable refs
    (`refs`) the condition/body touch; the `while_loop` declaration is
    hoisted to top level (`_HOISTED_LOOPS`) and the call site emits the
    `slot`/`loop`/write-back sequence — the same shape the tail-recursion
    lowering uses, but with sequential (not simultaneous) body updates,
    since OCaml `while` bodies execute statement-by-statement."""
    cond = node.child_by_field_name("condition")
    do_clause = next((c for c in node.named_children if c.type == "do_clause"), None)
    body = do_clause.named_children[0] if (do_clause and do_clause.named_children) else None
    if cond is None or body is None:
        return f"{indent}// UNSUPPORTED-WHILE: malformed\n"
    state = _collect_ref_vars(cond, source, refs) + [
        v for v in _collect_ref_vars(body, source, refs)
        if v not in _collect_ref_vars(cond, source, refs)
    ]
    if not state:
        return f"{indent}// UNSUPPORTED-WHILE: no mutable ref state to thread\n"
    cond_src = _lower_expression(cond, source)
    # Loop body: sequential mutations. A sequence -> each element as a
    # statement; a single expression -> one statement.
    if body.type == "sequence_expression":
        elems = body.named_children
    else:
        elems = [body]
    body_lines = "".join(_lower_stmt_expr(e, source, "    ", refs) for e in elems)
    if "UNSUPPORTED" in body_lines or "UNSUPPORTED" in cond_src:
        return f"{indent}// UNSUPPORTED-WHILE: body/condition not fully lowerable\n"
    loop_name = f"_while{len(_HOISTED_LOOPS)}"
    state_decls = ", ".join(f"{refs[v]} {v} = 0" for v in state)
    _HOISTED_LOOPS.append(
        f"while_loop {loop_name}({cond_src}, {state_decls}) {{\n{body_lines}}}\n"
    )
    slot_lines = "".join(f"{indent}slot {refs[v]} _{v}_r = {v};\n" for v in state)
    slot_args = ", ".join(f"_{v}_r" for v in state)
    writeback = "".join(f"{indent}{v} = _{v}_r;\n" for v in state)
    return (
        f"{slot_lines}"
        f"{indent}loop {loop_name}({cond_src}, {slot_args});\n"
        f"{writeback}"
    )


def _lower_stmt_expr(node, source: bytes, indent: str,
                     refs: Optional[dict] = None) -> str:
    """Lower one side-effecting expression in STATEMENT position (a
    non-final element of a sequence `e1; e2; …`). The common imperative
    cases are a ref assignment `r := e` -> Sutra `r = e;` and a `while`
    loop; anything else (e.g. a call evaluated for its effect) lowers to
    a bare expression statement `expr;`."""
    if node.type == "while_expression" and refs is not None:
        return _lower_while(node, source, indent, refs)
    if node.type == "set_expression":
        # `a.(i) <- v` -> RAM write at base+i. Array set is statement-only.
        kids = node.named_children
        target = kids[0] if kids else None
        val = kids[1] if len(kids) > 1 else None
        if target is not None and target.type == "array_get_expression":
            tk = target.named_children
            arr = tk[0] if tk else None
            idx = tk[1] if len(tk) > 1 else None
            arr_name = _node_text(arr, source) if arr is not None else ""
            idx_src = _lower_expression(idx, source) if idx is not None else "0"
            val_src = _lower_expression(val, source) if val is not None else "0"
            if arr_name in _INT_DICT_ARRAYS:
                return f"{indent}{arr_name}[{idx_src}] = {val_src};\n"
            if arr_name in _RAM_ARRAYS:
                base = _RAM_ARRAYS[arr_name]
                addr = idx_src if base == 0 else f"{base} + {idx_src}"
                return f"{indent}ramWrite({addr}, {val_src});\n"
            return f"{indent}// UNSUPPORTED-SET: array set on unknown array '{arr_name}'\n"
    if node.type == "infix_expression":
        op = node.child_by_field_name("operator")
        if op is not None and _node_text(op, source) == ":=":
            left = node.child_by_field_name("left")
            right = node.child_by_field_name("right")
            lhs = _lower_expression(left, source) if left is not None else "_"
            rhs = _lower_expression(right, source) if right is not None else "0"
            return f"{indent}{lhs} = {rhs};\n"
    return f"{indent}{_lower_expression(node, source)};\n"


def _lower_body_to_statements(body, source: bytes, indent: str,
                              record_types=frozenset(),
                              refs: Optional[dict] = None) -> str:
    """Lower a function-body expression into Sutra statements. A
    `let x = e in rest` becomes a local declaration followed by the
    lowering of `rest`; a `sequence_expression` (`e1; …; eN`) becomes
    statements for `e1 … e(N-1)` and the lowering of `eN`; a `while` in
    statement position becomes a hoisted Sutra `while_loop`; a
    `record_expression` body becomes axon construction; the final
    (non-let) expression becomes `return …;`."""
    if refs is None:
        refs = {}
    if body.type == "record_expression":
        return _lower_record_body(body, source, indent)
    _unwrapped = _unwrap_parens(body)
    if _unwrapped is not None and _unwrapped.type == "tuple_expression":
        return _lower_tuple_body(_unwrapped, source, indent)
    _opt = _option_kind(_unwrapped, source)
    if _opt is not None:
        return _lower_option_body(_opt, source, indent)
    _var = _variant_value_kind(_unwrapped, source)
    if _var is not None:
        return _lower_variant_value_body(_var, source, indent)
    if body.type == "match_expression" and _is_option_match(body, source):
        return _lower_option_match_body(body, source, indent)
    if body.type == "match_expression" and _is_variant_match(body, source):
        return _lower_variant_match_body(body, source, indent)
    if body.type == "let_expression":
        kids = body.named_children
        if len(kids) >= 2:
            *bindings, in_body = kids
            out = ""
            for b in bindings:
                if b.type == "value_definition":
                    out += _lower_local_binding(b, source, indent, record_types, refs)
                else:
                    out += f"{indent}// UNSUPPORTED-LET-IN-PART: {b.type}\n"
            out += _lower_body_to_statements(in_body, source, indent, record_types, refs)
            return out
    if body.type == "sequence_expression":
        kids = body.named_children
        if kids:
            *stmts, last = kids
            out = ""
            for s in stmts:
                out += _lower_stmt_expr(s, source, indent, refs)
            out += _lower_body_to_statements(last, source, indent, record_types, refs)
            return out
    if body.type == "application_expression":
        hoisted = _hoist_record_args(body, source, indent)
        if hoisted is not None:
            return hoisted
    # Aggregate-literal args nested inside a larger return expression
    # (`f {..} + g {..}`): hoist them to temps, then lower the expression — the
    # call sites now reference the temps via `_ARG_HOIST`.
    deep = _hoist_aggregate_args_deep(body, source, indent)
    if deep is not None:
        prelude, added = deep
        try:
            replaced = _lower_expression(body, source)
        finally:
            for nid in added:
                _ARG_HOIST.pop(nid, None)
        return prelude + f"{indent}return {replaced};\n"
    return f"{indent}return {_lower_expression(body, source)};\n"


# Sutra comparison operator → its logical negation. Used to turn an
# OCaml halt-condition (`if n = 0 then base else recurse`) into the
# loop's *continue* condition.
_NEG_CMP = {"==": "!=", "!=": "==", "<": ">=", ">": "<=", "<=": ">", ">=": "<"}


def _self_call_args(node, name: str, arity: int, source: bytes):
    """If `node` is exactly `name arg1 … arg{arity}` (a self-application
    at the right arity), return the list of arg nodes; else None."""
    if node.type != "application_expression":
        return None
    kids = node.named_children
    if not kids:
        return None
    fn = kids[0]
    if fn.type != "value_path" or _node_text(fn, source) != name:
        return None
    args = kids[1:]
    if len(args) != arity:
        return None
    return args


def _negate_cond(cond, source: bytes) -> Optional[str]:
    """Negate an OCaml halt condition into the loop's *continue* condition.
    A single infix comparison is inverted precisely via `_NEG_CMP`
    (`n = 0` -> `n != 0`); any other BOOLEAN condition (a bool flag, `&&`/`||`,
    `not …`, a predicate call) is negated generally with Sutra `!(…)` — OCaml
    `if` requires a bool, so this is always valid."""
    if cond is None:
        return None
    if cond.type == "infix_expression":
        op = cond.child_by_field_name("operator")
        left = cond.child_by_field_name("left")
        right = cond.child_by_field_name("right")
        if op is not None and left is not None and right is not None:
            sutra_op = _OP_MAP.get(_node_text(op, source))
            neg = _NEG_CMP.get(sutra_op) if sutra_op else None
            if neg is not None:
                return (f"{_lower_expression(left, source)} {neg} "
                        f"{_lower_expression(right, source)}")
            # A boolean infix (&&, ||) — fall through to general `!(…)` negation.
    return f"!({_lower_expression(cond, source)})"


def _try_lower_tail_recursive(
    name: str, params: list[tuple[str, str]], ret: str, body, source: bytes,
) -> Optional[str]:
    """Try to lower a TAIL-recursive `let rec` of the accumulator shape
    `let rec f p1 … pk = if COND then BASE else f a1 … ak` (or with the
    self-call in the THEN branch) to a Sutra declared `while_loop`. The
    recursion becomes bounded substrate iteration — no self-calling
    function (which would not terminate through the fuzzy-if blend).
    Returns the emitted Sutra (loop decl + function) or None if the body
    is not this exact shape (caller then falls back to UNSUPPORTED).

    Verified on the substrate: `let rec sum_to acc n = if n = 0 then acc
    else sum_to (acc + n) (n - 1)` with `sum_to 0 5` decodes to 15."""
    if body.type != "if_expression":
        return None
    cond = body.child_by_field_name("condition")
    then_c = else_c = None
    for c in body.named_children:
        if c.type == "then_clause":
            then_c = c
        elif c.type == "else_clause":
            else_c = c
    if then_c is None or else_c is None or not then_c.named_children \
            or not else_c.named_children:
        return None
    then_e = then_c.named_children[0]
    else_e = else_c.named_children[0]
    arity = len(params)
    then_args = _self_call_args(then_e, name, arity, source)
    else_args = _self_call_args(else_e, name, arity, source)
    # Exactly ONE branch must be the self-call (the other is the base).
    if (then_args is None) == (else_args is None):
        return None
    if else_args is not None:
        cont = _negate_cond(cond, source)  # halt when COND, loop while not
        rec_args, base = else_args, then_e
    else:
        cont = _lower_expression(cond, source)  # loop while COND
        rec_args, base = then_args, else_e
    if cont is None:
        return None

    loop_name = f"_rec_{name}"
    state_decls = ", ".join(f"{ty} {nm} = 0" for nm, ty in params)
    # Simultaneous state update via temporaries: compute every new value
    # from the OLD params first (`T _ti = e_i;`), then assign all params
    # (`p_i = _ti;`). A naive sequential `p1 = e1; p2 = e2;` is wrong when
    # a later arg reads a param an earlier line already overwrote — e.g. a
    # swap `f y x` (measured: `swaploop 7 9 2` gave 9 instead of 7).
    temp_decls = "".join(
        f"    {ty} _t{i} = {_lower_expression(arg, source)};\n"
        for i, ((_nm, ty), arg) in enumerate(zip(params, rec_args))
    )
    assigns = "".join(f"    {nm} = _t{i};\n" for i, (nm, _ty) in enumerate(params))
    body_lines = temp_decls + assigns
    loop_decl = f"while_loop {loop_name}({cont}, {state_decls}) {{\n{body_lines}}}\n"

    slot_lines = "".join(f"    slot {ty} _{nm}_r = {nm};\n" for nm, ty in params)
    slot_args = ", ".join(f"_{nm}_r" for nm, _ty in params)
    writeback = "".join(f"    {nm} = _{nm}_r;\n" for nm, _ty in params)
    params_src = ", ".join(f"{ty} {nm}" for nm, ty in params)
    base_src = _lower_expression(base, source)
    fn = (
        f"function {ret} {name}({params_src}) {{\n"
        f"{slot_lines}"
        f"    loop {loop_name}({cont}, {slot_args});\n"
        f"{writeback}"
        f"    return {base_src};\n"
        f"}}\n"
    )
    return loop_decl + fn


# Associative + commutative integer combine ops. The accumulator transform below
# folds leaves in the REVERSE order of the recursion, so the result is preserved
# only for ops where order does not matter — `+` and `*`. NOT `-` / `/` (the
# reversed fold would change the value): those stay UNSUPPORTED, not faked.
_FOLD_OPS = {"+", "*"}


def _try_lower_foldable_nontail_recursive(
    name: str, params: list[tuple[str, str]], ret: str, body, source: bytes,
) -> Optional[str]:
    """CPS / accumulator transform for a FOLDABLE non-tail recursion of the shape
    `let rec f n = if COND then BASE else (LEAF <OP> f(REC))` (single param), where
    OP is associative + commutative (`+` or `*`). The pending work `LEAF OP _` — which
    in a stack language sits on the call stack — is reified as an accumulator carried
    by a Sutra `while_loop` (the trampoline): `acc` starts at BASE, each step folds
    LEAF into `acc` and advances `n` via REC. This lets raw non-tail factorial/sum
    compile + run on the substrate instead of UNSUPPORTED.

    Only `+`/`*` qualify (see `_FOLD_OPS`): the transform folds leaves in the reverse
    order of the recursion, which preserves the result only for commutative+associative
    ops. Returns the emitted Sutra (loop decl + function) or None (→ UNSUPPORTED).
    Substrate-verified: `fact 5 = 120`, `sum 5 = 15`."""
    if len(params) != 1 or body.type != "if_expression":
        return None
    cond = body.child_by_field_name("condition")
    if cond is None:
        return None
    then_c = next((c for c in body.named_children if c.type == "then_clause"), None)
    else_c = next((c for c in body.named_children if c.type == "else_clause"), None)
    if (then_c is None or else_c is None or not then_c.named_children
            or not else_c.named_children):
        return None
    then_e = then_c.named_children[0]
    else_e = else_c.named_children[0]

    def _foldable(node):
        """`LEAF OP f(REC)` / `f(REC) OP LEAF` with OP in _FOLD_OPS and a single-arg
        self-call → (op_text, leaf_node, rec_arg_node); else None."""
        n = _unwrap_parens(node)
        if n is None or n.type != "infix_expression":
            return None
        op = n.child_by_field_name("operator")
        left = n.child_by_field_name("left")
        right = n.child_by_field_name("right")
        if op is None or left is None or right is None:
            return None
        op_text = _node_text(op, source)
        if op_text not in _FOLD_OPS:
            return None
        lc = _self_call_args(_unwrap_parens(left), name, 1, source)
        rc = _self_call_args(_unwrap_parens(right), name, 1, source)
        if (lc is None) == (rc is None):
            return None  # exactly one operand must be the self-call
        return (op_text, right, lc[0]) if lc is not None else (op_text, left, rc[0])

    fold_else, fold_then = _foldable(else_e), _foldable(then_e)
    if (fold_else is None) == (fold_then is None):
        return None
    if fold_else is not None:
        cont = _negate_cond(cond, source)            # loop while not COND
        op_text, leaf, rec_arg = fold_else
        base = then_e
    else:
        cont = _lower_expression(cond, source)        # loop while COND
        op_text, leaf, rec_arg = fold_then
        base = else_e
    if cont is None:
        return None

    pname, pty = params[0]
    if pname in _value_paths(base, source):
        # BASE is emitted pre-loop, evaluated at the INITIAL param — a BASE that
        # references the param would be mis-evaluated (MEASURED 2026-06-12:
        # `let rec weird n = if n = 0 then n + 7 else n + weird (n - 1)` ran to
        # 16 on the substrate, ground truth 13). Reject → UNSUPPORTED, not wrong.
        return None
    sutra_op = _OP_MAP.get(op_text, op_text)
    loop_name = f"_rec_{name}"
    leaf_src = _lower_expression(leaf, source)
    rec_src = _lower_expression(rec_arg, source)
    base_src = _lower_expression(base, source)
    if any("UNSUPPORTED" in s for s in (leaf_src, rec_src, base_src, cont)):
        return None
    # while_loop carries (n, acc); simultaneous update via temporaries (new acc from
    # the OLD n and OLD acc; new n from REC of the OLD n).
    loop_decl = (
        f"while_loop {loop_name}({cont}, {pty} {pname} = 0, {pty} _acc = 0) {{\n"
        f"    {pty} _t_n = {rec_src};\n"
        f"    {pty} _t_acc = _acc {sutra_op} {leaf_src};\n"
        f"    {pname} = _t_n;\n"
        f"    _acc = _t_acc;\n"
        f"}}\n"
    )
    fn = (
        f"function {ret} {name}({pty} {pname}) {{\n"
        f"    {pty} _acc = {base_src};\n"
        f"    slot {pty} _{pname}_r = {pname};\n"
        f"    slot {pty} _acc_r = _acc;\n"
        f"    loop {loop_name}({cont}, _{pname}_r, _acc_r);\n"
        f"    return _acc_r;\n"
        f"}}\n"
    )
    return loop_decl + fn


def _lower_let_binding(lb, source: bytes, record_types=frozenset(),
                       is_rec: bool = False) -> str:
    kids = lb.named_children
    if not kids:
        return "// UNSUPPORTED-LET: empty let_binding\n"
    name = _node_text(kids[0], source)
    body = kids[-1]
    middle = kids[1:-1]

    has_param = any(k.type == "parameter" for k in middle)
    if not has_param:
        # A zero-parameter `let x = expr` is a value binding, not a
        # function. Lower it to a Sutra top-level constant
        # `<ty> <name> = <expr>;` — top-level var decls are visible inside
        # functions on the substrate (verified). Only simple, lowerable
        # bodies qualify; sequences / refs / the `let () = …` entry point
        # have no `name`-shaped binder or no single-expression body, so
        # they stay UNSUPPORTED rather than emit a footgun.
        if is_rec:
            return (
                f"// UNSUPPORTED-LET-REC: value binding '{name}' "
                "(recursive value, not a function)\n"
            )
        if not _is_identifier(name):
            return (
                f"// UNSUPPORTED-LET: value binding '{name}' "
                "(binder is not a plain identifier)\n"
            )
        # A direct axon-mode variant construction at module scope (`let z = Zero`,
        # `let p = Pair (7, 9)`) -> a top-level multi-statement axon construction
        # (`Axon z; z.add("_tag", …); …`). A top-level Axon is visible inside
        # functions on the substrate (verified), the same as a top-level constant.
        # Same machinery as the local/body/arg positions; nullary stores `_val`=0.
        _vk = _variant_value_kind(_unwrap_parens(body), source)
        if _vk is not None:
            return _emit_variant_construction(_vk, source, "", name)
        # A type annotation (`let x : int = …`) overrides the inferred type.
        ann_type = next((_map_type(k, source, record_types)
                         for k in middle if _is_type_node(k)), None)
        expr_src = _lower_expression(body, source)
        if "UNSUPPORTED" in expr_src:
            return (
                f"// UNSUPPORTED-LET: value binding '{name}' "
                f"(body does not lower to a simple expression: {body.type})\n"
            )
        ty = ann_type if ann_type is not None else _value_binding_type(body, source)
        return f"{ty} {name} = {expr_src};\n"

    params: list[tuple[str, str]] = []
    ret_type: Optional[str] = None
    for k in middle:
        if k.type == "parameter":
            p = _lower_param(k, source, record_types)
            if p is not None:
                params.append(p)
        elif _is_type_node(k):
            ret_type = _map_type(k, source, record_types)
    ret = ret_type if ret_type is not None else _DEFAULT_TYPE
    # Narrow body inference: a function whose body is a string literal
    # returns a Sutra `String`, not the `int` default — emitting
    # `function int … { return "…"; }` would be a misleading type. Other
    # body shapes keep the int default (broad return-type inference is a
    # later item; float fixtures rely on the current default).
    if ret_type is None and body.type == "string":
        ret = "String"
    # A function whose body is a tuple or an option constructor returns an
    # Axon (the positional-/tagged-record carrier), like a record-bodied fn.
    if ret_type is None:
        _ub = _unwrap_parens(body)
        if _ub is not None and (_ub.type == "tuple_expression"
                                or _option_kind(_ub, source) is not None
                                or _variant_value_kind(_ub, source) is not None):
            ret = "Axon"

    if is_rec:
        # `let rec` is general recursion. Sutra's if/else is a defuzz
        # BLEND that evaluates BOTH branches unconditionally, so a
        # self-calling function never terminates on the substrate.
        # TAIL recursion of the accumulator shape lowers to a bounded
        # Sutra `while_loop` instead (substrate-verified). Anything that
        # is NOT that shape (non-tail recursion like factorial, or a
        # non-comparison halt condition) we surface as UNSUPPORTED rather
        # than emit a runtime footgun.
        tail = _try_lower_tail_recursive(name, params, ret, body, source)
        if tail is not None:
            return tail
        # FOLDABLE non-tail recursion (factorial/sum: `LEAF +|* f(n-1)`) — the CPS/
        # accumulator transform reifies the pending work as an accumulator carried by
        # a while_loop (trampoline). Only +/* (assoc.+comm.); others stay UNSUPPORTED.
        fold = _try_lower_foldable_nontail_recursive(name, params, ret, body, source)
        if fold is not None:
            return fold
        return (
            f"// UNSUPPORTED-LET-REC: recursive function '{name}' is not the "
            "tail-recursive accumulator shape nor a foldable (+/*) non-tail "
            "recursion; Sutra's fuzzy if/else evaluates both branches, so general "
            "recursion does not terminate — needs a loop/recur encoding "
            "(queue.md Transpiler track)\n"
        )

    params_src = ", ".join(f"{ty} {nm}" for nm, ty in params)
    body_src = _lower_body_to_statements(body, source, "    ", record_types, {})
    return f"function {ret} {name}({params_src}) {{\n{body_src}}}\n"


def lower(source: str, source_path: Optional[pathlib.Path] = None) -> str:
    """Top-level entry point. OCaml source string → Sutra source string.

    `source_path` is accepted for harness parity with `sutra-from-ts`
    (where it drives import resolution); the OCaml MVP has no module
    handling yet, so it is currently unused.
    """
    import tree_sitter
    import tree_sitter_ocaml as tso

    lang = tree_sitter.Language(tso.language_ocaml())
    parser = tree_sitter.Parser(lang)
    src_bytes = source.encode("utf-8")
    tree = parser.parse(src_bytes)

    # Prepass: collect record type names so record-typed params map to a
    # Sutra Axon. `type X = { … }` parses as
    # type_definition > type_binding > type_constructor (X) +
    # record_declaration.
    record_types: set[str] = set()
    _CONSTRUCTORS.clear()
    _VARIANT_CTORS.clear()
    _ARG_HOIST.clear()
    _HOISTED_LOOPS.clear()
    _HOISTED_DECLS.clear()
    _RAM_ARRAYS.clear()
    _INT_DICT_ARRAYS.clear()
    for child in tree.root_node.named_children:
        if child.type != "type_definition":
            continue
        for tb in child.named_children:
            if tb.type != "type_binding":
                continue
            tc = next(
                (c for c in tb.named_children if c.type == "type_constructor"), None
            )
            rd = next(
                (c for c in tb.named_children if c.type == "record_declaration"), None
            )
            if tc is not None and rd is not None:
                record_types.add(_node_text(tc, src_bytes))
            # Variant `type X = A | B | …` -> nullary constructors become
            # enum tags (A=0, B=1, …). The tag index advances for every
            # constructor (preserving OCaml's order) but only nullary
            # ones are mapped; a parameterised constructor (`C of t`) is
            # left out, so using it lowers to UNSUPPORTED.
            vd = next(
                (c for c in tb.named_children if c.type == "variant_declaration"), None
            )
            if vd is not None:
                ctor_decls = [c for c in vd.named_children
                              if c.type == "constructor_declaration"]
                # Axon-mode iff ANY constructor carries an argument. A
                # `constructor_declaration` with >1 named child has a payload
                # type (`C of t`); a bare one (just `constructor_name`) is nullary.
                axon_mode = any(len(cd.named_children) > 1 for cd in ctor_decls)
                # An axon-mode variant value is carried by an Axon, so a param
                # typed with this variant maps to `Axon` (same as a record type).
                if axon_mode and tc is not None:
                    record_types.add(_node_text(tc, src_bytes))
                for idx, cd in enumerate(ctor_decls):
                    cn = next((c for c in cd.named_children
                               if c.type == "constructor_name"), None)
                    if cn is None:
                        continue
                    name = _node_text(cn, src_bytes)
                    # Arity = number of payload type components. `Origin` -> 0,
                    # `Lit of int` -> 1, `Pair of int * int` -> 2 (each tuple
                    # component is a separate type child under the declaration).
                    arity = sum(1 for c in cd.named_children
                                if c.type != "constructor_name")
                    if axon_mode:
                        # Uniform tagged-axon: all ctors of this type (param +
                        # nullary) get (tag, arity). NOT enum-int.
                        _VARIANT_CTORS[name] = (idx, arity)
                    elif arity == 0:
                        _CONSTRUCTORS[name] = idx  # pure-enum variant

    # After record types are known: collect top-level binding names (so the
    # nested-function closed-ness check can tell a top-level reference from
    # an enclosing-local capture) and which functions return an Axon.
    _TOPLEVEL_NAMES.clear()
    _AXON_RETURNING.clear()
    for child in tree.root_node.named_children:
        if child.type != "value_definition":
            continue
        for lb in child.named_children:
            if lb.type == "let_binding" and lb.named_children:
                nm = _node_text(lb.named_children[0], src_bytes)
                _TOPLEVEL_NAMES.add(nm)
                if _fn_returns_axon(lb, src_bytes, record_types):
                    _AXON_RETURNING.add(nm)

    out: list[str] = [_HEADER]
    for child in tree.root_node.named_children:
        if child.type == "value_definition":
            # `let rec` carries the `rec` keyword as an anonymous token;
            # detect it from the leading tokens so the recursion guard
            # in _lower_let_binding fires.
            toks = _node_text(child, src_bytes).split(None, 2)
            is_rec = len(toks) >= 2 and toks[0] == "let" and toks[1] == "rec"
            for lb in child.named_children:
                if lb.type == "let_binding":
                    out.append(
                        _lower_let_binding(lb, src_bytes, record_types, is_rec=is_rec)
                    )
        elif child.type == "type_definition":
            # Erased — the record type name was collected in the prepass;
            # the declaration emits nothing (like a TS interface).
            continue
        elif child.type == "comment":
            continue
        else:
            out.append(f"// UNSUPPORTED-TOPLEVEL: {child.type}\n")
    # Sutra loops and hoisted nested functions are top-level declarations;
    # insert them just after the header, before the functions that use
    # them. Hoisted nested functions first (a loop body may call one).
    if _HOISTED_DECLS or _HOISTED_LOOPS:
        out[1:1] = list(_HOISTED_DECLS) + list(_HOISTED_LOOPS)
    return "".join(out)
