"""OCaml → Sutra lowering pass.

Walks a tree-sitter-ocaml parse tree and emits Sutra (.su) source.
Modeled on `sutra-from-ts/sutra_from_ts/lower.py`.

Why OCaml first (per todo.md §"Multi-language transpiler frontends"):
Sutra is a purely functional language, so ML-family syntax — algebraic
data types, pattern matching, expression-oriented bodies — is the
closest structural match. The functional source languages transpile
*cleanly* where JS fights the substrate.

Scope today (MVP — this is the first frontend tick):

- Top-level `let name p1 p2 … = body` value definitions with ≥ 1
  parameter lower to Sutra `function` declarations. The OCaml entry
  convention `let main () = …` (a single `unit` parameter) lowers to a
  zero-argument `function … main()`.
- Parameters: plain `a` (untyped — defaults to `int`, see note below) or
  typed `(x : int)`. A trailing return-type annotation (`… : int = body`)
  is read when present, else the return type defaults to `int`.
- Expression bodies: infix arithmetic (`+ - * /` and the float forms
  `+. -. *. /.`), comparisons (`= <> < > <= >=`), variable references,
  integer/float literals, function application (`f a b` → `f(a, b)`),
  and parenthesised expressions.

Type inference is deliberately *not* attempted yet: OCaml is globally
Hindley–Milner inferred, and replicating that is a later item. The MVP
defaults unannotated parameters and return types to `int` (OCaml's `+`
family is int-only; `+.` is float), which is correct for the integer
arithmetic fixtures and explicit for everything else — annotate the
OCaml source to get other types until inference lands.

Anything outside this scope lowers to a `// UNSUPPORTED-*` Sutra comment
(or an inline `/* UNSUPPORTED-EXPR: … */`) so the caller can see exactly
what blocked translation, the same convention `sutra-from-ts` uses.
"""

from __future__ import annotations

import pathlib
from typing import Optional


_HEADER = (
    "// Generated by sutra-from-ocaml. See sdk/sutra-from-ocaml/README.md.\n"
    "\n"
)

# OCaml type constructor → Sutra type name. Unmapped constructors fall
# back to the MVP default (`int`); widen this table as fixtures need
# float/bool/string/record types.
_OCAML_TYPE_TO_SUTRA = {
    "int": "int",
    "float": "float",
    "bool": "bool",
    "string": "String",
    "unit": "void",
}

_DEFAULT_TYPE = "int"

# OCaml infix operator text → Sutra operator. The float-arithmetic forms
# (`+.` …) collapse onto the same Sutra arithmetic ops — Sutra's number
# axis is unified, so there is no separate float operator surface. OCaml
# structural `=` / `<>` become Sutra `==` / `!=`.
_OP_MAP = {
    "+": "+", "-": "-", "*": "*", "/": "/",
    "+.": "+", "-.": "-", "*.": "*", "/.": "/",
    "=": "==", "<>": "!=",
    "<": "<", ">": ">", "<=": "<=", ">=": ">=",
}


def _node_text(node, source: bytes) -> str:
    return source[node.start_byte:node.end_byte].decode("utf-8")


def _is_type_node(node) -> bool:
    """True for the OCaml grammar's type-expression nodes (the things
    that show up as a return-type annotation or inside a typed_pattern)."""
    return node.type == "type_constructor_path" or node.type.endswith("_type")


def _map_type(type_node, source: bytes) -> str:
    if type_node is None:
        return _DEFAULT_TYPE
    text = _node_text(type_node, source).strip()
    return _OCAML_TYPE_TO_SUTRA.get(text, _DEFAULT_TYPE)


def _lower_expression(node, source: bytes) -> str:
    t = node.type
    if t == "number":
        return _node_text(node, source)
    if t == "value_path":
        # A variable / function reference. MVP carries the path text
        # through verbatim (`a`, and later `Module.name`).
        return _node_text(node, source)
    if t == "parenthesized_expression":
        inner = node.named_children[0] if node.named_children else None
        return f"({_lower_expression(inner, source)})" if inner is not None else "()"
    if t == "infix_expression":
        left = node.child_by_field_name("left")
        op = node.child_by_field_name("operator")
        right = node.child_by_field_name("right")
        op_text = _node_text(op, source) if op is not None else "+"
        op_sutra = _OP_MAP.get(op_text, op_text)
        left_src = _lower_expression(left, source) if left is not None else "0"
        right_src = _lower_expression(right, source) if right is not None else "0"
        return f"{left_src} {op_sutra} {right_src}"
    if t == "application_expression":
        kids = node.named_children
        if not kids:
            return "/* UNSUPPORTED-APP: empty */"
        fn_src = _lower_expression(kids[0], source)
        arg_srcs = [_lower_expression(a, source) for a in kids[1:]]
        return f"{fn_src}({', '.join(arg_srcs)})"
    if t == "if_expression":
        # OCaml `if c then a else b` is an *expression*. Lower it to the
        # same strong-defuzz blend the TS frontend uses for if/else:
        #   weight = (1 + truth_axis(defuzzy(c))) / 2
        #   result = weight * a + (1 - weight) * b
        # i.e. ((1 + truth_axis(defuzzy(c))) * a
        #       + (1 - truth_axis(defuzzy(c))) * b) / 2
        # When c defuzzes true (+1) the blend is a; false (-1) it is b;
        # at the midpoint it interpolates. Differentiable, fuzzy, no
        # host-side branch — the substrate decides. An `if c then a`
        # with no else is the implicit-zero-else form (OCaml types that
        # unit; we mirror the TS select-with-implicit-zero shape).
        cond = node.child_by_field_name("condition")
        then_c = None
        else_c = None
        for c in node.named_children:
            if c.type == "then_clause":
                then_c = c
            elif c.type == "else_clause":
                else_c = c
        cond_src = _lower_expression(cond, source) if cond is not None else "false"
        then_expr = (
            then_c.named_children[0]
            if then_c is not None and then_c.named_children else None
        )
        then_src = _lower_expression(then_expr, source) if then_expr is not None else "0"
        w = f"truth_axis(defuzzy({cond_src}))"
        # Each product term is fully parenthesised — `((w) * (branch))` —
        # and the two terms are grouped before `/ 2`. A bare
        # `(weight) * (atom) + …` would emit `… * (a) + (b) …`, and the
        # Sutra parser reads a parenthesised atom followed by a binary
        # operator (`(a) + …`) as a *cast* `(Type) expr`, which the
        # codegen rejects (CastExpr). Full grouping avoids putting a
        # `(atom)` immediately before an infix operator.
        if else_c is not None and else_c.named_children:
            else_src = _lower_expression(else_c.named_children[0], source)
            return (
                f"(((1 + {w}) * ({then_src})) "
                f"+ ((1 - {w}) * ({else_src}))) / 2"
            )
        return f"(((1 + {w}) * ({then_src}))) / 2"
    return f"/* UNSUPPORTED-EXPR: {t} */"


def _lower_param(param_node, source: bytes) -> Optional[tuple[str, str]]:
    """Lower one `parameter` node → (name, sutra_type), or None for the
    `unit` parameter (`let main () = …`), which contributes no Sutra
    parameter."""
    child = param_node.named_children[0] if param_node.named_children else None
    if child is None:
        return None
    if child.type == "unit":
        return None
    if child.type == "value_pattern":
        return (_node_text(child, source), _DEFAULT_TYPE)
    if child.type == "typed_pattern":
        vp = None
        tp = None
        for c in child.named_children:
            if c.type == "value_pattern":
                vp = c
            elif _is_type_node(c):
                tp = c
        name = _node_text(vp, source) if vp is not None else "_arg"
        ptype = _map_type(tp, source) if tp is not None else _DEFAULT_TYPE
        return (name, ptype)
    # Other pattern kinds (tuple / constructor destructuring) are a later
    # item; carry the name through as an int-typed param for now.
    return (_node_text(child, source), _DEFAULT_TYPE)


def _lower_let_binding(lb, source: bytes) -> str:
    kids = lb.named_children
    if not kids:
        return "// UNSUPPORTED-LET: empty let_binding\n"
    name = _node_text(kids[0], source)
    body = kids[-1]
    middle = kids[1:-1]

    has_param = any(k.type == "parameter" for k in middle)
    if not has_param:
        # A zero-parameter `let x = expr` is a value binding, not a
        # function. Top-level Sutra constants are a later item.
        return (
            f"// UNSUPPORTED-LET: value binding '{name}' (no parameters; "
            "only function-shaped lets lower today)\n"
        )

    params: list[tuple[str, str]] = []
    ret_type: Optional[str] = None
    for k in middle:
        if k.type == "parameter":
            p = _lower_param(k, source)
            if p is not None:
                params.append(p)
        elif _is_type_node(k):
            ret_type = _map_type(k, source)

    ret = ret_type if ret_type is not None else _DEFAULT_TYPE
    params_src = ", ".join(f"{ty} {nm}" for nm, ty in params)
    body_src = _lower_expression(body, source)
    return (
        f"function {ret} {name}({params_src}) {{\n"
        f"    return {body_src};\n"
        f"}}\n"
    )


def lower(source: str, source_path: Optional[pathlib.Path] = None) -> str:
    """Top-level entry point. OCaml source string → Sutra source string.

    `source_path` is accepted for harness parity with `sutra-from-ts`
    (where it drives import resolution); the OCaml MVP has no module
    handling yet, so it is currently unused.
    """
    import tree_sitter
    import tree_sitter_ocaml as tso

    lang = tree_sitter.Language(tso.language_ocaml())
    parser = tree_sitter.Parser(lang)
    src_bytes = source.encode("utf-8")
    tree = parser.parse(src_bytes)

    out: list[str] = [_HEADER]
    for child in tree.root_node.named_children:
        if child.type == "value_definition":
            for lb in child.named_children:
                if lb.type == "let_binding":
                    out.append(_lower_let_binding(lb, src_bytes))
        elif child.type == "comment":
            continue
        else:
            out.append(f"// UNSUPPORTED-TOPLEVEL: {child.type}\n")
    return "".join(out)
